#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/GameCore/ELevelPerformanceType.h"
#include "unitysdk/System/Object.h"

namespace RPG::GameCore { class PerformanceBackupConfig; }
namespace RPG::GameCore { class PerformanceSortedItem; }

#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_CREATE_OFFSET UNITYSDK_OFFSET(0xC036F00)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GETPERFORMANCEDESC_OFFSET UNITYSDK_OFFSET(0xC037810)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_HASCG_OFFSET UNITYSDK_OFFSET(0xC037A20)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_INDENT_OFFSET UNITYSDK_OFFSET(0xC0379E0)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_ISBRANCH_OFFSET UNITYSDK_OFFSET(0xC0379C0)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCEBACKUPCONFIG_OFFSET UNITYSDK_OFFSET(0xC037A00)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCEID_OFFSET UNITYSDK_OFFSET(0xC0379A0)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCEITEM_OFFSET UNITYSDK_OFFSET(0xC037A40)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCETYPE_OFFSET UNITYSDK_OFFSET(0xC037980)
#define RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xC037800)

namespace RPG::Client::MissionReplayData
{
	inline static constexpr unsigned int NormalMissionReplayPerformanceData_TypeDefinitionIndex = 69730;

	class NormalMissionReplayPerformanceData : public ::System::Object
	{
	public:
		::RPG::GameCore::PerformanceSortedItem* _PerformanceItem; // 0x10

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::MissionReplayData::NormalMissionReplayPerformanceData* Create(::RPG::GameCore::PerformanceSortedItem* a1)
		{
			return ((::RPG::Client::MissionReplayData::NormalMissionReplayPerformanceData*(*)(::RPG::GameCore::PerformanceSortedItem*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_CREATE_OFFSET))(a1);
		}

		::RPG::Client::TextID GetPerformanceDesc()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GETPERFORMANCEDESC_OFFSET))(this);
		}

		::System::Boolean get_IsBranch()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_ISBRANCH_OFFSET))(this);
		}

		::System::Int32 get_Indent()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_INDENT_OFFSET))(this);
		}

		::RPG::GameCore::ELevelPerformanceType get_PerformanceType()
		{
			return ((::RPG::GameCore::ELevelPerformanceType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCETYPE_OFFSET))(this);
		}

		::System::UInt32 get_PerformanceID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCEID_OFFSET))(this);
		}

		::RPG::GameCore::PerformanceBackupConfig* get_PerformanceBackupConfig()
		{
			return ((::RPG::GameCore::PerformanceBackupConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCEBACKUPCONFIG_OFFSET))(this);
		}

		::System::Boolean get_HasCg()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_HASCG_OFFSET))(this);
		}

		::RPG::GameCore::PerformanceSortedItem* get_PerformanceItem()
		{
			return ((::RPG::GameCore::PerformanceSortedItem*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MISSIONREPLAYDATA_NORMALMISSIONREPLAYPERFORMANCEDATA_GET_PERFORMANCEITEM_OFFSET))(this);
		}
	};
}
