#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_8ADAAB4A2E4AC573.h"

namespace RPG::Client { class Effect_Transform; }
namespace RPG::GameCore { class AdventureCharacterFloatingConfig; }
namespace UnityEngine { class AnimationCurve; }

#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_GETCURRENTFLOATINGCONFIG_OFFSET UNITYSDK_OFFSET(0x1223EA50)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_GETSOURCEFLOATINGCONFIG_OFFSET UNITYSDK_OFFSET(0x1221D4D0)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONMODELARTLOADED_OFFSET UNITYSDK_OFFSET(0x1223F510)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONMODELARTUNLOADED_OFFSET UNITYSDK_OFFSET(0x1223F730)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONMODELROOTLOADED_OFFSET UNITYSDK_OFFSET(0x1223F390)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONUNINIT_OFFSET UNITYSDK_OFFSET(0x1223EAA0)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_OVERRIDEFLOATINGCONFIG_OFFSET UNITYSDK_OFFSET(0x1221D3F0)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_SETUP_OFFSET UNITYSDK_OFFSET(0x1221D600)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_TICK_OFFSET UNITYSDK_OFFSET(0x1221D6E0)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__APPLYFLOATINGHEIGHT_1_OFFSET UNITYSDK_OFFSET(0x1223EC80)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__APPLYFLOATINGHEIGHT_OFFSET UNITYSDK_OFFSET(0x1223F3E0)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__CLEANUPFLOATINGEFFECT_OFFSET UNITYSDK_OFFSET(0x1223EB10)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__CTOR_OFFSET UNITYSDK_OFFSET(0x1223F7C0)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__EVALUATEFLOATINGHEIGHT_OFFSET UNITYSDK_OFFSET(0x1223EB60)
#define RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__INITFLOATINGHEIGHT_OFFSET UNITYSDK_OFFSET(0x1223E8B0)

namespace RPG::GameCore
{
	inline static constexpr unsigned int CharacterModelComponent_CharacterFloatingFeature_TypeDefinitionIndex = 57346;

	class CharacterModelComponent_CharacterFloatingFeature : public ::Class_1_8ADAAB4A2E4AC573
	{
	public:
		::RPG::GameCore::AdventureCharacterFloatingConfig* _FloatingConfig; // 0x20
		::RPG::GameCore::AdventureCharacterFloatingConfig* _OverrideFloatingConfig; // 0x28
		::RPG::Client::Effect_Transform* _PropEffect_Transform; // 0x30
		::UnityEngine::AnimationCurve* _FloatingCurve; // 0x38
		::System::Single _FloatingLoopTime; // 0x40

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__CTOR_OFFSET))(this);
		}

		::System::Void Setup(::RPG::GameCore::AdventureCharacterFloatingConfig* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::AdventureCharacterFloatingConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_SETUP_OFFSET))(this, a1);
		}

		::System::Void OverrideFloatingConfig(::RPG::GameCore::AdventureCharacterFloatingConfig* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::AdventureCharacterFloatingConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_OVERRIDEFLOATINGCONFIG_OFFSET))(this, a1);
		}

		::RPG::GameCore::AdventureCharacterFloatingConfig* GetCurrentFloatingConfig()
		{
			return ((::RPG::GameCore::AdventureCharacterFloatingConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_GETCURRENTFLOATINGCONFIG_OFFSET))(this);
		}

		::RPG::GameCore::AdventureCharacterFloatingConfig* GetSourceFloatingConfig()
		{
			return ((::RPG::GameCore::AdventureCharacterFloatingConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_GETSOURCEFLOATINGCONFIG_OFFSET))(this);
		}

		::System::Void OnUninit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONUNINIT_OFFSET))(this);
		}

		::System::Void Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_TICK_OFFSET))(this, a1);
		}

		::System::Void OnModelRootLoaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONMODELROOTLOADED_OFFSET))(this);
		}

		::System::Void OnModelArtLoaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONMODELARTLOADED_OFFSET))(this);
		}

		::System::Void OnModelArtUnloaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE_ONMODELARTUNLOADED_OFFSET))(this);
		}

		::System::Void _InitFloatingHeight()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__INITFLOATINGHEIGHT_OFFSET))(this);
		}

		::System::Void _CleanupFloatingEffect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__CLEANUPFLOATINGEFFECT_OFFSET))(this);
		}

		::System::Void _ApplyFloatingHeight()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__APPLYFLOATINGHEIGHT_OFFSET))(this);
		}

		::System::Single _EvaluateFloatingHeight()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__EVALUATEFLOATINGHEIGHT_OFFSET))(this);
		}

		::System::Void _ApplyFloatingHeight_1(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERMODELCOMPONENT_CHARACTERFLOATINGFEATURE__APPLYFLOATINGHEIGHT_1_OFFSET))(this, a1);
		}
	};
}
