#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_FINISHTARGETGPTARGETVALUE_OFFSET UNITYSDK_OFFSET(0x1B1C99D0)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_FINISHTARGETGP_OFFSET UNITYSDK_OFFSET(0x1B1C99B0)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_GETREWARDQUESTID_OFFSET UNITYSDK_OFFSET(0x1B1C9990)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_LOCKDESC_OFFSET UNITYSDK_OFFSET(0x1B1C9950)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_TARGETGROUPID_OFFSET UNITYSDK_OFFSET(0x1B1C99F0)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_TITLETEXT_OFFSET UNITYSDK_OFFSET(0x1B1C9930)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_UNLOCKQUESTID_OFFSET UNITYSDK_OFFSET(0x1B1C9970)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_FINISHTARGETGPTARGETVALUE_OFFSET UNITYSDK_OFFSET(0x1B1C99E0)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_FINISHTARGETGP_OFFSET UNITYSDK_OFFSET(0x1B1C99C0)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_GETREWARDQUESTID_OFFSET UNITYSDK_OFFSET(0x1B1C99A0)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_LOCKDESC_OFFSET UNITYSDK_OFFSET(0x1B1C9960)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_TARGETGROUPID_OFFSET UNITYSDK_OFFSET(0x1B1C9A00)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_TITLETEXT_OFFSET UNITYSDK_OFFSET(0x1B1C9940)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_UNLOCKQUESTID_OFFSET UNITYSDK_OFFSET(0x1B1C9980)
#define RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG__CTOR_OFFSET UNITYSDK_OFFSET(0x1B1C9A10)

namespace RPG::Client::LittleGame::FourRotateVoxel
{
	inline static constexpr unsigned int FourRotateVoxelMapInfoConfig_TypeDefinitionIndex = 76351;

	class FourRotateVoxelMapInfoConfig : public ::System::Object
	{
	public:
		::System::Collections::Generic::List_1<::System::String*>* _FinishTargetGP_k__BackingField; // 0x10
		::System::Collections::Generic::List_1<::System::String*>* _FinishTargetGPTargetValue_k__BackingField; // 0x18
		::RPG::Client::TextID _LockDesc_k__BackingField; // 0x20
		::System::UInt32 _TargetGroupID_k__BackingField; // 0x30
		::System::UInt32 _GetRewardQuestID_k__BackingField; // 0x34
		::System::UInt32 _UnlockQuestID_k__BackingField; // 0x38
		::RPG::Client::TextID _TitleText_k__BackingField; // 0x40

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG__CTOR_OFFSET))(this);
		}

		::RPG::Client::TextID get_TitleText()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_TITLETEXT_OFFSET))(this);
		}

		::System::Void set_TitleText(::RPG::Client::TextID a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_TITLETEXT_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_LockDesc()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_LOCKDESC_OFFSET))(this);
		}

		::System::Void set_LockDesc(::RPG::Client::TextID a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_LOCKDESC_OFFSET))(this, a1);
		}

		::System::UInt32 get_UnlockQuestID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_UNLOCKQUESTID_OFFSET))(this);
		}

		::System::Void set_UnlockQuestID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_UNLOCKQUESTID_OFFSET))(this, a1);
		}

		::System::UInt32 get_GetRewardQuestID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_GETREWARDQUESTID_OFFSET))(this);
		}

		::System::Void set_GetRewardQuestID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_GETREWARDQUESTID_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::String*>* get_FinishTargetGP()
		{
			return ((::System::Collections::Generic::List_1<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_FINISHTARGETGP_OFFSET))(this);
		}

		::System::Void set_FinishTargetGP(::System::Collections::Generic::List_1<::System::String*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::String*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_FINISHTARGETGP_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::String*>* get_FinishTargetGPTargetValue()
		{
			return ((::System::Collections::Generic::List_1<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_FINISHTARGETGPTARGETVALUE_OFFSET))(this);
		}

		::System::Void set_FinishTargetGPTargetValue(::System::Collections::Generic::List_1<::System::String*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::String*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_FINISHTARGETGPTARGETVALUE_OFFSET))(this, a1);
		}

		::System::UInt32 get_TargetGroupID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_GET_TARGETGROUPID_OFFSET))(this);
		}

		::System::Void set_TargetGroupID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FOURROTATEVOXEL_FOURROTATEVOXELMAPINFOCONFIG_SET_TARGETGROUPID_OFFSET))(this, a1);
		}
	};
}
