#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Epic/OnlineServices/Result.h"
#include "unitysdk/System/ValueType.h"

namespace System { class Object; }
namespace System { class String; }

#define EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_CLIENTBASEURL_OFFSET UNITYSDK_OFFSET(0x71B80)
#define EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_CLIENTDATAADDRESS_OFFSET UNITYSDK_OFFSET(0x6020)
#define EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_CLIENTDATA_OFFSET UNITYSDK_OFFSET(0x719C0)
#define EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_QUERYID_OFFSET UNITYSDK_OFFSET(0x1D290)
#define EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_RESULTCODE_OFFSET UNITYSDK_OFFSET(0x5F00)
#define EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_ROOMNAME_OFFSET UNITYSDK_OFFSET(0x71AD0)
#define EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_TOKENCOUNT_OFFSET UNITYSDK_OFFSET(0x5FB30)

namespace Epic::OnlineServices::RTCAdmin
{
	inline static constexpr unsigned int QueryJoinRoomTokenCompleteCallbackInfoInternal_TypeDefinitionIndex = 45354;

	struct alignas(8) QueryJoinRoomTokenCompleteCallbackInfoInternal
	{
		::Epic::OnlineServices::Result m_ResultCode; // 0x10
		::System::IntPtr m_ClientData; // 0x18
		::System::IntPtr m_RoomName; // 0x20
		::System::IntPtr m_ClientBaseUrl; // 0x28
		::System::UInt32 m_QueryId; // 0x30
		::System::UInt32 m_TokenCount; // 0x34

		::Epic::OnlineServices::Result get_ResultCode()
		{
			return ((::Epic::OnlineServices::Result(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_RESULTCODE_OFFSET))(this);
		}

		::System::Object* get_ClientData()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_CLIENTDATA_OFFSET))(this);
		}

		::System::IntPtr get_ClientDataAddress()
		{
			return ((::System::IntPtr(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_CLIENTDATAADDRESS_OFFSET))(this);
		}

		::System::String* get_RoomName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_ROOMNAME_OFFSET))(this);
		}

		::System::String* get_ClientBaseUrl()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_CLIENTBASEURL_OFFSET))(this);
		}

		::System::UInt32 get_QueryId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_QUERYID_OFFSET))(this);
		}

		::System::UInt32 get_TokenCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_RTCADMIN_QUERYJOINROOMTOKENCOMPLETECALLBACKINFOINTERNAL_GET_TOKENCOUNT_OFFSET))(this);
		}
	};
}
