#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/ValueType.h"

namespace Epic::OnlineServices { class ProductUserId; }
namespace System { class Object; }
namespace System { class String; }

#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_CLIENTDATAADDRESS_OFFSET UNITYSDK_OFFSET(0x246290)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_CLIENTDATA_OFFSET UNITYSDK_OFFSET(0x9AC510)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_DATACHUNK_OFFSET UNITYSDK_OFFSET(0x9AC7F0)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_FILENAME_OFFSET UNITYSDK_OFFSET(0x9AC690)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_ISLASTCHUNK_OFFSET UNITYSDK_OFFSET(0x9AC740)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_LOCALUSERID_OFFSET UNITYSDK_OFFSET(0x9AC620)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_TOTALFILESIZEBYTES_OFFSET UNITYSDK_OFFSET(0x2C1260)

namespace Epic::OnlineServices::PlayerDataStorage
{
	inline static constexpr unsigned int ReadFileDataCallbackInfoInternal_TypeDefinitionIndex = 35464;

	struct alignas(8) ReadFileDataCallbackInfoInternal
	{
		::System::IntPtr m_ClientData; // 0x10
		::System::IntPtr m_LocalUserId; // 0x18
		::System::IntPtr m_Filename; // 0x20
		::System::UInt32 m_TotalFileSizeBytes; // 0x28
		::System::Int32 m_IsLastChunk; // 0x2C
		::System::UInt32 m_DataChunkLengthBytes; // 0x30
		::System::IntPtr m_DataChunk; // 0x38

		::System::Object* get_ClientData()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_CLIENTDATA_OFFSET))(this);
		}

		::System::IntPtr get_ClientDataAddress()
		{
			return ((::System::IntPtr(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_CLIENTDATAADDRESS_OFFSET))(this);
		}

		::Epic::OnlineServices::ProductUserId* get_LocalUserId()
		{
			return ((::Epic::OnlineServices::ProductUserId*(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_LOCALUSERID_OFFSET))(this);
		}

		::System::String* get_Filename()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_FILENAME_OFFSET))(this);
		}

		::System::UInt32 get_TotalFileSizeBytes()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_TOTALFILESIZEBYTES_OFFSET))(this);
		}

		::System::Boolean get_IsLastChunk()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_ISLASTCHUNK_OFFSET))(this);
		}

		::Il2CppArray<::System::Byte>* get_DataChunk()
		{
			return ((::Il2CppArray<::System::Byte>*(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_READFILEDATACALLBACKINFOINTERNAL_GET_DATACHUNK_OFFSET))(this);
		}
	};
}
