#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/BattleAssetPreload_AssetPreloadGroup.h"
#include "unitysdk/RPG/GameCore/AttackDamageType.h"

namespace RPG::GameCore { class BattlePerformStageConfig; }
namespace RPG::GameCore { class PreloadItemList; }
namespace System { class String; }

#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_ADDBATTLEPERFORMPRELOAD_OFFSET UNITYSDK_OFFSET(0xC8E8700)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0xC8E92A0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERBATTLE_OFFSET UNITYSDK_OFFSET(0xC8E93A0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0xC8E9220)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERBATTLE_OFFSET UNITYSDK_OFFSET(0xC8E9320)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHBEFORELEAVEBATTLE_OFFSET UNITYSDK_OFFSET(0xC8E9410)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REMOVEBATTLEPERFORMPRELOAD_OFFSET UNITYSDK_OFFSET(0xC8E8DD0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__ADDPERFORMASSETS_OFFSET UNITYSDK_OFFSET(0xC8E7940)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__ADDPOSTUREEFFECTS_OFFSET UNITYSDK_OFFSET(0xC8E7750)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPLFORCOLLECTIONMODE_OFFSET UNITYSDK_OFFSET(0xC8E7450)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPL_OFFSET UNITYSDK_OFFSET(0xC8E71A0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__CTOR_OFFSET UNITYSDK_OFFSET(0xC8E9480)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__REFRESHPERFORMPRELOAD_OFFSET UNITYSDK_OFFSET(0xC8E84D0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__REFRESHPOSTUREEFFECTS_OFFSET UNITYSDK_OFFSET(0xC8E80C0)

namespace RPG::Client
{
	inline static constexpr unsigned int BattleAssetPreload_InBattleAssetPreloadGroup_TypeDefinitionIndex = 59796;

	class BattleAssetPreload_InBattleAssetPreloadGroup : public ::RPG::Client::BattleAssetPreload_AssetPreloadGroup
	{
	public:
		// static const ::System::String* POSTURE_EFFECT_TYPE; // 0x0
		// static const ::System::String* STAGE_PERFORM_TYPE; // 0x0
		// static const ::System::String* BATTLE_PERFORM_CHARACTER_TYPE; // 0x0
		::RPG::GameCore::AttackDamageType _LastPostureDamageType; // 0x68
		::System::UInt32 _LastPreloadPerformID; // 0x6C

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__CTOR_OFFSET))(this);
		}

		::System::Void _CollectResourceImpl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPL_OFFSET))(this);
		}

		::System::Void _CollectResourceImplForCollectionMode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPLFORCOLLECTIONMODE_OFFSET))(this);
		}

		::System::Void _RefreshPostureEffects()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__REFRESHPOSTUREEFFECTS_OFFSET))(this);
		}

		::System::Void _RefreshPerformPreload()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__REFRESHPERFORMPRELOAD_OFFSET))(this);
		}

		::System::Void _AddPostureEffects(::System::String* a1, ::RPG::GameCore::PreloadItemList* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::RPG::GameCore::PreloadItemList*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__ADDPOSTUREEFFECTS_OFFSET))(this, a1, a2);
		}

		::System::Void _AddPerformAssets(::System::UInt32 a1, ::RPG::GameCore::BattlePerformStageConfig* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::RPG::GameCore::BattlePerformStageConfig*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP__ADDPERFORMASSETS_OFFSET))(this, a1, a2);
		}

		::System::Void AddBattlePerformPreload(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_ADDBATTLEPERFORMPRELOAD_OFFSET))(this, a1);
		}

		::System::Void RemoveBattlePerformPreload(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REMOVEBATTLEPERFORMPRELOAD_OFFSET))(this, a1);
		}

		::System::Void RefreshBeforeEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshAfterEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshBeforeEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERBATTLE_OFFSET))(this);
		}

		::System::Void RefreshAfterEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERBATTLE_OFFSET))(this);
		}

		::System::Void RefreshBeforeLeaveBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_INBATTLEASSETPRELOADGROUP_REFRESHBEFORELEAVEBATTLE_OFFSET))(this);
		}
	};
}
