#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/ChimeraDuelBattlePageViewModel_GameViewModel_ExitModeType.h"
#include "unitysdk/RPG/Client/LittleGame/ChimeraDuel/ChimeraDuelLogLevel.h"
#include "unitysdk/System/Object.h"

#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_CURRENTLIFECOUNT_OFFSET UNITYSDK_OFFSET(0x93925E0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_CURRENTROUNDINDEX_OFFSET UNITYSDK_OFFSET(0x9392620)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_CURRENTWINCOUNT_OFFSET UNITYSDK_OFFSET(0x9392560)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_EXITMODE_OFFSET UNITYSDK_OFFSET(0x93926A0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_LOGLEVEL_OFFSET UNITYSDK_OFFSET(0x9392700)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_MAXROUNDNUM_OFFSET UNITYSDK_OFFSET(0x93926E0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_MAXWINCOUNT_OFFSET UNITYSDK_OFFSET(0x93925A0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDEARLYVICTORY_OFFSET UNITYSDK_OFFSET(0x93926C0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWACCELERATEBUTTON_OFFSET UNITYSDK_OFFSET(0x9392660)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWAUTOMODEBUTTON_OFFSET UNITYSDK_OFFSET(0x9392640)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWLIFECOUNT_OFFSET UNITYSDK_OFFSET(0x93925C0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWMASTERSKILL_OFFSET UNITYSDK_OFFSET(0x9392680)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWROUNDINDEX_OFFSET UNITYSDK_OFFSET(0x9392600)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWWINCOUNT_OFFSET UNITYSDK_OFFSET(0x9392540)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_TARGETWINCOUNT_OFFSET UNITYSDK_OFFSET(0x9392580)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_CURRENTLIFECOUNT_OFFSET UNITYSDK_OFFSET(0x93925F0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_CURRENTROUNDINDEX_OFFSET UNITYSDK_OFFSET(0x9392630)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_CURRENTWINCOUNT_OFFSET UNITYSDK_OFFSET(0x9392570)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_EXITMODE_OFFSET UNITYSDK_OFFSET(0x93926B0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_LOGLEVEL_OFFSET UNITYSDK_OFFSET(0x9392710)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_MAXROUNDNUM_OFFSET UNITYSDK_OFFSET(0x93926F0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_MAXWINCOUNT_OFFSET UNITYSDK_OFFSET(0x93925B0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDEARLYVICTORY_OFFSET UNITYSDK_OFFSET(0x93926D0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWACCELERATEBUTTON_OFFSET UNITYSDK_OFFSET(0x9392670)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWAUTOMODEBUTTON_OFFSET UNITYSDK_OFFSET(0x9392650)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWLIFECOUNT_OFFSET UNITYSDK_OFFSET(0x93925D0)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWMASTERSKILL_OFFSET UNITYSDK_OFFSET(0x9392690)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWROUNDINDEX_OFFSET UNITYSDK_OFFSET(0x9392610)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWWINCOUNT_OFFSET UNITYSDK_OFFSET(0x9392550)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_TARGETWINCOUNT_OFFSET UNITYSDK_OFFSET(0x9392590)
#define RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0x9390250)

namespace RPG::Client
{
	inline static constexpr unsigned int ChimeraDuelBattlePageViewModel_GameViewModel_TypeDefinitionIndex = 51467;

	class ChimeraDuelBattlePageViewModel_GameViewModel : public ::System::Object
	{
	public:
		::System::Int32 _TargetWinCount_k__BackingField; // 0x10
		::System::Int32 _MaxWinCount_k__BackingField; // 0x14
		::System::UInt32 _MaxRoundNum_k__BackingField; // 0x18
		::System::Boolean _ShouldShowMasterSkill_k__BackingField; // 0x1C
		::System::Boolean _ShouldShowAutoModeButton_k__BackingField; // 0x1D
		::System::Boolean _ShouldShowRoundIndex_k__BackingField; // 0x1E
		::RPG::Client::LittleGame::ChimeraDuel::ChimeraDuelLogLevel _LogLevel_k__BackingField; // 0x20
		::System::Boolean _ShouldShowAccelerateButton_k__BackingField; // 0x24
		::System::Boolean _ShouldShowWinCount_k__BackingField; // 0x25
		::System::Boolean _ShouldShowLifeCount_k__BackingField; // 0x26
		::System::Boolean _ShouldEarlyVictory_k__BackingField; // 0x27
		::RPG::Client::ChimeraDuelBattlePageViewModel_GameViewModel_ExitModeType _ExitMode_k__BackingField; // 0x28
		::System::Int32 _CurrentLifeCount_k__BackingField; // 0x2C
		::System::Int32 _CurrentRoundIndex_k__BackingField; // 0x30
		::System::Int32 _CurrentWinCount_k__BackingField; // 0x34

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL__CTOR_OFFSET))(this);
		}

		::System::Boolean get_ShouldShowWinCount()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWWINCOUNT_OFFSET))(this);
		}

		::System::Void set_ShouldShowWinCount(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWWINCOUNT_OFFSET))(this, value);
		}

		::System::Int32 get_CurrentWinCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_CURRENTWINCOUNT_OFFSET))(this);
		}

		::System::Void set_CurrentWinCount(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_CURRENTWINCOUNT_OFFSET))(this, value);
		}

		::System::Int32 get_TargetWinCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_TARGETWINCOUNT_OFFSET))(this);
		}

		::System::Void set_TargetWinCount(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_TARGETWINCOUNT_OFFSET))(this, value);
		}

		::System::Int32 get_MaxWinCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_MAXWINCOUNT_OFFSET))(this);
		}

		::System::Void set_MaxWinCount(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_MAXWINCOUNT_OFFSET))(this, value);
		}

		::System::Boolean get_ShouldShowLifeCount()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWLIFECOUNT_OFFSET))(this);
		}

		::System::Void set_ShouldShowLifeCount(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWLIFECOUNT_OFFSET))(this, value);
		}

		::System::Int32 get_CurrentLifeCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_CURRENTLIFECOUNT_OFFSET))(this);
		}

		::System::Void set_CurrentLifeCount(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_CURRENTLIFECOUNT_OFFSET))(this, value);
		}

		::System::Boolean get_ShouldShowRoundIndex()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWROUNDINDEX_OFFSET))(this);
		}

		::System::Void set_ShouldShowRoundIndex(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWROUNDINDEX_OFFSET))(this, value);
		}

		::System::Int32 get_CurrentRoundIndex()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_CURRENTROUNDINDEX_OFFSET))(this);
		}

		::System::Void set_CurrentRoundIndex(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_CURRENTROUNDINDEX_OFFSET))(this, value);
		}

		::System::Boolean get_ShouldShowAutoModeButton()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWAUTOMODEBUTTON_OFFSET))(this);
		}

		::System::Void set_ShouldShowAutoModeButton(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWAUTOMODEBUTTON_OFFSET))(this, value);
		}

		::System::Boolean get_ShouldShowAccelerateButton()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWACCELERATEBUTTON_OFFSET))(this);
		}

		::System::Void set_ShouldShowAccelerateButton(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWACCELERATEBUTTON_OFFSET))(this, value);
		}

		::System::Boolean get_ShouldShowMasterSkill()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDSHOWMASTERSKILL_OFFSET))(this);
		}

		::System::Void set_ShouldShowMasterSkill(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDSHOWMASTERSKILL_OFFSET))(this, value);
		}

		::RPG::Client::ChimeraDuelBattlePageViewModel_GameViewModel_ExitModeType get_ExitMode()
		{
			return ((::RPG::Client::ChimeraDuelBattlePageViewModel_GameViewModel_ExitModeType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_EXITMODE_OFFSET))(this);
		}

		::System::Void set_ExitMode(::RPG::Client::ChimeraDuelBattlePageViewModel_GameViewModel_ExitModeType value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChimeraDuelBattlePageViewModel_GameViewModel_ExitModeType))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_EXITMODE_OFFSET))(this, value);
		}

		::System::Boolean get_ShouldEarlyVictory()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_SHOULDEARLYVICTORY_OFFSET))(this);
		}

		::System::Void set_ShouldEarlyVictory(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_SHOULDEARLYVICTORY_OFFSET))(this, value);
		}

		::System::UInt32 get_MaxRoundNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_MAXROUNDNUM_OFFSET))(this);
		}

		::System::Void set_MaxRoundNum(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_MAXROUNDNUM_OFFSET))(this, value);
		}

		::RPG::Client::LittleGame::ChimeraDuel::ChimeraDuelLogLevel get_LogLevel()
		{
			return ((::RPG::Client::LittleGame::ChimeraDuel::ChimeraDuelLogLevel(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_GET_LOGLEVEL_OFFSET))(this);
		}

		::System::Void set_LogLevel(::RPG::Client::LittleGame::ChimeraDuel::ChimeraDuelLogLevel value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::LittleGame::ChimeraDuel::ChimeraDuelLogLevel))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELBATTLEPAGEVIEWMODEL_GAMEVIEWMODEL_SET_LOGLEVEL_OFFSET))(this, value);
		}
	};
}
