#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Nullable_1.h"
#include "unitysdk/System/Object.h"

class Class_1_02098A44CBBFEEE1;
class Class_1_21C7581DFE99F091_21;
namespace RPG::Client { class ChimeraDuelChimeraData; }
namespace RPG::Client { class ChimeraDuelGameSessionItem; }
namespace RPG::Client { class IChimeraDuelSkillData; }

#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CANBEUPGRADEDBY_OFFSET UNITYSDK_OFFSET(0xB68ABF0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CREATEFAKE_OFFSET UNITYSDK_OFFSET(0xB68A630)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CREATE_1_OFFSET UNITYSDK_OFFSET(0xB68A310)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CREATE_OFFSET UNITYSDK_OFFSET(0xB68A1B0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTATTACK_OFFSET UNITYSDK_OFFSET(0xB68AE30)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTEXPOFCURRENTLEVEL_OFFSET UNITYSDK_OFFSET(0xB68AB60)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTHEALTH_OFFSET UNITYSDK_OFFSET(0xB68B110)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTLEVEL_OFFSET UNITYSDK_OFFSET(0xB68A7B0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETMAXEXPOFCURRENTLEVEL_OFFSET UNITYSDK_OFFSET(0xB68A9E0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETMAXEXPOFPREVIOUSLEVEL_OFFSET UNITYSDK_OFFSET(0xB68AAA0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETSELLPRICE_OFFSET UNITYSDK_OFFSET(0xB68B2E0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_CHIMERADATA_OFFSET UNITYSDK_OFFSET(0xB689F90)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_CHIMERAID_OFFSET UNITYSDK_OFFSET(0xB689F70)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_EQUIPMENT_OFFSET UNITYSDK_OFFSET(0xB68A190)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_GAINEDEXP_OFFSET UNITYSDK_OFFSET(0xB68A0A0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_UNIQUEID_OFFSET UNITYSDK_OFFSET(0xB689F60)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_ISMAXLEVEL_OFFSET UNITYSDK_OFFSET(0xB68A950)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_SET_CHIMERAID_OFFSET UNITYSDK_OFFSET(0xB689F80)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_SET_EQUIPMENT_OFFSET UNITYSDK_OFFSET(0xB68A1A0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_SYNC_OFFSET UNITYSDK_OFFSET(0xB68B680)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETBATTLESKILLDATA_OFFSET UNITYSDK_OFFSET(0xB68B5C0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETCOREFLAMECOUNT_OFFSET UNITYSDK_OFFSET(0xB68B370)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETSHOPSKILLDATA_OFFSET UNITYSDK_OFFSET(0xB68B500)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETSKILLDATAFORDISPLAY_OFFSET UNITYSDK_OFFSET(0xB68B410)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_WOULDLEVELUPWITHEXP_OFFSET UNITYSDK_OFFSET(0xB68ACE0)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__CTOR_1_OFFSET UNITYSDK_OFFSET(0xB68A730)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__CTOR_OFFSET UNITYSDK_OFFSET(0xB68A290)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__GETCOREFLAMECOUNT_OFFSET UNITYSDK_OFFSET(0xB68A770)
#define RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__GETGAINEDEXPFORDISPLAY_OFFSET UNITYSDK_OFFSET(0xB68A0B0)

namespace RPG::Client
{
	inline static constexpr unsigned int ChimeraDuelGameSessionChimera_TypeDefinitionIndex = 59255;

	class ChimeraDuelGameSessionChimera : public ::System::Object
	{
	public:
		::RPG::Client::ChimeraDuelGameSessionItem* _Equipment_k__BackingField; // 0x10
		::System::UInt32 _UniqueID_k__BackingField; // 0x18
		::System::Int32 _DeltaAttack; // 0x1C
		::System::UInt32 _SpecialParam; // 0x20
		::System::Int32 _DeltaHealth; // 0x24
		::System::Int32 _GainedExp; // 0x28
		::System::UInt32 _ChimeraID_k__BackingField; // 0x2C

		::System::Void _ctor(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__CTOR_OFFSET))(this, a1, a2);
		}

		::System::Void _ctor_1(::RPG::Client::ChimeraDuelGameSessionChimera* a1, ::System::Nullable_1<::System::UInt32> a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChimeraDuelGameSessionChimera*, ::System::Nullable_1<::System::UInt32>))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__CTOR_1_OFFSET))(this, a1, a2);
		}

		::System::UInt32 get_UniqueID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_UNIQUEID_OFFSET))(this);
		}

		::System::UInt32 get_ChimeraID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_CHIMERAID_OFFSET))(this);
		}

		::System::Void set_ChimeraID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_SET_CHIMERAID_OFFSET))(this, a1);
		}

		::RPG::Client::ChimeraDuelChimeraData* get_ChimeraData()
		{
			return ((::RPG::Client::ChimeraDuelChimeraData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_CHIMERADATA_OFFSET))(this);
		}

		::System::Int32 get_GainedExp()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_GAINEDEXP_OFFSET))(this);
		}

		::RPG::Client::ChimeraDuelGameSessionItem* get_Equipment()
		{
			return ((::RPG::Client::ChimeraDuelGameSessionItem*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GET_EQUIPMENT_OFFSET))(this);
		}

		::System::Void set_Equipment(::RPG::Client::ChimeraDuelGameSessionItem* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChimeraDuelGameSessionItem*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_SET_EQUIPMENT_OFFSET))(this, a1);
		}

		static ::RPG::Client::ChimeraDuelGameSessionChimera* Create(::Class_1_02098A44CBBFEEE1* a1)
		{
			return ((::RPG::Client::ChimeraDuelGameSessionChimera*(*)(::Class_1_02098A44CBBFEEE1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CREATE_OFFSET))(a1);
		}

		static ::RPG::Client::ChimeraDuelGameSessionChimera* Create_1(::Class_1_21C7581DFE99F091_21* a1)
		{
			return ((::RPG::Client::ChimeraDuelGameSessionChimera*(*)(::Class_1_21C7581DFE99F091_21*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CREATE_1_OFFSET))(a1);
		}

		static ::RPG::Client::ChimeraDuelGameSessionChimera* CreateFake(::System::UInt32 a1, ::System::UInt32 a2, ::System::Int32 a3, ::System::Int32 a4, ::System::Int32 a5, ::System::UInt32 a6, ::System::UInt32 a7)
		{
			return ((::RPG::Client::ChimeraDuelGameSessionChimera*(*)(::System::UInt32, ::System::UInt32, ::System::Int32, ::System::Int32, ::System::Int32, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CREATEFAKE_OFFSET))(a1, a2, a3, a4, a5, a6, a7);
		}

		::System::Int32 _GetGainedExpForDisplay()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__GETGAINEDEXPFORDISPLAY_OFFSET))(this);
		}

		::System::Int32 GetCurrentLevel()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTLEVEL_OFFSET))(this);
		}

		::System::Boolean IsMaxLevel()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_ISMAXLEVEL_OFFSET))(this);
		}

		::System::Int32 GetMaxExpOfCurrentLevel()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETMAXEXPOFCURRENTLEVEL_OFFSET))(this);
		}

		::System::Int32 GetMaxExpOfPreviousLevel()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETMAXEXPOFPREVIOUSLEVEL_OFFSET))(this);
		}

		::System::Int32 GetCurrentExpOfCurrentLevel()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTEXPOFCURRENTLEVEL_OFFSET))(this);
		}

		::System::Boolean CanBeUpgradedBy(::RPG::Client::ChimeraDuelGameSessionChimera* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::ChimeraDuelGameSessionChimera*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_CANBEUPGRADEDBY_OFFSET))(this, a1);
		}

		::System::Boolean WouldLevelUpWithExp(::System::Int32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_WOULDLEVELUPWITHEXP_OFFSET))(this, a1);
		}

		::System::Int32 GetCurrentAttack()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTATTACK_OFFSET))(this);
		}

		::System::Int32 GetCurrentHealth()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETCURRENTHEALTH_OFFSET))(this);
		}

		::System::Int32 GetSellPrice()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_GETSELLPRICE_OFFSET))(this);
		}

		::System::Int32 _GetCoreflameCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA__GETCOREFLAMECOUNT_OFFSET))(this);
		}

		::System::Nullable_1<::System::Int32> TryGetCoreflameCount()
		{
			return ((::System::Nullable_1<::System::Int32>(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETCOREFLAMECOUNT_OFFSET))(this);
		}

		::RPG::Client::IChimeraDuelSkillData* TryGetSkillDataForDisplay()
		{
			return ((::RPG::Client::IChimeraDuelSkillData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETSKILLDATAFORDISPLAY_OFFSET))(this);
		}

		::RPG::Client::IChimeraDuelSkillData* TryGetShopSkillData()
		{
			return ((::RPG::Client::IChimeraDuelSkillData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETSHOPSKILLDATA_OFFSET))(this);
		}

		::RPG::Client::IChimeraDuelSkillData* TryGetBattleSkillData()
		{
			return ((::RPG::Client::IChimeraDuelSkillData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_TRYGETBATTLESKILLDATA_OFFSET))(this);
		}

		::System::Void Sync(::Class_1_02098A44CBBFEEE1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_02098A44CBBFEEE1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHIMERADUELGAMESESSIONCHIMERA_SYNC_OFFSET))(this, a1);
		}
	};
}
