#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

class Class_1_D17272E82AE804C2_507;

#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_FINISH_OFFSET UNITYSDK_OFFSET(0xD2DAAE0)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GETACTIONID_OFFSET UNITYSDK_OFFSET(0xD2DAB60)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GETISHANDLED_OFFSET UNITYSDK_OFFSET(0xD2DABA0)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GET_ACTIONID_OFFSET UNITYSDK_OFFSET(0xD2DAC00)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GET_ISHANDLED_OFFSET UNITYSDK_OFFSET(0xD2DABE0)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_SET_ACTIONID_OFFSET UNITYSDK_OFFSET(0xD2DAC10)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_SET_ISHANDLED_OFFSET UNITYSDK_OFFSET(0xD2DABF0)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_START_OFFSET UNITYSDK_OFFSET(0xD2DAA70)
#define RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION__CTOR_OFFSET UNITYSDK_OFFSET(0xD2DAC20)

namespace RPG::Client
{
	inline static constexpr unsigned int GridFightPendingSelectableBaseAction_TypeDefinitionIndex = 64671;

	class GridFightPendingSelectableBaseAction : public ::System::Object
	{
	public:
		::System::UInt32 _ActionID_k__BackingField; // 0x10
		::System::Boolean _IsHandled_k__BackingField; // 0x14

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION__CTOR_OFFSET))(this);
		}

		::System::Void Start()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_START_OFFSET))(this);
		}

		::System::Void Finish()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_FINISH_OFFSET))(this);
		}

		::System::UInt32 GetActionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GETACTIONID_OFFSET))(this);
		}

		::System::Boolean GetIsHandled()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GETISHANDLED_OFFSET))(this);
		}

		::System::Boolean get_IsHandled()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GET_ISHANDLED_OFFSET))(this);
		}

		::System::Void set_IsHandled(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_SET_ISHANDLED_OFFSET))(this, a1);
		}

		::System::UInt32 get_ActionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_GET_ACTIONID_OFFSET))(this);
		}

		::System::Void set_ActionID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTPENDINGSELECTABLEBASEACTION_SET_ACTIONID_OFFSET))(this, a1);
		}
	};
}
