#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_5AA38DC400740F29.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

namespace System { class String; }

#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ISREACHLIMIT_OFFSET UNITYSDK_OFFSET(0xA391F40)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ITEMICONPATH_OFFSET UNITYSDK_OFFSET(0xA391F90)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ITEMID_OFFSET UNITYSDK_OFFSET(0xA391F60)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ITEMNAME_OFFSET UNITYSDK_OFFSET(0xA391F70)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_VALUEEXTRA_OFFSET UNITYSDK_OFFSET(0xA391F20)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_VALUE_OFFSET UNITYSDK_OFFSET(0xA391F00)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SETVIRTUALITEM_OFFSET UNITYSDK_OFFSET(0xA391D10)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_ISREACHLIMIT_OFFSET UNITYSDK_OFFSET(0xA391F50)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_ITEMICONPATH_OFFSET UNITYSDK_OFFSET(0xA391FA0)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_ITEMNAME_OFFSET UNITYSDK_OFFSET(0xA391F80)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_VALUEEXTRA_OFFSET UNITYSDK_OFFSET(0xA391F30)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_VALUE_OFFSET UNITYSDK_OFFSET(0xA391F10)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM__CTOR_OFFSET UNITYSDK_OFFSET(0xA391D00)
#define RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM__FILLFROMEXCEL_OFFSET UNITYSDK_OFFSET(0xA391D60)

namespace RPG::Client
{
	inline static constexpr unsigned int RogueTournGameScoreSettleResultVirtualItem_TypeDefinitionIndex = 55345;

	class RogueTournGameScoreSettleResultVirtualItem : public ::System::Object
	{
	public:
		::System::String* _ItemIconPath_k__BackingField; // 0x10
		::System::UInt32 _ItemID; // 0x18
		::System::UInt32 _Value_k__BackingField; // 0x1C
		::System::UInt32 _ValueExtra_k__BackingField; // 0x20
		::System::Boolean _IsReachLimit_k__BackingField; // 0x24
		::RPG::Client::TextID _ItemName_k__BackingField; // 0x28

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM__CTOR_OFFSET))(this);
		}

		::System::Void SetVirtualItem(::Enum_3_5AA38DC400740F29 virtualItemType)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_5AA38DC400740F29))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SETVIRTUALITEM_OFFSET))(this, virtualItemType);
		}

		::System::Void _FillFromExcel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM__FILLFROMEXCEL_OFFSET))(this);
		}

		::System::UInt32 get_Value()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_VALUE_OFFSET))(this);
		}

		::System::Void set_Value(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_VALUE_OFFSET))(this, value);
		}

		::System::UInt32 get_ValueExtra()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_VALUEEXTRA_OFFSET))(this);
		}

		::System::Void set_ValueExtra(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_VALUEEXTRA_OFFSET))(this, value);
		}

		::System::Boolean get_IsReachLimit()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ISREACHLIMIT_OFFSET))(this);
		}

		::System::Void set_IsReachLimit(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_ISREACHLIMIT_OFFSET))(this, value);
		}

		::System::UInt32 get_ItemID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ITEMID_OFFSET))(this);
		}

		::RPG::Client::TextID get_ItemName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ITEMNAME_OFFSET))(this);
		}

		::System::Void set_ItemName(::RPG::Client::TextID value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_ITEMNAME_OFFSET))(this, value);
		}

		::System::String* get_ItemIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_GET_ITEMICONPATH_OFFSET))(this);
		}

		::System::Void set_ItemIconPath(::System::String* value)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNGAMESCORESETTLERESULTVIRTUALITEM_SET_ITEMICONPATH_OFFSET))(this, value);
		}
	};
}
