#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/RogueResidentActivityPanelData.h"

class Class_1_355D5C2B1D92981B;
class Class_1_D4B4346A5EB96462;
namespace RPG::GameCore { class IntroDataRow; }
namespace RPG::GameCore { class RogueActivityResidentConfigRow; }
namespace System { class String; }

#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_CREATEBYROW_OFFSET UNITYSDK_OFFSET(0xB087CF0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_GET_LOCKEDREASON_OFFSET UNITYSDK_OFFSET(0xB088D60)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISHIDEALLREDDOT_OFFSET UNITYSDK_OFFSET(0xB088D20)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISSHOWNEWREDDOT_OFFSET UNITYSDK_OFFSET(0xB088CE0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISSHOWNOPASSNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0xB088CA0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0xB0882B0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xB087CD0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISDICEHANDBOOKREWARDAVAILABLE_OFFSET UNITYSDK_OFFSET(0xB088600)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISMAINSTORYREWARDAVAILABLE_OFFSET UNITYSDK_OFFSET(0xB088AF0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISQUESTREWARDAVAILABLE_OFFSET UNITYSDK_OFFSET(0xB088840)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISSTORYUNLOCKREWARDAVAILABLE_OFFSET UNITYSDK_OFFSET(0xB0888C0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISSUBSTORYREWARDAVAILABLE_OFFSET UNITYSDK_OFFSET(0xB088940)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__REFRESHGUIDESTATUS_OFFSET UNITYSDK_OFFSET(0xB0885A0)
#define RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA___IFIXBASEPROXY_GET_LOCKEDREASON_OFFSET UNITYSDK_OFFSET(0xB088E30)

namespace RPG::Client
{
	inline static constexpr unsigned int RogueNousResidentActivityPanelData_TypeDefinitionIndex = 56981;

	class RogueNousResidentActivityPanelData : public ::RPG::Client::RogueResidentActivityPanelData
	{
	public:
		::System::Boolean _IsGuideOneFinished; // 0xB0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::RogueNousResidentActivityPanelData* CreateByRow(::RPG::GameCore::RogueActivityResidentConfigRow* row, ::RPG::GameCore::IntroDataRow* introRow, ::Class_1_D4B4346A5EB96462* scheduleProxyFactory, ::Class_1_355D5C2B1D92981B* rewardCountProxyFactory)
		{
			return ((::RPG::Client::RogueNousResidentActivityPanelData*(*)(::RPG::GameCore::RogueActivityResidentConfigRow*, ::RPG::GameCore::IntroDataRow*, ::Class_1_D4B4346A5EB96462*, ::Class_1_355D5C2B1D92981B*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_CREATEBYROW_OFFSET))(row, introRow, scheduleProxyFactory, rewardCountProxyFactory);
		}

		::System::Boolean IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowNoPassNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISSHOWNOPASSNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowNewRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISSHOWNEWREDDOT_OFFSET))(this);
		}

		::System::Boolean IsHideAllRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_ISHIDEALLREDDOT_OFFSET))(this);
		}

		::System::Void _RefreshGuideStatus()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__REFRESHGUIDESTATUS_OFFSET))(this);
		}

		::System::Boolean _IsDiceHandbookRewardAvailable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISDICEHANDBOOKREWARDAVAILABLE_OFFSET))(this);
		}

		::System::Boolean _IsQuestRewardAvailable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISQUESTREWARDAVAILABLE_OFFSET))(this);
		}

		::System::Boolean _IsStoryUnlockRewardAvailable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISSTORYUNLOCKREWARDAVAILABLE_OFFSET))(this);
		}

		::System::Boolean _IsSubStoryRewardAvailable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISSUBSTORYREWARDAVAILABLE_OFFSET))(this);
		}

		::System::Boolean _IsMainStoryRewardAvailable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA__ISMAINSTORYREWARDAVAILABLE_OFFSET))(this);
		}

		::System::String* get_LockedReason()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA_GET_LOCKEDREASON_OFFSET))(this);
		}

		::System::String* __iFixBaseProxy_get_LockedReason()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUENOUSRESIDENTACTIVITYPANELDATA___IFIXBASEPROXY_GET_LOCKEDREASON_OFFSET))(this);
		}
	};
}
