#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TABehaviorBase.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_0_16E4307DCC419505_372;
namespace RPG::Client { class StageHarmonyVelocitySignalMonoPlugin; }
namespace System { class String; }
namespace UnityEngine { class GameObject; }

#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_AUTOACTIVE_OFFSET UNITYSDK_OFFSET(0x17B53B40)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_CHANNELNAME_OFFSET UNITYSDK_OFFSET(0x17B53BA0)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_GET_OWNERFMSYSTEM_OFFSET UNITYSDK_OFFSET(0x17B53B80)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET UNITYSDK_OFFSET(0x17B53A10)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_2C9E083DC9C549F9_OFFSET UNITYSDK_OFFSET(0x17B53FE0)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_391A84BCD9F51317_OFFSET UNITYSDK_OFFSET(0x17B538A0)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET UNITYSDK_OFFSET(0x17B536C0)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET UNITYSDK_OFFSET(0x17B53720)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET UNITYSDK_OFFSET(0x17B53780)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET UNITYSDK_OFFSET(0x17B537E0)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_5_OFFSET UNITYSDK_OFFSET(0x17B53840)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET UNITYSDK_OFFSET(0x17B53660)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_68805403250CC013_OFFSET UNITYSDK_OFFSET(0x17B53A50)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_B06F516E4459C742_OFFSET UNITYSDK_OFFSET(0x17B538E0)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_ONCHANNELACTIVE_OFFSET UNITYSDK_OFFSET(0x17B53C20)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_ONCHANNELDEACTIVE_OFFSET UNITYSDK_OFFSET(0x17B53C60)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_ONCHANNELUPDATE_OFFSET UNITYSDK_OFFSET(0x17B53CA0)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_SAMPLE_OFFSET UNITYSDK_OFFSET(0x17B53D00)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_SET_OWNERFMSYSTEM_OFFSET UNITYSDK_OFFSET(0x17B53B90)
#define RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR__CTOR_OFFSET UNITYSDK_OFFSET(0x17B54060)

namespace RPG::Client
{
	inline static constexpr unsigned int StageHarmonyVelocitySignalBehavior_TypeDefinitionIndex = 67804;

	class StageHarmonyVelocitySignalBehavior : public ::RPG::Client::TABehaviorBase
	{
	public:
		::Class_0_16E4307DCC419505_372* _OwnerFMSystem_k__BackingField; // 0x38
		::UnityEngine::Vector3 _Velocity; // 0x40
		::UnityEngine::Vector3 _LastLocalPosition; // 0x4C

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR__CTOR_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_5()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_4343F372F34C05BF_5_OFFSET))(this);
		}

		::System::Boolean Method_3_391A84BCD9F51317()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_391A84BCD9F51317_OFFSET))(this);
		}

		::System::Void Method_3_B06F516E4459C742()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_B06F516E4459C742_OFFSET))(this);
		}

		::System::Void Method_3_68805403250CC013()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_68805403250CC013_OFFSET))(this);
		}

		::System::Boolean AutoActive()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_AUTOACTIVE_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_372* get_OwnerFMSystem()
		{
			return ((::Class_0_16E4307DCC419505_372*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_GET_OWNERFMSYSTEM_OFFSET))(this);
		}

		::System::Void set_OwnerFMSystem(::Class_0_16E4307DCC419505_372* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_372*))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_SET_OWNERFMSYSTEM_OFFSET))(this, a1);
		}

		::System::String* ChannelName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_CHANNELNAME_OFFSET))(this);
		}

		::System::Void OnChannelActive()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_ONCHANNELACTIVE_OFFSET))(this);
		}

		::System::Void OnChannelDeactive()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_ONCHANNELDEACTIVE_OFFSET))(this);
		}

		::System::Void OnChannelUpdate(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_ONCHANNELUPDATE_OFFSET))(this, a1);
		}

		::System::Single Sample(::System::Single a1)
		{
			return ((::System::Single(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_SAMPLE_OFFSET))(this, a1);
		}

		::UnityEngine::GameObject* Method_3_2C9E083DC9C549F9()
		{
			return ((::UnityEngine::GameObject*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_METHOD_3_2C9E083DC9C549F9_OFFSET))(this);
		}

		::RPG::Client::StageHarmonyVelocitySignalMonoPlugin* get__OwnerMonoPlugin()
		{
			return ((::RPG::Client::StageHarmonyVelocitySignalMonoPlugin*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_STAGEHARMONYVELOCITYSIGNALBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET))(this);
		}
	};
}
