#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/UnityEngine/Bounds.h"
#include "unitysdk/UnityEngine/MonoBehaviour.h"

namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class GameObject; }

#define NAPSTREAMING_NAPSTREAMINGREGION_CALCLOADBOUNDS_OFFSET UNITYSDK_OFFSET(0xFFDFC90)
#define NAPSTREAMING_NAPSTREAMINGREGION_ONENABLE_OFFSET UNITYSDK_OFFSET(0xFFDFA80)
#define NAPSTREAMING_NAPSTREAMINGREGION__CTOR_OFFSET UNITYSDK_OFFSET(0xFFE00D0)

namespace NapStreaming
{
	inline static constexpr unsigned int NapStreamingRegion_TypeDefinitionIndex = 42650;

	class NapStreamingRegion : public ::UnityEngine::MonoBehaviour
	{
	public:
		::System::Single unloadPercent; // 0x18
		::UnityEngine::GameObject* loadAreas; // 0x20
		::System::Collections::Generic::List_1<::UnityEngine::GameObject*>* childs; // 0x28
		::System::Boolean autoGenerated; // 0x30

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + NAPSTREAMING_NAPSTREAMINGREGION__CTOR_OFFSET))(this);
		}

		::System::Void OnEnable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + NAPSTREAMING_NAPSTREAMINGREGION_ONENABLE_OFFSET))(this);
		}

		::UnityEngine::Bounds CalcLoadBounds()
		{
			return ((::UnityEngine::Bounds(*)(::PVOID))((::PBYTE)hIl2Cpp + NAPSTREAMING_NAPSTREAMINGREGION_CALCLOADBOUNDS_OFFSET))(this);
		}
	};
}
