#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/ChessStateMachine/TextureSheetVEBase.h"

class Class_1_43BD383C98B4C0C5_20;
class Class_2_9E53935807C1819B;

#define MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION_FORCESTOP_OFFSET UNITYSDK_OFFSET(0xECF8A60)
#define MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION_RUN_OFFSET UNITYSDK_OFFSET(0xECF8030)
#define MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION_TEXTURECALLBACK_OFFSET UNITYSDK_OFFSET(0xECF8980)
#define MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION__CTOR_OFFSET UNITYSDK_OFFSET(0xECF8C50)
#define MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION___BASE_FORCESTOP_OFFSET UNITYSDK_OFFSET(0xECF8C60)
#define MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION___BASE_RUN_OFFSET UNITYSDK_OFFSET(0xECF8CF0)

namespace MoleMole::ChessStateMachine
{
	inline static constexpr unsigned int ShowNoneInteractAnimAction_TypeDefinitionIndex = 51828;

	class ShowNoneInteractAnimAction : public ::MoleMole::ChessStateMachine::TextureSheetVEBase
	{
	public:
		::Class_2_9E53935807C1819B* _actionContext; // 0x28

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION__CTOR_OFFSET))(this);
		}

		::System::Void Run(::Class_1_43BD383C98B4C0C5_20* context)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_20*))((::PBYTE)hIl2Cpp + MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION_RUN_OFFSET))(this, context);
		}

		::System::Void TextureCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION_TEXTURECALLBACK_OFFSET))(this);
		}

		::System::Void ForceStop()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION_FORCESTOP_OFFSET))(this);
		}

		::System::Void __base_ForceStop()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION___BASE_FORCESTOP_OFFSET))(this);
		}

		::System::Void __base_Run(::Class_1_43BD383C98B4C0C5_20* P0)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_20*))((::PBYTE)hIl2Cpp + MOLEMOLE_CHESSSTATEMACHINE_SHOWNONEINTERACTANIMACTION___BASE_RUN_OFFSET))(this, P0);
		}
	};
}
