#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Mono/Security/X509/X509Extension.h"

namespace Mono::Security { class ASN1; }
namespace System { class String; }

#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_DECODE_OFFSET UNITYSDK_OFFSET(0x1C4B0A10)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_ENCODE_OFFSET UNITYSDK_OFFSET(0x1C4B0B20)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_GET_IDENTIFIER_OFFSET UNITYSDK_OFFSET(0x1C4B0DB0)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_GET_NAME_OFFSET UNITYSDK_OFFSET(0x1C4B0D70)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_SET_IDENTIFIER_OFFSET UNITYSDK_OFFSET(0x1C4B0EB0)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_TOSTRING_OFFSET UNITYSDK_OFFSET(0x1C4B0EC0)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION__CTOR_1_OFFSET UNITYSDK_OFFSET(0x1C4B09F0)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION__CTOR_2_OFFSET UNITYSDK_OFFSET(0x1C4B0A00)
#define MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION__CTOR_OFFSET UNITYSDK_OFFSET(0x1C4B09B0)

namespace Mono::Security::X509::Extensions
{
	inline static constexpr unsigned int AuthorityKeyIdentifierExtension_TypeDefinitionIndex = 2328;

	class AuthorityKeyIdentifierExtension : public ::Mono::Security::X509::X509Extension
	{
	public:
		::Il2CppArray<::System::Byte>* aki; // 0x28

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION__CTOR_OFFSET))(this);
		}

		::System::Void _ctor_1(::Mono::Security::ASN1* asn1)
		{
			return ((::System::Void(*)(::PVOID, ::Mono::Security::ASN1*))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION__CTOR_1_OFFSET))(this, asn1);
		}

		::System::Void _ctor_2(::Mono::Security::X509::X509Extension* extension)
		{
			return ((::System::Void(*)(::PVOID, ::Mono::Security::X509::X509Extension*))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION__CTOR_2_OFFSET))(this, extension);
		}

		::System::Void Decode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_DECODE_OFFSET))(this);
		}

		::System::Void Encode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_ENCODE_OFFSET))(this);
		}

		::System::String* get_Name()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_GET_NAME_OFFSET))(this);
		}

		::Il2CppArray<::System::Byte>* get_Identifier()
		{
			return ((::Il2CppArray<::System::Byte>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_GET_IDENTIFIER_OFFSET))(this);
		}

		::System::Void set_Identifier(::Il2CppArray<::System::Byte>* value)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::System::Byte>*))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_SET_IDENTIFIER_OFFSET))(this, value);
		}

		::System::String* ToString()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MONO_SECURITY_X509_EXTENSIONS_AUTHORITYKEYIDENTIFIEREXTENSION_TOSTRING_OFFSET))(this);
		}
	};
}
