#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/EffectSimulate/AvatarMatChange/ExportContextBase.h"

namespace System { class String; }

#define MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_391A84BCD9F51317_OFFSET UNITYSDK_OFFSET(0x142668C0)
#define MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_88B60F3B95FAA4F1_OFFSET UNITYSDK_OFFSET(0x142667F0)
#define MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_8A082AE0230435DC_OFFSET UNITYSDK_OFFSET(0x14266680)
#define MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_B345A53823FD29B2_OFFSET UNITYSDK_OFFSET(0x142664D0)
#define MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT__CTOR_OFFSET UNITYSDK_OFFSET(0x14266860)

namespace MoleMole::EffectSimulate::AvatarMatChange
{
	inline static constexpr unsigned int ExportContextMainPlot_TypeDefinitionIndex = 48014;

	class ExportContextMainPlot : public ::MoleMole::EffectSimulate::AvatarMatChange::ExportContextBase
	{
	public:
		::System::String* mainPlotName; // 0x18
		::System::Boolean skillPatternNameUseCtx; // 0x20
		::System::String* markStr; // 0x28
		::System::String* moduleType; // 0x30
		::System::Int32 markID; // 0x38

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT__CTOR_OFFSET))(this);
		}

		::System::String* Method_2_B345A53823FD29B2()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_B345A53823FD29B2_OFFSET))(this);
		}

		::System::String* Method_2_8A082AE0230435DC()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_8A082AE0230435DC_OFFSET))(this);
		}

		::System::String* Method_2_88B60F3B95FAA4F1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_88B60F3B95FAA4F1_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_AVATARMATCHANGE_EXPORTCONTEXTMAINPLOT_METHOD_2_391A84BCD9F51317_OFFSET))(this);
		}
	};
}
