#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_ABILITYCOOLDOWNMS_OFFSET UNITYSDK_OFFSET(0xA0CB220)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_ABILITYDURATIONMS_OFFSET UNITYSDK_OFFSET(0xA0CB200)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_ABILITYID_OFFSET UNITYSDK_OFFSET(0xA0CB1E0)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_PLAYERHANDLE_OFFSET UNITYSDK_OFFSET(0xA0CB1C0)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_ABILITYCOOLDOWNMS_OFFSET UNITYSDK_OFFSET(0xA0CB230)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_ABILITYDURATIONMS_OFFSET UNITYSDK_OFFSET(0xA0CB210)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_ABILITYID_OFFSET UNITYSDK_OFFSET(0xA0CB1F0)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_PLAYERHANDLE_OFFSET UNITYSDK_OFFSET(0xA0CB1D0)
#define EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS__CTOR_OFFSET UNITYSDK_OFFSET(0xA0CB240)

namespace Epic::OnlineServices::AntiCheatCommon
{
	inline static constexpr unsigned int LogPlayerUseAbilityOptions_TypeDefinitionIndex = 43293;

	class LogPlayerUseAbilityOptions : public ::System::Object
	{
	public:
		::System::UInt32 _AbilityDurationMs_k__BackingField; // 0x10
		::System::UInt32 _AbilityCooldownMs_k__BackingField; // 0x14
		::System::UInt32 _AbilityId_k__BackingField; // 0x18
		::System::IntPtr _PlayerHandle_k__BackingField; // 0x20

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS__CTOR_OFFSET))(this);
		}

		::System::IntPtr get_PlayerHandle()
		{
			return ((::System::IntPtr(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_PLAYERHANDLE_OFFSET))(this);
		}

		::System::Void set_PlayerHandle(::System::IntPtr a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::IntPtr))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_PLAYERHANDLE_OFFSET))(this, a1);
		}

		::System::UInt32 get_AbilityId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_ABILITYID_OFFSET))(this);
		}

		::System::Void set_AbilityId(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_ABILITYID_OFFSET))(this, a1);
		}

		::System::UInt32 get_AbilityDurationMs()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_ABILITYDURATIONMS_OFFSET))(this);
		}

		::System::Void set_AbilityDurationMs(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_ABILITYDURATIONMS_OFFSET))(this, a1);
		}

		::System::UInt32 get_AbilityCooldownMs()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_GET_ABILITYCOOLDOWNMS_OFFSET))(this);
		}

		::System::Void set_AbilityCooldownMs(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_ANTICHEATCOMMON_LOGPLAYERUSEABILITYOPTIONS_SET_ABILITYCOOLDOWNMS_OFFSET))(this, a1);
		}
	};
}
