#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"
#include "unitysdk/UnityEngine/BatteryStatus.h"
#include "unitysdk/UnityEngine/DeviceType.h"
#include "unitysdk/UnityEngine/Experimental/Rendering/DefaultFormat.h"
#include "unitysdk/UnityEngine/Experimental/Rendering/FormatUsage.h"
#include "unitysdk/UnityEngine/Experimental/Rendering/GraphicsFormat.h"
#include "unitysdk/UnityEngine/NPOTSupport.h"
#include "unitysdk/UnityEngine/OperatingSystemFamily.h"
#include "unitysdk/UnityEngine/RenderTextureDescriptor.h"
#include "unitysdk/UnityEngine/RenderTextureFormat.h"
#include "unitysdk/UnityEngine/Rendering/CopyTextureSupport.h"
#include "unitysdk/UnityEngine/Rendering/GraphicsDeviceType.h"
#include "unitysdk/UnityEngine/Rendering/RenderingThreadingMode.h"
#include "unitysdk/UnityEngine/Rendering/VertexAttributeFormat.h"
#include "unitysdk/UnityEngine/TextureFormat.h"

namespace System { class String; }
namespace System { struct Enum; }

#define UNITYENGINE_SYSTEMINFO_GETBATTERYLEVEL_OFFSET UNITYSDK_OFFSET(0x18A52A60)
#define UNITYENGINE_SYSTEMINFO_GETBATTERYSTATUS_OFFSET UNITYSDK_OFFSET(0x18A52A80)
#define UNITYENGINE_SYSTEMINFO_GETCOMPATIBLEFORMAT_OFFSET UNITYSDK_OFFSET(0x18A53910)
#define UNITYENGINE_SYSTEMINFO_GETCOPYTEXTURESUPPORT_OFFSET UNITYSDK_OFFSET(0x18A52F50)
#define UNITYENGINE_SYSTEMINFO_GETDEVICEMODEL_OFFSET UNITYSDK_OFFSET(0x18A52BA0)
#define UNITYENGINE_SYSTEMINFO_GETDEVICENAME_OFFSET UNITYSDK_OFFSET(0x18A52B80)
#define UNITYENGINE_SYSTEMINFO_GETDEVICETYPE_OFFSET UNITYSDK_OFFSET(0x18A52C60)
#define UNITYENGINE_SYSTEMINFO_GETDEVICEUNIQUEIDENTIFIER_OFFSET UNITYSDK_OFFSET(0x18A52B60)
#define UNITYENGINE_SYSTEMINFO_GETDISPLAYDRIVERVERSION_OFFSET UNITYSDK_OFFSET(0x18A52D80)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEID_OFFSET UNITYSDK_OFFSET(0x18A52CE0)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICENAME_OFFSET UNITYSDK_OFFSET(0x18A52CA0)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICETYPE_OFFSET UNITYSDK_OFFSET(0x18A52D20)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEVENDORID_OFFSET UNITYSDK_OFFSET(0x18A52D00)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEVENDOR_OFFSET UNITYSDK_OFFSET(0x18A52CC0)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEVERSION_OFFSET UNITYSDK_OFFSET(0x18A52D60)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSFORMAT_OFFSET UNITYSDK_OFFSET(0x18A53920)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSMEMORYSIZE_OFFSET UNITYSDK_OFFSET(0x18A52C80)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSMULTITHREADED_OFFSET UNITYSDK_OFFSET(0x18A52DC0)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSSHADERLEVEL_OFFSET UNITYSDK_OFFSET(0x18A52DA0)
#define UNITYENGINE_SYSTEMINFO_GETGRAPHICSUVSTARTSATTOP_OFFSET UNITYSDK_OFFSET(0x18A52D40)
#define UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZEX_OFFSET UNITYSDK_OFFSET(0x18A536D0)
#define UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZEY_OFFSET UNITYSDK_OFFSET(0x18A536F0)
#define UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZEZ_OFFSET UNITYSDK_OFFSET(0x18A53710)
#define UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZE_OFFSET UNITYSDK_OFFSET(0x18A536B0)
#define UNITYENGINE_SYSTEMINFO_GETMAXCUBEMAPSIZE_OFFSET UNITYSDK_OFFSET(0x18A535B0)
#define UNITYENGINE_SYSTEMINFO_GETMAXRENDERTEXTURESIZE_OFFSET UNITYSDK_OFFSET(0x18A535D0)
#define UNITYENGINE_SYSTEMINFO_GETMAXTEXTURESIZE_OFFSET UNITYSDK_OFFSET(0x18A53590)
#define UNITYENGINE_SYSTEMINFO_GETNPOTSUPPORT_OFFSET UNITYSDK_OFFSET(0x18A53570)
#define UNITYENGINE_SYSTEMINFO_GETOPERATINGSYSTEMFAMILY_OFFSET UNITYSDK_OFFSET(0x18A52AC0)
#define UNITYENGINE_SYSTEMINFO_GETOPERATINGSYSTEM_OFFSET UNITYSDK_OFFSET(0x18A52AA0)
#define UNITYENGINE_SYSTEMINFO_GETPHYSICALMEMORYMB_OFFSET UNITYSDK_OFFSET(0x18A52B40)
#define UNITYENGINE_SYSTEMINFO_GETPROCESSORCOUNT_OFFSET UNITYSDK_OFFSET(0x18A52B20)
#define UNITYENGINE_SYSTEMINFO_GETPROCESSORFREQUENCYMHZ_OFFSET UNITYSDK_OFFSET(0x18A52B00)
#define UNITYENGINE_SYSTEMINFO_GETPROCESSORTYPE_OFFSET UNITYSDK_OFFSET(0x18A52AE0)
#define UNITYENGINE_SYSTEMINFO_GETRENDERINGTHREADINGMODE_OFFSET UNITYSDK_OFFSET(0x18A52DE0)
#define UNITYENGINE_SYSTEMINFO_GETRENDERTEXTURESUPPORTEDMSAASAMPLECOUNT_INJECTED_OFFSET UNITYSDK_OFFSET(0x18A53940)
#define UNITYENGINE_SYSTEMINFO_GETRENDERTEXTURESUPPORTEDMSAASAMPLECOUNT_OFFSET UNITYSDK_OFFSET(0x18A53930)
#define UNITYENGINE_SYSTEMINFO_GET_BATTERYLEVEL_OFFSET UNITYSDK_OFFSET(0x18A52A50)
#define UNITYENGINE_SYSTEMINFO_GET_BATTERYSTATUS_OFFSET UNITYSDK_OFFSET(0x18A52A70)
#define UNITYENGINE_SYSTEMINFO_GET_COPYTEXTURESUPPORT_OFFSET UNITYSDK_OFFSET(0x18A52F40)
#define UNITYENGINE_SYSTEMINFO_GET_DEVICEMODEL_OFFSET UNITYSDK_OFFSET(0x18A52B90)
#define UNITYENGINE_SYSTEMINFO_GET_DEVICENAME_OFFSET UNITYSDK_OFFSET(0x18A52B70)
#define UNITYENGINE_SYSTEMINFO_GET_DEVICETYPE_OFFSET UNITYSDK_OFFSET(0x18A52C50)
#define UNITYENGINE_SYSTEMINFO_GET_DEVICEUNIQUEIDENTIFIER_OFFSET UNITYSDK_OFFSET(0x18A52B50)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEID_OFFSET UNITYSDK_OFFSET(0x18A52CD0)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICENAME_OFFSET UNITYSDK_OFFSET(0x18A52C90)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICETYPE_OFFSET UNITYSDK_OFFSET(0x18A52D10)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEVENDORID_OFFSET UNITYSDK_OFFSET(0x18A52CF0)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEVENDOR_OFFSET UNITYSDK_OFFSET(0x18A52CB0)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEVERSION_OFFSET UNITYSDK_OFFSET(0x18A52D50)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDRIVERVERSION_OFFSET UNITYSDK_OFFSET(0x18A52D70)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSMEMORYSIZE_OFFSET UNITYSDK_OFFSET(0x18A52C70)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSMULTITHREADED_OFFSET UNITYSDK_OFFSET(0x18A52DB0)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSPIXELFILLRATE_OFFSET UNITYSDK_OFFSET(0x18A53820)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSSHADERLEVEL_OFFSET UNITYSDK_OFFSET(0x18A52D90)
#define UNITYENGINE_SYSTEMINFO_GET_GRAPHICSUVSTARTSATTOP_OFFSET UNITYSDK_OFFSET(0x18A52D30)
#define UNITYENGINE_SYSTEMINFO_GET_HASDYNAMICUNIFORMARRAYINDEXINGINFRAGMENTSHADERS_OFFSET UNITYSDK_OFFSET(0x18A52E10)
#define UNITYENGINE_SYSTEMINFO_GET_HASHIDDENSURFACEREMOVALONGPU_OFFSET UNITYSDK_OFFSET(0x18A52DF0)
#define UNITYENGINE_SYSTEMINFO_GET_HASMIPMAXLEVEL_OFFSET UNITYSDK_OFFSET(0x18A537E0)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSCOMPUTE_OFFSET UNITYSDK_OFFSET(0x18A53680)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSDOMAIN_OFFSET UNITYSDK_OFFSET(0x18A53640)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSFRAGMENT_OFFSET UNITYSDK_OFFSET(0x18A53600)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSGEOMETRY_OFFSET UNITYSDK_OFFSET(0x18A53620)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSHULL_OFFSET UNITYSDK_OFFSET(0x18A53660)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSVERTEX_OFFSET UNITYSDK_OFFSET(0x18A535E0)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZEX_OFFSET UNITYSDK_OFFSET(0x18A536C0)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZEY_OFFSET UNITYSDK_OFFSET(0x18A536E0)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZEZ_OFFSET UNITYSDK_OFFSET(0x18A53700)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZE_OFFSET UNITYSDK_OFFSET(0x18A536A0)
#define UNITYENGINE_SYSTEMINFO_GET_MAXCUBEMAPSIZE_OFFSET UNITYSDK_OFFSET(0x18A535A0)
#define UNITYENGINE_SYSTEMINFO_GET_MAXRENDERTEXTURESIZE_OFFSET UNITYSDK_OFFSET(0x18A535C0)
#define UNITYENGINE_SYSTEMINFO_GET_MAXTEXTURESIZE_OFFSET UNITYSDK_OFFSET(0x18A53580)
#define UNITYENGINE_SYSTEMINFO_GET_MINCONSTANTBUFFEROFFSETALIGNMENT_OFFSET UNITYSDK_OFFSET(0x18A537C0)
#define UNITYENGINE_SYSTEMINFO_GET_NPOTSUPPORT_OFFSET UNITYSDK_OFFSET(0x18A53560)
#define UNITYENGINE_SYSTEMINFO_GET_OPERATINGSYSTEMFAMILY_OFFSET UNITYSDK_OFFSET(0x18A52AB0)
#define UNITYENGINE_SYSTEMINFO_GET_OPERATINGSYSTEM_OFFSET UNITYSDK_OFFSET(0x18A52A90)
#define UNITYENGINE_SYSTEMINFO_GET_PROCESSORCOUNT_OFFSET UNITYSDK_OFFSET(0x18A52B10)
#define UNITYENGINE_SYSTEMINFO_GET_PROCESSORFREQUENCY_OFFSET UNITYSDK_OFFSET(0x18A52AF0)
#define UNITYENGINE_SYSTEMINFO_GET_PROCESSORTYPE_OFFSET UNITYSDK_OFFSET(0x18A52AD0)
#define UNITYENGINE_SYSTEMINFO_GET_RENDERINGTHREADINGMODE_OFFSET UNITYSDK_OFFSET(0x18A52DD0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTEDRANDOMWRITETARGETCOUNT_OFFSET UNITYSDK_OFFSET(0x18A53080)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTEDRENDERTARGETCOUNT_OFFSET UNITYSDK_OFFSET(0x18A53040)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTMETALFX_OFFSET UNITYSDK_OFFSET(0x18A53880)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTS2DARRAYTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52EE0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTS32BITSINDEXBUFFER_OFFSET UNITYSDK_OFFSET(0x18A53000)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTS3DRENDERTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52F00)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTS3DTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52EC0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSACCELEROMETER_OFFSET UNITYSDK_OFFSET(0x18A52BB0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSASYNCCOMPUTE_OFFSET UNITYSDK_OFFSET(0x18A53720)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSASYNCGPUREADBACK_OFFSET UNITYSDK_OFFSET(0x18A53760)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSAUDIO_OFFSET UNITYSDK_OFFSET(0x18A52C30)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSCOMPUTESHADERS_OFFSET UNITYSDK_OFFSET(0x18A52F60)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSCONSERVATIVERASTER_OFFSET UNITYSDK_OFFSET(0x18A538A0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSCUBEMAPARRAYTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52F20)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSDRAWBASEDVRS_OFFSET UNITYSDK_OFFSET(0x18A538E0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGEOMETRYSHADERS_OFFSET UNITYSDK_OFFSET(0x18A52F80)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGPUFENCE_OFFSET UNITYSDK_OFFSET(0x18A53960)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGRAPHICSFENCE_OFFSET UNITYSDK_OFFSET(0x18A53740)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGYROSCOPE_OFFSET UNITYSDK_OFFSET(0x18A52BD0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSHARDWAREQUADTOPOLOGY_OFFSET UNITYSDK_OFFSET(0x18A52FE0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSIMAGEEFFECTS_OFFSET UNITYSDK_OFFSET(0x18A52EB0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSINSTANCING_OFFSET UNITYSDK_OFFSET(0x18A52FC0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSLOCATIONSERVICE_OFFSET UNITYSDK_OFFSET(0x18A52BF0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMIPSTREAMING_OFFSET UNITYSDK_OFFSET(0x18A53800)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMOTIONVECTORS_OFFSET UNITYSDK_OFFSET(0x18A52E80)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMULTISAMPLEAUTORESOLVE_OFFSET UNITYSDK_OFFSET(0x18A530C0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMULTISAMPLEDTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A530A0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRAWSHADOWDEPTHSAMPLING_OFFSET UNITYSDK_OFFSET(0x18A52E50)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRAYTRACING_OFFSET UNITYSDK_OFFSET(0x18A53780)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRENDERTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52E70)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRENDERTOCUBEMAP_OFFSET UNITYSDK_OFFSET(0x18A52EA0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSEPARATEDRENDERTARGETSBLEND_OFFSET UNITYSDK_OFFSET(0x18A53060)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSETCONSTANTBUFFER_OFFSET UNITYSDK_OFFSET(0x18A537A0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSHADOWS_OFFSET UNITYSDK_OFFSET(0x18A52E30)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSKINBATCHING_OFFSET UNITYSDK_OFFSET(0x18A538C0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSPARSETEXTURES_OFFSET UNITYSDK_OFFSET(0x18A53020)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSTENCIL_OFFSET UNITYSDK_OFFSET(0x18A53120)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSTOREANDRESOLVEACTION_OFFSET UNITYSDK_OFFSET(0x18A53850)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSTESSELLATIONSHADERS_OFFSET UNITYSDK_OFFSET(0x18A52FA0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSTEXTUREWRAPMIRRORONCE_OFFSET UNITYSDK_OFFSET(0x18A530E0)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSVERTEXPROGRAMS_OFFSET UNITYSDK_OFFSET(0x18A53870)
#define UNITYENGINE_SYSTEMINFO_GET_SUPPORTSVIBRATION_OFFSET UNITYSDK_OFFSET(0x18A52C10)
#define UNITYENGINE_SYSTEMINFO_GET_SYSTEMMEMORYSIZE_OFFSET UNITYSDK_OFFSET(0x18A52B30)
#define UNITYENGINE_SYSTEMINFO_GET_USESLOADSTOREACTIONS_OFFSET UNITYSDK_OFFSET(0x18A53830)
#define UNITYENGINE_SYSTEMINFO_GET_USESREVERSEDZBUFFER_OFFSET UNITYSDK_OFFSET(0x18A53100)
#define UNITYENGINE_SYSTEMINFO_HASDYNAMICUNIFORMARRAYINDEXINGINFRAGMENTSHADERS_OFFSET UNITYSDK_OFFSET(0x18A52E20)
#define UNITYENGINE_SYSTEMINFO_HASHIDDENSURFACEREMOVALONGPU_OFFSET UNITYSDK_OFFSET(0x18A52E00)
#define UNITYENGINE_SYSTEMINFO_HASMIPMAXLEVEL_OFFSET UNITYSDK_OFFSET(0x18A537F0)
#define UNITYENGINE_SYSTEMINFO_HASRENDERTEXTURENATIVE_OFFSET UNITYSDK_OFFSET(0x18A53260)
#define UNITYENGINE_SYSTEMINFO_ISADRENODRIVERVERSIONMATCH_OFFSET UNITYSDK_OFFSET(0x18A53950)
#define UNITYENGINE_SYSTEMINFO_ISFORMATSUPPORTED_OFFSET UNITYSDK_OFFSET(0x18A53900)
#define UNITYENGINE_SYSTEMINFO_ISGYROAVAILABLE_OFFSET UNITYSDK_OFFSET(0x18A52BE0)
#define UNITYENGINE_SYSTEMINFO_ISVALIDENUMVALUE_OFFSET UNITYSDK_OFFSET(0x18A53130)
#define UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSCOMPUTE_OFFSET UNITYSDK_OFFSET(0x18A53690)
#define UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSDOMAIN_OFFSET UNITYSDK_OFFSET(0x18A53650)
#define UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSFRAGMENT_OFFSET UNITYSDK_OFFSET(0x18A53610)
#define UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSGEOMETRY_OFFSET UNITYSDK_OFFSET(0x18A53630)
#define UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSHULL_OFFSET UNITYSDK_OFFSET(0x18A53670)
#define UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSVERTEX_OFFSET UNITYSDK_OFFSET(0x18A535F0)
#define UNITYENGINE_SYSTEMINFO_MINCONSTANTBUFFEROFFSETALIGNMENT_OFFSET UNITYSDK_OFFSET(0x18A537D0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTEDRANDOMWRITETARGETCOUNT_OFFSET UNITYSDK_OFFSET(0x18A53090)
#define UNITYENGINE_SYSTEMINFO_SUPPORTEDRENDERTARGETCOUNT_OFFSET UNITYSDK_OFFSET(0x18A53050)
#define UNITYENGINE_SYSTEMINFO_SUPPORTMETALFX_OFFSET UNITYSDK_OFFSET(0x18A53890)
#define UNITYENGINE_SYSTEMINFO_SUPPORTS2DARRAYTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52EF0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTS32BITSINDEXBUFFER_OFFSET UNITYSDK_OFFSET(0x18A53010)
#define UNITYENGINE_SYSTEMINFO_SUPPORTS3DRENDERTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52F10)
#define UNITYENGINE_SYSTEMINFO_SUPPORTS3DTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52ED0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSACCELEROMETER_OFFSET UNITYSDK_OFFSET(0x18A52BC0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSASYNCCOMPUTE_OFFSET UNITYSDK_OFFSET(0x18A53730)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSASYNCGPUREADBACK_OFFSET UNITYSDK_OFFSET(0x18A53770)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSAUDIO_OFFSET UNITYSDK_OFFSET(0x18A52C40)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSBLENDINGONRENDERTEXTUREFORMATNATIVE_OFFSET UNITYSDK_OFFSET(0x18A53350)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSBLENDINGONRENDERTEXTUREFORMAT_OFFSET UNITYSDK_OFFSET(0x18A53270)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSCOMPUTESHADERS_OFFSET UNITYSDK_OFFSET(0x18A52F70)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSCONSERVATIVERASTER_OFFSET UNITYSDK_OFFSET(0x18A538B0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSCUBEMAPARRAYTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A52F30)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSDRAWBASEDVRS_OFFSET UNITYSDK_OFFSET(0x18A538F0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSGEOMETRYSHADERS_OFFSET UNITYSDK_OFFSET(0x18A52F90)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSGPUFENCE_OFFSET UNITYSDK_OFFSET(0x18A53750)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSHARDWAREQUADTOPOLOGY_OFFSET UNITYSDK_OFFSET(0x18A52FF0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSINSTANCING_OFFSET UNITYSDK_OFFSET(0x18A52FD0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSLOCATIONSERVICE_OFFSET UNITYSDK_OFFSET(0x18A52C00)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSMIPSTREAMING_OFFSET UNITYSDK_OFFSET(0x18A53810)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSMOTIONVECTORS_OFFSET UNITYSDK_OFFSET(0x18A52E90)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSMULTISAMPLEAUTORESOLVE_OFFSET UNITYSDK_OFFSET(0x18A530D0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSMULTISAMPLEDTEXTURES_OFFSET UNITYSDK_OFFSET(0x18A530B0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSRAWSHADOWDEPTHSAMPLING_OFFSET UNITYSDK_OFFSET(0x18A52E60)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSRAYTRACING_OFFSET UNITYSDK_OFFSET(0x18A53790)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSRENDERTEXTUREFORMAT_OFFSET UNITYSDK_OFFSET(0x18A531A0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSSEPARATEDRENDERTARGETSBLEND_OFFSET UNITYSDK_OFFSET(0x18A53070)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSSETCONSTANTBUFFER_OFFSET UNITYSDK_OFFSET(0x18A537B0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSSHADOWS_OFFSET UNITYSDK_OFFSET(0x18A52E40)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSSKINBATCHING_OFFSET UNITYSDK_OFFSET(0x18A538D0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSSPARSETEXTURES_OFFSET UNITYSDK_OFFSET(0x18A53030)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSSTOREANDRESOLVEACTION_OFFSET UNITYSDK_OFFSET(0x18A53860)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSTESSELLATIONSHADERS_OFFSET UNITYSDK_OFFSET(0x18A52FB0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSTEXTUREFORMATNATIVE_OFFSET UNITYSDK_OFFSET(0x18A53420)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSTEXTUREFORMAT_OFFSET UNITYSDK_OFFSET(0x18A53360)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSTEXTUREWRAPMIRRORONCE_OFFSET UNITYSDK_OFFSET(0x18A530F0)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSVERTEXATTRIBUTEFORMATNATIVE_OFFSET UNITYSDK_OFFSET(0x18A53550)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSVERTEXATTRIBUTEFORMAT_OFFSET UNITYSDK_OFFSET(0x18A53430)
#define UNITYENGINE_SYSTEMINFO_SUPPORTSVIBRATION_OFFSET UNITYSDK_OFFSET(0x18A52C20)
#define UNITYENGINE_SYSTEMINFO_USESLOADSTOREACTIONS_OFFSET UNITYSDK_OFFSET(0x18A53840)
#define UNITYENGINE_SYSTEMINFO_USESREVERSEDZBUFFER_OFFSET UNITYSDK_OFFSET(0x18A53110)
#define UNITYENGINE_SYSTEMINFO__CTOR_OFFSET UNITYSDK_OFFSET(0x18A53970)

namespace UnityEngine
{
	inline static constexpr unsigned int SystemInfo_TypeDefinitionIndex = 4199;

	class SystemInfo : public ::System::Object
	{
	public:
		// static const ::System::String* unsupportedIdentifier; // 0x0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO__CTOR_OFFSET))(this);
		}

		static ::System::Single get_batteryLevel()
		{
			return ((::System::Single(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_BATTERYLEVEL_OFFSET))();
		}

		static ::UnityEngine::BatteryStatus get_batteryStatus()
		{
			return ((::UnityEngine::BatteryStatus(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_BATTERYSTATUS_OFFSET))();
		}

		static ::System::String* get_operatingSystem()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_OPERATINGSYSTEM_OFFSET))();
		}

		static ::UnityEngine::OperatingSystemFamily get_operatingSystemFamily()
		{
			return ((::UnityEngine::OperatingSystemFamily(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_OPERATINGSYSTEMFAMILY_OFFSET))();
		}

		static ::System::String* get_processorType()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_PROCESSORTYPE_OFFSET))();
		}

		static ::System::Int32 get_processorFrequency()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_PROCESSORFREQUENCY_OFFSET))();
		}

		static ::System::Int32 get_processorCount()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_PROCESSORCOUNT_OFFSET))();
		}

		static ::System::Int32 get_systemMemorySize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SYSTEMMEMORYSIZE_OFFSET))();
		}

		static ::System::String* get_deviceUniqueIdentifier()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_DEVICEUNIQUEIDENTIFIER_OFFSET))();
		}

		static ::System::String* get_deviceName()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_DEVICENAME_OFFSET))();
		}

		static ::System::String* get_deviceModel()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_DEVICEMODEL_OFFSET))();
		}

		static ::System::Boolean get_supportsAccelerometer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSACCELEROMETER_OFFSET))();
		}

		static ::System::Boolean get_supportsGyroscope()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGYROSCOPE_OFFSET))();
		}

		static ::System::Boolean get_supportsLocationService()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSLOCATIONSERVICE_OFFSET))();
		}

		static ::System::Boolean get_supportsVibration()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSVIBRATION_OFFSET))();
		}

		static ::System::Boolean get_supportsAudio()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSAUDIO_OFFSET))();
		}

		static ::UnityEngine::DeviceType get_deviceType()
		{
			return ((::UnityEngine::DeviceType(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_DEVICETYPE_OFFSET))();
		}

		static ::System::Int32 get_graphicsMemorySize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSMEMORYSIZE_OFFSET))();
		}

		static ::System::String* get_graphicsDeviceName()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICENAME_OFFSET))();
		}

		static ::System::String* get_graphicsDeviceVendor()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEVENDOR_OFFSET))();
		}

		static ::System::Int32 get_graphicsDeviceID()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEID_OFFSET))();
		}

		static ::System::Int32 get_graphicsDeviceVendorID()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEVENDORID_OFFSET))();
		}

		static ::UnityEngine::Rendering::GraphicsDeviceType get_graphicsDeviceType()
		{
			return ((::UnityEngine::Rendering::GraphicsDeviceType(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICETYPE_OFFSET))();
		}

		static ::System::Boolean get_graphicsUVStartsAtTop()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSUVSTARTSATTOP_OFFSET))();
		}

		static ::System::String* get_graphicsDeviceVersion()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDEVICEVERSION_OFFSET))();
		}

		static ::System::String* get_graphicsDriverVersion()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSDRIVERVERSION_OFFSET))();
		}

		static ::System::Int32 get_graphicsShaderLevel()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSSHADERLEVEL_OFFSET))();
		}

		static ::System::Boolean get_graphicsMultiThreaded()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSMULTITHREADED_OFFSET))();
		}

		static ::UnityEngine::Rendering::RenderingThreadingMode get_renderingThreadingMode()
		{
			return ((::UnityEngine::Rendering::RenderingThreadingMode(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_RENDERINGTHREADINGMODE_OFFSET))();
		}

		static ::System::Boolean get_hasHiddenSurfaceRemovalOnGPU()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_HASHIDDENSURFACEREMOVALONGPU_OFFSET))();
		}

		static ::System::Boolean get_hasDynamicUniformArrayIndexingInFragmentShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_HASDYNAMICUNIFORMARRAYINDEXINGINFRAGMENTSHADERS_OFFSET))();
		}

		static ::System::Boolean get_supportsShadows()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSHADOWS_OFFSET))();
		}

		static ::System::Boolean get_supportsRawShadowDepthSampling()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRAWSHADOWDEPTHSAMPLING_OFFSET))();
		}

		static ::System::Boolean get_supportsRenderTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRENDERTEXTURES_OFFSET))();
		}

		static ::System::Boolean get_supportsMotionVectors()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMOTIONVECTORS_OFFSET))();
		}

		static ::System::Boolean get_supportsRenderToCubemap()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRENDERTOCUBEMAP_OFFSET))();
		}

		static ::System::Boolean get_supportsImageEffects()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSIMAGEEFFECTS_OFFSET))();
		}

		static ::System::Boolean get_supports3DTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTS3DTEXTURES_OFFSET))();
		}

		static ::System::Boolean get_supports2DArrayTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTS2DARRAYTEXTURES_OFFSET))();
		}

		static ::System::Boolean get_supports3DRenderTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTS3DRENDERTEXTURES_OFFSET))();
		}

		static ::System::Boolean get_supportsCubemapArrayTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSCUBEMAPARRAYTEXTURES_OFFSET))();
		}

		static ::UnityEngine::Rendering::CopyTextureSupport get_copyTextureSupport()
		{
			return ((::UnityEngine::Rendering::CopyTextureSupport(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_COPYTEXTURESUPPORT_OFFSET))();
		}

		static ::System::Boolean get_supportsComputeShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSCOMPUTESHADERS_OFFSET))();
		}

		static ::System::Boolean get_supportsGeometryShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGEOMETRYSHADERS_OFFSET))();
		}

		static ::System::Boolean get_supportsTessellationShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSTESSELLATIONSHADERS_OFFSET))();
		}

		static ::System::Boolean get_supportsInstancing()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSINSTANCING_OFFSET))();
		}

		static ::System::Boolean get_supportsHardwareQuadTopology()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSHARDWAREQUADTOPOLOGY_OFFSET))();
		}

		static ::System::Boolean get_supports32bitsIndexBuffer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTS32BITSINDEXBUFFER_OFFSET))();
		}

		static ::System::Boolean get_supportsSparseTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSPARSETEXTURES_OFFSET))();
		}

		static ::System::Int32 get_supportedRenderTargetCount()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTEDRENDERTARGETCOUNT_OFFSET))();
		}

		static ::System::Boolean get_supportsSeparatedRenderTargetsBlend()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSEPARATEDRENDERTARGETSBLEND_OFFSET))();
		}

		static ::System::Int32 get_supportedRandomWriteTargetCount()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTEDRANDOMWRITETARGETCOUNT_OFFSET))();
		}

		static ::System::Int32 get_supportsMultisampledTextures()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMULTISAMPLEDTEXTURES_OFFSET))();
		}

		static ::System::Boolean get_supportsMultisampleAutoResolve()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMULTISAMPLEAUTORESOLVE_OFFSET))();
		}

		static ::System::Int32 get_supportsTextureWrapMirrorOnce()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSTEXTUREWRAPMIRRORONCE_OFFSET))();
		}

		static ::System::Boolean get_usesReversedZBuffer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_USESREVERSEDZBUFFER_OFFSET))();
		}

		static ::System::Int32 get_supportsStencil()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSTENCIL_OFFSET))();
		}

		static ::System::Boolean IsValidEnumValue(::System::Enum* value)
		{
			return ((::System::Boolean(*)(::System::Enum*))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_ISVALIDENUMVALUE_OFFSET))(value);
		}

		static ::System::Boolean SupportsRenderTextureFormat(::UnityEngine::RenderTextureFormat format)
		{
			return ((::System::Boolean(*)(::UnityEngine::RenderTextureFormat))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSRENDERTEXTUREFORMAT_OFFSET))(format);
		}

		static ::System::Boolean SupportsBlendingOnRenderTextureFormat(::UnityEngine::RenderTextureFormat format)
		{
			return ((::System::Boolean(*)(::UnityEngine::RenderTextureFormat))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSBLENDINGONRENDERTEXTUREFORMAT_OFFSET))(format);
		}

		static ::System::Boolean SupportsTextureFormat(::UnityEngine::TextureFormat format)
		{
			return ((::System::Boolean(*)(::UnityEngine::TextureFormat))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSTEXTUREFORMAT_OFFSET))(format);
		}

		static ::System::Boolean SupportsVertexAttributeFormat(::UnityEngine::Rendering::VertexAttributeFormat format, ::System::Int32 dimension)
		{
			return ((::System::Boolean(*)(::UnityEngine::Rendering::VertexAttributeFormat, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSVERTEXATTRIBUTEFORMAT_OFFSET))(format, dimension);
		}

		static ::UnityEngine::NPOTSupport get_npotSupport()
		{
			return ((::UnityEngine::NPOTSupport(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_NPOTSUPPORT_OFFSET))();
		}

		static ::System::Int32 get_maxTextureSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXTEXTURESIZE_OFFSET))();
		}

		static ::System::Int32 get_maxCubemapSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCUBEMAPSIZE_OFFSET))();
		}

		static ::System::Int32 get_maxRenderTextureSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXRENDERTEXTURESIZE_OFFSET))();
		}

		static ::System::Int32 get_maxComputeBufferInputsVertex()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSVERTEX_OFFSET))();
		}

		static ::System::Int32 get_maxComputeBufferInputsFragment()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSFRAGMENT_OFFSET))();
		}

		static ::System::Int32 get_maxComputeBufferInputsGeometry()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSGEOMETRY_OFFSET))();
		}

		static ::System::Int32 get_maxComputeBufferInputsDomain()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSDOMAIN_OFFSET))();
		}

		static ::System::Int32 get_maxComputeBufferInputsHull()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSHULL_OFFSET))();
		}

		static ::System::Int32 get_maxComputeBufferInputsCompute()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEBUFFERINPUTSCOMPUTE_OFFSET))();
		}

		static ::System::Int32 get_maxComputeWorkGroupSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZE_OFFSET))();
		}

		static ::System::Int32 get_maxComputeWorkGroupSizeX()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZEX_OFFSET))();
		}

		static ::System::Int32 get_maxComputeWorkGroupSizeY()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZEY_OFFSET))();
		}

		static ::System::Int32 get_maxComputeWorkGroupSizeZ()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MAXCOMPUTEWORKGROUPSIZEZ_OFFSET))();
		}

		static ::System::Boolean get_supportsAsyncCompute()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSASYNCCOMPUTE_OFFSET))();
		}

		static ::System::Boolean get_supportsGraphicsFence()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGRAPHICSFENCE_OFFSET))();
		}

		static ::System::Boolean get_supportsAsyncGPUReadback()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSASYNCGPUREADBACK_OFFSET))();
		}

		static ::System::Boolean get_supportsRayTracing()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSRAYTRACING_OFFSET))();
		}

		static ::System::Boolean get_supportsSetConstantBuffer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSETCONSTANTBUFFER_OFFSET))();
		}

		static ::System::Boolean get_minConstantBufferOffsetAlignment()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_MINCONSTANTBUFFEROFFSETALIGNMENT_OFFSET))();
		}

		static ::System::Boolean get_hasMipMaxLevel()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_HASMIPMAXLEVEL_OFFSET))();
		}

		static ::System::Boolean get_supportsMipStreaming()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSMIPSTREAMING_OFFSET))();
		}

		static ::System::Int32 get_graphicsPixelFillrate()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_GRAPHICSPIXELFILLRATE_OFFSET))();
		}

		static ::System::Boolean get_usesLoadStoreActions()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_USESLOADSTOREACTIONS_OFFSET))();
		}

		static ::System::Boolean get_supportsStoreAndResolveAction()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSTOREANDRESOLVEACTION_OFFSET))();
		}

		static ::System::Boolean get_supportsVertexPrograms()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSVERTEXPROGRAMS_OFFSET))();
		}

		static ::System::Boolean get_supportMetalFX()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTMETALFX_OFFSET))();
		}

		static ::System::Boolean get_supportsConservativeRaster()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSCONSERVATIVERASTER_OFFSET))();
		}

		static ::System::Boolean get_supportsSkinBatching()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSSKINBATCHING_OFFSET))();
		}

		static ::System::Boolean get_supportsDrawBasedVRS()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSDRAWBASEDVRS_OFFSET))();
		}

		static ::System::Single GetBatteryLevel()
		{
			return ((::System::Single(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETBATTERYLEVEL_OFFSET))();
		}

		static ::UnityEngine::BatteryStatus GetBatteryStatus()
		{
			return ((::UnityEngine::BatteryStatus(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETBATTERYSTATUS_OFFSET))();
		}

		static ::System::String* GetOperatingSystem()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETOPERATINGSYSTEM_OFFSET))();
		}

		static ::UnityEngine::OperatingSystemFamily GetOperatingSystemFamily()
		{
			return ((::UnityEngine::OperatingSystemFamily(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETOPERATINGSYSTEMFAMILY_OFFSET))();
		}

		static ::System::String* GetProcessorType()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETPROCESSORTYPE_OFFSET))();
		}

		static ::System::Int32 GetProcessorFrequencyMHz()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETPROCESSORFREQUENCYMHZ_OFFSET))();
		}

		static ::System::Int32 GetProcessorCount()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETPROCESSORCOUNT_OFFSET))();
		}

		static ::System::Int32 GetPhysicalMemoryMB()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETPHYSICALMEMORYMB_OFFSET))();
		}

		static ::System::String* GetDeviceUniqueIdentifier()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETDEVICEUNIQUEIDENTIFIER_OFFSET))();
		}

		static ::System::String* GetDeviceName()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETDEVICENAME_OFFSET))();
		}

		static ::System::String* GetDeviceModel()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETDEVICEMODEL_OFFSET))();
		}

		static ::System::Boolean SupportsAccelerometer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSACCELEROMETER_OFFSET))();
		}

		static ::System::Boolean IsGyroAvailable()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_ISGYROAVAILABLE_OFFSET))();
		}

		static ::System::Boolean SupportsLocationService()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSLOCATIONSERVICE_OFFSET))();
		}

		static ::System::Boolean SupportsVibration()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSVIBRATION_OFFSET))();
		}

		static ::System::Boolean SupportsAudio()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSAUDIO_OFFSET))();
		}

		static ::UnityEngine::DeviceType GetDeviceType()
		{
			return ((::UnityEngine::DeviceType(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETDEVICETYPE_OFFSET))();
		}

		static ::System::Int32 GetGraphicsMemorySize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSMEMORYSIZE_OFFSET))();
		}

		static ::System::String* GetGraphicsDeviceName()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICENAME_OFFSET))();
		}

		static ::System::String* GetGraphicsDeviceVendor()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEVENDOR_OFFSET))();
		}

		static ::System::Int32 GetGraphicsDeviceID()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEID_OFFSET))();
		}

		static ::System::Int32 GetGraphicsDeviceVendorID()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEVENDORID_OFFSET))();
		}

		static ::UnityEngine::Rendering::GraphicsDeviceType GetGraphicsDeviceType()
		{
			return ((::UnityEngine::Rendering::GraphicsDeviceType(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICETYPE_OFFSET))();
		}

		static ::System::Boolean GetGraphicsUVStartsAtTop()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSUVSTARTSATTOP_OFFSET))();
		}

		static ::System::String* GetGraphicsDeviceVersion()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSDEVICEVERSION_OFFSET))();
		}

		static ::System::String* GetDisplayDriverVersion()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETDISPLAYDRIVERVERSION_OFFSET))();
		}

		static ::System::Int32 GetGraphicsShaderLevel()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSSHADERLEVEL_OFFSET))();
		}

		static ::System::Boolean GetGraphicsMultiThreaded()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSMULTITHREADED_OFFSET))();
		}

		static ::UnityEngine::Rendering::RenderingThreadingMode GetRenderingThreadingMode()
		{
			return ((::UnityEngine::Rendering::RenderingThreadingMode(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETRENDERINGTHREADINGMODE_OFFSET))();
		}

		static ::System::Boolean HasHiddenSurfaceRemovalOnGPU()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_HASHIDDENSURFACEREMOVALONGPU_OFFSET))();
		}

		static ::System::Boolean HasDynamicUniformArrayIndexingInFragmentShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_HASDYNAMICUNIFORMARRAYINDEXINGINFRAGMENTSHADERS_OFFSET))();
		}

		static ::System::Boolean SupportsShadows()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSSHADOWS_OFFSET))();
		}

		static ::System::Boolean SupportsRawShadowDepthSampling()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSRAWSHADOWDEPTHSAMPLING_OFFSET))();
		}

		static ::System::Boolean SupportsMotionVectors()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSMOTIONVECTORS_OFFSET))();
		}

		static ::System::Boolean Supports3DTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTS3DTEXTURES_OFFSET))();
		}

		static ::System::Boolean Supports2DArrayTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTS2DARRAYTEXTURES_OFFSET))();
		}

		static ::System::Boolean Supports3DRenderTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTS3DRENDERTEXTURES_OFFSET))();
		}

		static ::System::Boolean SupportsCubemapArrayTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSCUBEMAPARRAYTEXTURES_OFFSET))();
		}

		static ::UnityEngine::Rendering::CopyTextureSupport GetCopyTextureSupport()
		{
			return ((::UnityEngine::Rendering::CopyTextureSupport(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETCOPYTEXTURESUPPORT_OFFSET))();
		}

		static ::System::Boolean SupportsComputeShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSCOMPUTESHADERS_OFFSET))();
		}

		static ::System::Boolean SupportsGeometryShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSGEOMETRYSHADERS_OFFSET))();
		}

		static ::System::Boolean SupportsTessellationShaders()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSTESSELLATIONSHADERS_OFFSET))();
		}

		static ::System::Boolean SupportsInstancing()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSINSTANCING_OFFSET))();
		}

		static ::System::Boolean SupportsHardwareQuadTopology()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSHARDWAREQUADTOPOLOGY_OFFSET))();
		}

		static ::System::Boolean Supports32bitsIndexBuffer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTS32BITSINDEXBUFFER_OFFSET))();
		}

		static ::System::Boolean SupportsSparseTextures()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSSPARSETEXTURES_OFFSET))();
		}

		static ::System::Int32 SupportedRenderTargetCount()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTEDRENDERTARGETCOUNT_OFFSET))();
		}

		static ::System::Boolean SupportsSeparatedRenderTargetsBlend()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSSEPARATEDRENDERTARGETSBLEND_OFFSET))();
		}

		static ::System::Int32 SupportedRandomWriteTargetCount()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTEDRANDOMWRITETARGETCOUNT_OFFSET))();
		}

		static ::System::Int32 MaxComputeBufferInputsVertex()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSVERTEX_OFFSET))();
		}

		static ::System::Int32 MaxComputeBufferInputsFragment()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSFRAGMENT_OFFSET))();
		}

		static ::System::Int32 MaxComputeBufferInputsGeometry()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSGEOMETRY_OFFSET))();
		}

		static ::System::Int32 MaxComputeBufferInputsDomain()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSDOMAIN_OFFSET))();
		}

		static ::System::Int32 MaxComputeBufferInputsHull()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSHULL_OFFSET))();
		}

		static ::System::Int32 MaxComputeBufferInputsCompute()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_MAXCOMPUTEBUFFERINPUTSCOMPUTE_OFFSET))();
		}

		static ::System::Int32 SupportsMultisampledTextures()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSMULTISAMPLEDTEXTURES_OFFSET))();
		}

		static ::System::Boolean SupportsMultisampleAutoResolve()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSMULTISAMPLEAUTORESOLVE_OFFSET))();
		}

		static ::System::Int32 SupportsTextureWrapMirrorOnce()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSTEXTUREWRAPMIRRORONCE_OFFSET))();
		}

		static ::System::Boolean UsesReversedZBuffer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_USESREVERSEDZBUFFER_OFFSET))();
		}

		static ::System::Boolean HasRenderTextureNative(::UnityEngine::RenderTextureFormat format)
		{
			return ((::System::Boolean(*)(::UnityEngine::RenderTextureFormat))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_HASRENDERTEXTURENATIVE_OFFSET))(format);
		}

		static ::System::Boolean SupportsBlendingOnRenderTextureFormatNative(::UnityEngine::RenderTextureFormat format)
		{
			return ((::System::Boolean(*)(::UnityEngine::RenderTextureFormat))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSBLENDINGONRENDERTEXTUREFORMATNATIVE_OFFSET))(format);
		}

		static ::System::Boolean SupportsTextureFormatNative(::UnityEngine::TextureFormat format)
		{
			return ((::System::Boolean(*)(::UnityEngine::TextureFormat))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSTEXTUREFORMATNATIVE_OFFSET))(format);
		}

		static ::System::Boolean SupportsVertexAttributeFormatNative(::UnityEngine::Rendering::VertexAttributeFormat format, ::System::Int32 dimension)
		{
			return ((::System::Boolean(*)(::UnityEngine::Rendering::VertexAttributeFormat, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSVERTEXATTRIBUTEFORMATNATIVE_OFFSET))(format, dimension);
		}

		static ::UnityEngine::NPOTSupport GetNPOTSupport()
		{
			return ((::UnityEngine::NPOTSupport(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETNPOTSUPPORT_OFFSET))();
		}

		static ::System::Int32 GetMaxTextureSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETMAXTEXTURESIZE_OFFSET))();
		}

		static ::System::Int32 GetMaxCubemapSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETMAXCUBEMAPSIZE_OFFSET))();
		}

		static ::System::Int32 GetMaxRenderTextureSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETMAXRENDERTEXTURESIZE_OFFSET))();
		}

		static ::System::Int32 GetMaxComputeWorkGroupSize()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZE_OFFSET))();
		}

		static ::System::Int32 GetMaxComputeWorkGroupSizeX()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZEX_OFFSET))();
		}

		static ::System::Int32 GetMaxComputeWorkGroupSizeY()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZEY_OFFSET))();
		}

		static ::System::Int32 GetMaxComputeWorkGroupSizeZ()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETMAXCOMPUTEWORKGROUPSIZEZ_OFFSET))();
		}

		static ::System::Boolean SupportsAsyncCompute()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSASYNCCOMPUTE_OFFSET))();
		}

		static ::System::Boolean SupportsGPUFence()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSGPUFENCE_OFFSET))();
		}

		static ::System::Boolean SupportsAsyncGPUReadback()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSASYNCGPUREADBACK_OFFSET))();
		}

		static ::System::Boolean SupportsRayTracing()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSRAYTRACING_OFFSET))();
		}

		static ::System::Boolean SupportsSetConstantBuffer()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSSETCONSTANTBUFFER_OFFSET))();
		}

		static ::System::Boolean MinConstantBufferOffsetAlignment()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_MINCONSTANTBUFFEROFFSETALIGNMENT_OFFSET))();
		}

		static ::System::Boolean HasMipMaxLevel()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_HASMIPMAXLEVEL_OFFSET))();
		}

		static ::System::Boolean SupportsMipStreaming()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSMIPSTREAMING_OFFSET))();
		}

		static ::System::Boolean IsFormatSupported(::UnityEngine::Experimental::Rendering::GraphicsFormat format, ::UnityEngine::Experimental::Rendering::FormatUsage usage)
		{
			return ((::System::Boolean(*)(::UnityEngine::Experimental::Rendering::GraphicsFormat, ::UnityEngine::Experimental::Rendering::FormatUsage))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_ISFORMATSUPPORTED_OFFSET))(format, usage);
		}

		static ::UnityEngine::Experimental::Rendering::GraphicsFormat GetCompatibleFormat(::UnityEngine::Experimental::Rendering::GraphicsFormat format, ::UnityEngine::Experimental::Rendering::FormatUsage usage)
		{
			return ((::UnityEngine::Experimental::Rendering::GraphicsFormat(*)(::UnityEngine::Experimental::Rendering::GraphicsFormat, ::UnityEngine::Experimental::Rendering::FormatUsage))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETCOMPATIBLEFORMAT_OFFSET))(format, usage);
		}

		static ::UnityEngine::Experimental::Rendering::GraphicsFormat GetGraphicsFormat(::UnityEngine::Experimental::Rendering::DefaultFormat format)
		{
			return ((::UnityEngine::Experimental::Rendering::GraphicsFormat(*)(::UnityEngine::Experimental::Rendering::DefaultFormat))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETGRAPHICSFORMAT_OFFSET))(format);
		}

		static ::System::Int32 GetRenderTextureSupportedMSAASampleCount(::UnityEngine::RenderTextureDescriptor desc)
		{
			return ((::System::Int32(*)(::UnityEngine::RenderTextureDescriptor))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETRENDERTEXTURESUPPORTEDMSAASAMPLECOUNT_OFFSET))(desc);
		}

		static ::System::Boolean UsesLoadStoreActions()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_USESLOADSTOREACTIONS_OFFSET))();
		}

		static ::System::Boolean SupportsStoreAndResolveAction()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSSTOREANDRESOLVEACTION_OFFSET))();
		}

		static ::System::Boolean SupportMetalFX()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTMETALFX_OFFSET))();
		}

		static ::System::Boolean SupportsConservativeRaster()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSCONSERVATIVERASTER_OFFSET))();
		}

		static ::System::Boolean SupportsSkinBatching()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSSKINBATCHING_OFFSET))();
		}

		static ::System::Boolean SupportsDrawBasedVRS()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_SUPPORTSDRAWBASEDVRS_OFFSET))();
		}

		static ::System::Boolean IsAdrenoDriverVersionMatch(::System::Int32 version, ::System::Int32 op)
		{
			return ((::System::Boolean(*)(::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_ISADRENODRIVERVERSIONMATCH_OFFSET))(version, op);
		}

		static ::System::Boolean get_supportsGPUFence()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GET_SUPPORTSGPUFENCE_OFFSET))();
		}

		static ::System::Int32 GetRenderTextureSupportedMSAASampleCount_Injected(::UnityEngine::RenderTextureDescriptor& desc)
		{
			return ((::System::Int32(*)(::UnityEngine::RenderTextureDescriptor&))((::PBYTE)hIl2Cpp + UNITYENGINE_SYSTEMINFO_GETRENDERTEXTURESUPPORTEDMSAASAMPLECOUNT_INJECTED_OFFSET))(desc);
		}
	};
}
