#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace System::Collections { class IEnumerator; }
namespace System::Collections::Generic { template <typename T> class IEnumerator_1; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class MonoBehaviour; }

#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_MOVENEXT_OFFSET UNITYSDK_OFFSET(0x17E05840)
#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE_UNITYENGINE_MONOBEHAVIOUR__GETENUMERATOR_OFFSET UNITYSDK_OFFSET(0x17E05AB0)
#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_UNITYENGINE_MONOBEHAVIOUR__GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x17E05A40)
#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_IENUMERABLE_GETENUMERATOR_OFFSET UNITYSDK_OFFSET(0x17E05B30)
#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x17E05AA0)
#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET UNITYSDK_OFFSET(0x17E05A50)
#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x17E05830)
#define MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524__CTOR_OFFSET UNITYSDK_OFFSET(0x17E05810)

namespace MoleMole::Timeline
{
	inline static constexpr unsigned int ZNetEffectPlayableAsset_Class_1_F4CD650069C06524_TypeDefinitionIndex = 44680;

	class ZNetEffectPlayableAsset_Class_1_F4CD650069C06524 : public ::System::Object
	{
	public:
		::UnityEngine::MonoBehaviour* Field_1_1; // 0x10
		::UnityEngine::GameObject* Field_1_3; // 0x18
		::Il2CppArray<::UnityEngine::MonoBehaviour*>* Field_1_5; // 0x20
		::UnityEngine::GameObject* Field_1_4; // 0x28
		::System::Int32 Field_1_6; // 0x30
		::System::Int32 Field_1_2; // 0x34
		::System::Int32 Field_1_0; // 0x38

		::System::Void _ctor(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524__CTOR_OFFSET))(this, a1);
		}

		::System::Void System_IDisposable_Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET))(this);
		}

		::System::Boolean MoveNext()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_MOVENEXT_OFFSET))(this);
		}

		::UnityEngine::MonoBehaviour* System_Collections_Generic_IEnumerator_UnityEngine_MonoBehaviour__get_Current()
		{
			return ((::UnityEngine::MonoBehaviour*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_UNITYENGINE_MONOBEHAVIOUR__GET_CURRENT_OFFSET))(this);
		}

		::System::Void System_Collections_IEnumerator_Reset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET))(this);
		}

		::System::Object* System_Collections_IEnumerator_get_Current()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET))(this);
		}

		::System::Collections::Generic::IEnumerator_1<::UnityEngine::MonoBehaviour*>* System_Collections_Generic_IEnumerable_UnityEngine_MonoBehaviour__GetEnumerator()
		{
			return ((::System::Collections::Generic::IEnumerator_1<::UnityEngine::MonoBehaviour*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE_UNITYENGINE_MONOBEHAVIOUR__GETENUMERATOR_OFFSET))(this);
		}

		::System::Collections::IEnumerator* System_Collections_IEnumerable_GetEnumerator()
		{
			return ((::System::Collections::IEnumerator*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_TIMELINE_ZNETEFFECTPLAYABLEASSET_CLASS_1_F4CD650069C06524_SYSTEM_COLLECTIONS_IENUMERABLE_GETENUMERATOR_OFFSET))(this);
		}
	};
}
