#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Data/InternalDataCollectionBase.h"

namespace System { class String; }
namespace System::Collections { class ArrayList; }
namespace System::ComponentModel { class CollectionChangeEventArgs; }
namespace System::ComponentModel { class CollectionChangeEventHandler; }
namespace System::Data { class Constraint; }
namespace System::Data { class DataColumn; }
namespace System::Data { class DataTable; }
namespace System::Data { class ForeignKeyConstraint; }
namespace System::Data { class UniqueConstraint; }

#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ADDFOREIGNKEYCONSTRAINT_OFFSET UNITYSDK_OFFSET(0x1EAAE910)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ADDUNIQUECONSTRAINT_OFFSET UNITYSDK_OFFSET(0x1EAAE5D0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ADD_1_OFFSET UNITYSDK_OFFSET(0x1EAADF00)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ADD_2_OFFSET UNITYSDK_OFFSET(0x1EAAEAD0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ADD_OFFSET UNITYSDK_OFFSET(0x1EAADEF0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ARRAYADD_OFFSET UNITYSDK_OFFSET(0x1EAAEA80)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ARRAYREMOVE_OFFSET UNITYSDK_OFFSET(0x1EAAEB70)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ASSIGNNAME_OFFSET UNITYSDK_OFFSET(0x1EAAE890)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_AUTOGENERATED_OFFSET UNITYSDK_OFFSET(0x1EAAE530)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_BASEADD_OFFSET UNITYSDK_OFFSET(0x1EAAE980)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_BASEGROUPSWITCH_OFFSET UNITYSDK_OFFSET(0x1EAAEC10)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_BASEREMOVE_OFFSET UNITYSDK_OFFSET(0x1EAAEEA0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_CANREMOVE_OFFSET UNITYSDK_OFFSET(0x1EAAF300)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_CLEAR_OFFSET UNITYSDK_OFFSET(0x1EAAF330)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_COMPAREARRAYS_OFFSET UNITYSDK_OFFSET(0x1EAAFA30)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_CONTAINS_1_OFFSET UNITYSDK_OFFSET(0x1EAAF940)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_CONTAINS_OFFSET UNITYSDK_OFFSET(0x1EAAF920)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDCONSTRAINT_OFFSET UNITYSDK_OFFSET(0x1EAAE3D0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDFOREIGNKEYCONSTRAINT_OFFSET UNITYSDK_OFFSET(0x1EAAFB90)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDKEYCONSTRAINT_1_OFFSET UNITYSDK_OFFSET(0x1EAAFAA0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDKEYCONSTRAINT_OFFSET UNITYSDK_OFFSET(0x1EAAE6F0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_FINISHINITCONSTRAINTS_OFFSET UNITYSDK_OFFSET(0x1EAAFF90)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_GET_ITEM_1_OFFSET UNITYSDK_OFFSET(0x1EAADCD0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_GET_ITEM_OFFSET UNITYSDK_OFFSET(0x1EAADC10)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_GET_LIST_OFFSET UNITYSDK_OFFSET(0x1EAADC00)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_INTERNALINDEXOF_OFFSET UNITYSDK_OFFSET(0x1EAADD90)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_MAKENAME_OFFSET UNITYSDK_OFFSET(0x1EAAEBA0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_ONCOLLECTIONCHANGED_OFFSET UNITYSDK_OFFSET(0x1EAAEAB0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_REGISTERNAME_OFFSET UNITYSDK_OFFSET(0x1EAAD530)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_REMOVE_OFFSET UNITYSDK_OFFSET(0x1EAAFDC0)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION_UNREGISTERNAME_OFFSET UNITYSDK_OFFSET(0x1EAAD720)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION__CTOR_1_OFFSET UNITYSDK_OFFSET(0x1EAB0790)
#define SYSTEM_DATA_CONSTRAINTCOLLECTION__CTOR_OFFSET UNITYSDK_OFFSET(0x1EAADB40)

namespace System::Data
{
	inline static constexpr unsigned int ConstraintCollection_TypeDefinitionIndex = 39219;

	class ConstraintCollection : public ::System::Data::InternalDataCollectionBase
	{
	public:
		::Il2CppArray<::System::Data::Constraint*>* _delayLoadingConstraints; // 0x10
		::System::ComponentModel::CollectionChangeEventHandler* _onCollectionChanged; // 0x18
		::System::Data::DataTable* _table; // 0x20
		::System::Collections::ArrayList* _list; // 0x28
		::System::Int32 _defaultNameIndex; // 0x30
		::System::Boolean _fLoadForeignKeyConstraintsOnly; // 0x34

		::System::Void _ctor(::System::Data::DataTable* table)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::DataTable*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION__CTOR_OFFSET))(this, table);
		}

		::System::Void _ctor_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION__CTOR_1_OFFSET))(this);
		}

		::System::Collections::ArrayList* get_List()
		{
			return ((::System::Collections::ArrayList*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_GET_LIST_OFFSET))(this);
		}

		::System::Data::Constraint* get_Item(::System::Int32 index)
		{
			return ((::System::Data::Constraint*(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_GET_ITEM_OFFSET))(this, index);
		}

		::System::Data::Constraint* get_Item_1(::System::String* name)
		{
			return ((::System::Data::Constraint*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_GET_ITEM_1_OFFSET))(this, name);
		}

		::System::Void Add(::System::Data::Constraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ADD_OFFSET))(this, constraint);
		}

		::System::Void Add_1(::System::Data::Constraint* constraint, ::System::Boolean addUniqueWhenAddingForeign)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::Constraint*, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ADD_1_OFFSET))(this, constraint, addUniqueWhenAddingForeign);
		}

		::System::Data::Constraint* Add_2(::System::String* name, ::Il2CppArray<::System::Data::DataColumn*>* columns, ::System::Boolean primaryKey)
		{
			return ((::System::Data::Constraint*(*)(::PVOID, ::System::String*, ::Il2CppArray<::System::Data::DataColumn*>*, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ADD_2_OFFSET))(this, name, columns, primaryKey);
		}

		::System::Void AddUniqueConstraint(::System::Data::UniqueConstraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::UniqueConstraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ADDUNIQUECONSTRAINT_OFFSET))(this, constraint);
		}

		::System::Void AddForeignKeyConstraint(::System::Data::ForeignKeyConstraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::ForeignKeyConstraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ADDFOREIGNKEYCONSTRAINT_OFFSET))(this, constraint);
		}

		::System::Boolean AutoGenerated(::System::Data::Constraint* constraint)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_AUTOGENERATED_OFFSET))(this, constraint);
		}

		::System::Void ArrayAdd(::System::Data::Constraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ARRAYADD_OFFSET))(this, constraint);
		}

		::System::Void ArrayRemove(::System::Data::Constraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ARRAYREMOVE_OFFSET))(this, constraint);
		}

		::System::String* AssignName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ASSIGNNAME_OFFSET))(this);
		}

		::System::Void BaseAdd(::System::Data::Constraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_BASEADD_OFFSET))(this, constraint);
		}

		::System::Void BaseGroupSwitch(::Il2CppArray<::System::Data::Constraint*>* oldArray, ::System::Int32 oldLength, ::Il2CppArray<::System::Data::Constraint*>* newArray, ::System::Int32 newLength)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::System::Data::Constraint*>*, ::System::Int32, ::Il2CppArray<::System::Data::Constraint*>*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_BASEGROUPSWITCH_OFFSET))(this, oldArray, oldLength, newArray, newLength);
		}

		::System::Void BaseRemove(::System::Data::Constraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_BASEREMOVE_OFFSET))(this, constraint);
		}

		::System::Boolean CanRemove(::System::Data::Constraint* constraint, ::System::Boolean fThrowException)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Data::Constraint*, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_CANREMOVE_OFFSET))(this, constraint, fThrowException);
		}

		::System::Void Clear()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_CLEAR_OFFSET))(this);
		}

		::System::Boolean Contains(::System::String* name)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_CONTAINS_OFFSET))(this, name);
		}

		::System::Boolean Contains_1(::System::String* name, ::System::Boolean caseSensitive)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_CONTAINS_1_OFFSET))(this, name, caseSensitive);
		}

		::System::Data::Constraint* FindConstraint(::System::Data::Constraint* constraint)
		{
			return ((::System::Data::Constraint*(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDCONSTRAINT_OFFSET))(this, constraint);
		}

		::System::Data::UniqueConstraint* FindKeyConstraint(::Il2CppArray<::System::Data::DataColumn*>* columns)
		{
			return ((::System::Data::UniqueConstraint*(*)(::PVOID, ::Il2CppArray<::System::Data::DataColumn*>*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDKEYCONSTRAINT_OFFSET))(this, columns);
		}

		::System::Data::UniqueConstraint* FindKeyConstraint_1(::System::Data::DataColumn* column)
		{
			return ((::System::Data::UniqueConstraint*(*)(::PVOID, ::System::Data::DataColumn*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDKEYCONSTRAINT_1_OFFSET))(this, column);
		}

		::System::Data::ForeignKeyConstraint* FindForeignKeyConstraint(::Il2CppArray<::System::Data::DataColumn*>* parentColumns, ::Il2CppArray<::System::Data::DataColumn*>* childColumns)
		{
			return ((::System::Data::ForeignKeyConstraint*(*)(::PVOID, ::Il2CppArray<::System::Data::DataColumn*>*, ::Il2CppArray<::System::Data::DataColumn*>*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_FINDFOREIGNKEYCONSTRAINT_OFFSET))(this, parentColumns, childColumns);
		}

		static ::System::Boolean CompareArrays(::Il2CppArray<::System::Data::DataColumn*>* a1, ::Il2CppArray<::System::Data::DataColumn*>* a2)
		{
			return ((::System::Boolean(*)(::Il2CppArray<::System::Data::DataColumn*>*, ::Il2CppArray<::System::Data::DataColumn*>*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_COMPAREARRAYS_OFFSET))(a1, a2);
		}

		::System::Int32 InternalIndexOf(::System::String* constraintName)
		{
			return ((::System::Int32(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_INTERNALINDEXOF_OFFSET))(this, constraintName);
		}

		::System::String* MakeName(::System::Int32 index)
		{
			return ((::System::String*(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_MAKENAME_OFFSET))(this, index);
		}

		::System::Void OnCollectionChanged(::System::ComponentModel::CollectionChangeEventArgs* ccevent)
		{
			return ((::System::Void(*)(::PVOID, ::System::ComponentModel::CollectionChangeEventArgs*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_ONCOLLECTIONCHANGED_OFFSET))(this, ccevent);
		}

		::System::Void RegisterName(::System::String* name)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_REGISTERNAME_OFFSET))(this, name);
		}

		::System::Void Remove(::System::Data::Constraint* constraint)
		{
			return ((::System::Void(*)(::PVOID, ::System::Data::Constraint*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_REMOVE_OFFSET))(this, constraint);
		}

		::System::Void UnregisterName(::System::String* name)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_UNREGISTERNAME_OFFSET))(this, name);
		}

		::System::Void FinishInitConstraints()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_DATA_CONSTRAINTCOLLECTION_FINISHINITCONSTRAINTS_OFFSET))(this);
		}
	};
}
