#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/ValueType.h"

namespace NPCCrowd::AI { class Node; }
namespace NPCCrowd::AI { class WPGraphDataStateAssetSO_NodeStateOverrideData; }
namespace System { class String; }

#define NPCCROWD_AI_FNODERUNTIME_GET_AUTOGENERATEDID_OFFSET UNITYSDK_OFFSET(0x58B040)
#define NPCCROWD_AI_FNODERUNTIME_GET_BISENTERPOINT_OFFSET UNITYSDK_OFFSET(0x58B0E0)
#define NPCCROWD_AI_FNODERUNTIME_GET_BISJOINTPOINT_OFFSET UNITYSDK_OFFSET(0x58B060)
#define NPCCROWD_AI_FNODERUNTIME_GET_BISOPEN_OFFSET UNITYSDK_OFFSET(0x58AFE0)
#define NPCCROWD_AI_FNODERUNTIME_GET_CREATEINTERVAL_OFFSET UNITYSDK_OFFSET(0x58B210)
#define NPCCROWD_AI_FNODERUNTIME_GET_CREATEVARIOUS_OFFSET UNITYSDK_OFFSET(0x58B270)
#define NPCCROWD_AI_FNODERUNTIME_GET_EXITPOINTS_OFFSET UNITYSDK_OFFSET(0x58B0F0)
#define NPCCROWD_AI_FNODERUNTIME_GET_MOVEMENTSTYLETYPE_OFFSET UNITYSDK_OFFSET(0x58B1B0)
#define NPCCROWD_AI_FNODERUNTIME_GET_NPCTAGIDS_OFFSET UNITYSDK_OFFSET(0x58B150)
#define NPCCROWD_AI_FNODERUNTIME_GET_POSITION_OFFSET UNITYSDK_OFFSET(0x58AFB0)
#define NPCCROWD_AI_FNODERUNTIME_ISVALID_OFFSET UNITYSDK_OFFSET(0x58B080)
#define NPCCROWD_AI_FNODERUNTIME_RANDOMANPCTAG_OFFSET UNITYSDK_OFFSET(0x58B2D0)
#define NPCCROWD_AI_FNODERUNTIME_RANDOMEXITPOINT_OFFSET UNITYSDK_OFFSET(0x58B2E0)
#define NPCCROWD_AI_FNODERUNTIME_SETNODESTATEOVERRIDE_OFFSET UNITYSDK_OFFSET(0x58AF60)
#define NPCCROWD_AI_FNODERUNTIME__CTOR_OFFSET UNITYSDK_OFFSET(0x58AF40)

namespace NPCCrowd::AI
{
	inline static constexpr unsigned int FNodeRuntime_TypeDefinitionIndex = 42887;

	struct alignas(8) FNodeRuntime
	{
		::NPCCrowd::AI::Node* nodeCfg; // 0x10
		::System::Int32 nodeArrayIdx; // 0x18
		::NPCCrowd::AI::WPGraphDataStateAssetSO_NodeStateOverrideData* nodeOverrideState; // 0x20

		::System::Void _ctor(::NPCCrowd::AI::Node* innodeCfg, ::System::Int32 innodeArrayIdx)
		{
			return ((::System::Void(*)(::PVOID, ::NPCCrowd::AI::Node*, ::System::Int32))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME__CTOR_OFFSET))(this, innodeCfg, innodeArrayIdx);
		}

		::System::Void SetNodeStateOverride(::NPCCrowd::AI::WPGraphDataStateAssetSO_NodeStateOverrideData* state)
		{
			return ((::System::Void(*)(::PVOID, ::NPCCrowd::AI::WPGraphDataStateAssetSO_NodeStateOverrideData*))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_SETNODESTATEOVERRIDE_OFFSET))(this, state);
		}

		/*
		::UnityEngine::Vector3 get_Position()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_POSITION_OFFSET))(this);
		}
		*/

		::System::Boolean get_bIsOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_BISOPEN_OFFSET))(this);
		}

		::System::UInt16 get_autoGeneratedID()
		{
			return ((::System::UInt16(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_AUTOGENERATEDID_OFFSET))(this);
		}

		::System::Boolean get_bIsJointPoint()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_BISJOINTPOINT_OFFSET))(this);
		}

		::System::Boolean IsValid()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_ISVALID_OFFSET))(this);
		}

		::System::Boolean get_bIsEnterPoint()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_BISENTERPOINT_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt16>* get_ExitPoints()
		{
			return ((::Il2CppArray<::System::UInt16>*(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_EXITPOINTS_OFFSET))(this);
		}

		::Il2CppArray<::System::Int32>* get_npcTagIDs()
		{
			return ((::Il2CppArray<::System::Int32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_NPCTAGIDS_OFFSET))(this);
		}

		::System::String* get_movementStyleType()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_MOVEMENTSTYLETYPE_OFFSET))(this);
		}

		::System::Single get_createInterval()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_CREATEINTERVAL_OFFSET))(this);
		}

		::System::Single get_createVarious()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_GET_CREATEVARIOUS_OFFSET))(this);
		}

		::System::Int32 RandomANPCTag(::System::Int32 randIdx)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_RANDOMANPCTAG_OFFSET))(this, randIdx);
		}

		::System::UInt16 RandomExitPoint(::System::Int32 randIdx)
		{
			return ((::System::UInt16(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FNODERUNTIME_RANDOMEXITPOINT_OFFSET))(this, randIdx);
		}
	};
}
