#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/ValueType.h"

namespace NPCCrowd::AI { class Path; }
namespace NPCCrowd::AI { class WPGraphDataStateAssetSO_PathStateOverrideData; }
namespace NPCCrowd::AI { class WPPathSetting; }

#define NPCCROWD_AI_FPATHRUNTIME_GET_AUTOGENERATEDID_OFFSET UNITYSDK_OFFSET(0x694230)
#define NPCCROWD_AI_FPATHRUNTIME_GET_BISONEWAY_OFFSET UNITYSDK_OFFSET(0x694290)
#define NPCCROWD_AI_FPATHRUNTIME_GET_BISOPEN_OFFSET UNITYSDK_OFFSET(0x694300)
#define NPCCROWD_AI_FPATHRUNTIME_GET_COST_OFFSET UNITYSDK_OFFSET(0x6941C0)
#define NPCCROWD_AI_FPATHRUNTIME_GET_DIR_OFFSET UNITYSDK_OFFSET(0x694380)
#define NPCCROWD_AI_FPATHRUNTIME_GET_IDOFA_OFFSET UNITYSDK_OFFSET(0x694250)
#define NPCCROWD_AI_FPATHRUNTIME_GET_IDOFB_OFFSET UNITYSDK_OFFSET(0x694270)
#define NPCCROWD_AI_FPATHRUNTIME_GET_LINESPACE_OFFSET UNITYSDK_OFFSET(0x694400)
#define NPCCROWD_AI_FPATHRUNTIME_GET_NUMBEROFWAYS_OFFSET UNITYSDK_OFFSET(0x694410)
#define NPCCROWD_AI_FPATHRUNTIME_GET_PATHDIRECTION_OFFSET UNITYSDK_OFFSET(0x694420)
#define NPCCROWD_AI_FPATHRUNTIME_GET_WIDTH_OFFSET UNITYSDK_OFFSET(0x694360)
#define NPCCROWD_AI_FPATHRUNTIME_ISVALID_OFFSET UNITYSDK_OFFSET(0x694430)
#define NPCCROWD_AI_FPATHRUNTIME_SETPATHSTATEOVERRIDEDATA_OFFSET UNITYSDK_OFFSET(0x6943B0)
#define NPCCROWD_AI_FPATHRUNTIME__CTOR_OFFSET UNITYSDK_OFFSET(0x6941A0)

namespace NPCCrowd::AI
{
	inline static constexpr unsigned int FPathRuntime_TypeDefinitionIndex = 71307;

	struct alignas(8) FPathRuntime
	{
		::System::Int32 pathArrayIdx; // 0x10
		::NPCCrowd::AI::Path* pathCfg; // 0x18
		::NPCCrowd::AI::WPPathSetting* defaultPathSetting; // 0x20
		::NPCCrowd::AI::WPGraphDataStateAssetSO_PathStateOverrideData* pathOverrideState; // 0x28

		::System::Void _ctor(::NPCCrowd::AI::WPPathSetting* graphDefaultSetting, ::NPCCrowd::AI::Path* inpathCfg, ::System::Int32 inpathArrayIdx)
		{
			return ((::System::Void(*)(::PVOID, ::NPCCrowd::AI::WPPathSetting*, ::NPCCrowd::AI::Path*, ::System::Int32))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME__CTOR_OFFSET))(this, graphDefaultSetting, inpathCfg, inpathArrayIdx);
		}

		::System::Int32 get_cost()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_COST_OFFSET))(this);
		}

		::System::UInt16 get_autoGeneratedID()
		{
			return ((::System::UInt16(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_AUTOGENERATEDID_OFFSET))(this);
		}

		::System::UInt16 get_IDOfA()
		{
			return ((::System::UInt16(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_IDOFA_OFFSET))(this);
		}

		::System::UInt16 get_IDOfB()
		{
			return ((::System::UInt16(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_IDOFB_OFFSET))(this);
		}

		::System::Boolean get_bIsOneWay()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_BISONEWAY_OFFSET))(this);
		}

		::System::Boolean get_bIsOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_BISOPEN_OFFSET))(this);
		}

		::System::Single get_width()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_WIDTH_OFFSET))(this);
		}

		/*
		::UnityEngine::Vector3 get_dir()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_DIR_OFFSET))(this);
		}
		*/

		::System::Void SetPathStateOverrideData(::NPCCrowd::AI::WPGraphDataStateAssetSO_PathStateOverrideData* inPathStateOverride)
		{
			return ((::System::Void(*)(::PVOID, ::NPCCrowd::AI::WPGraphDataStateAssetSO_PathStateOverrideData*))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_SETPATHSTATEOVERRIDEDATA_OFFSET))(this, inPathStateOverride);
		}

		::System::Single get_lineSpace()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_LINESPACE_OFFSET))(this);
		}

		::System::Byte get_numberOfWays()
		{
			return ((::System::Byte(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_NUMBEROFWAYS_OFFSET))(this);
		}

		::System::Byte get_pathDirection()
		{
			return ((::System::Byte(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_GET_PATHDIRECTION_OFFSET))(this);
		}

		::System::Boolean IsValid()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_FPATHRUNTIME_ISVALID_OFFSET))(this);
		}
	};
}
