#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"
#include "unitysdk/UnityEngine/Vector3.h"

namespace NPCCrowd::AI { class Node; }
namespace NPCCrowd::AI { class Path; }

#define NPCCROWD_AI_NODECALUATEMEMORY_GET_AUTOGENERATEDID_OFFSET UNITYSDK_OFFSET(0xD405020)
#define NPCCROWD_AI_NODECALUATEMEMORY_GET_COMBINEDHEURISTIC_OFFSET UNITYSDK_OFFSET(0xD404FE0)
#define NPCCROWD_AI_NODECALUATEMEMORY_GET_POSITION_OFFSET UNITYSDK_OFFSET(0xD405000)
#define NPCCROWD_AI_NODECALUATEMEMORY__CTOR_OFFSET UNITYSDK_OFFSET(0xD404FF0)

namespace NPCCrowd::AI
{
	inline static constexpr unsigned int NodeCaluateMemory_TypeDefinitionIndex = 83662;

	class NodeCaluateMemory : public ::System::Object
	{
	public:
		::NPCCrowd::AI::NodeCaluateMemory* previousNode; // 0x10
		::NPCCrowd::AI::Node* node; // 0x18
		::NPCCrowd::AI::Path* previousPath; // 0x20
		::System::Single pathDistance; // 0x28
		::System::Single heuristicDistance; // 0x2C

		::System::Void _ctor(::NPCCrowd::AI::Node* nod)
		{
			return ((::System::Void(*)(::PVOID, ::NPCCrowd::AI::Node*))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODECALUATEMEMORY__CTOR_OFFSET))(this, nod);
		}

		::System::Single get_combinedHeuristic()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODECALUATEMEMORY_GET_COMBINEDHEURISTIC_OFFSET))(this);
		}

		::UnityEngine::Vector3& get_Position()
		{
			return ((::UnityEngine::Vector3&(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODECALUATEMEMORY_GET_POSITION_OFFSET))(this);
		}

		::System::Int32 get_autoGeneratedID()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODECALUATEMEMORY_GET_AUTOGENERATEDID_OFFSET))(this);
		}
	};
}
