#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"
#include "unitysdk/UnityEngine/Vector3.h"

#define NPCCROWD_AI_NODE_GET_ISOPEN_OFFSET UNITYSDK_OFFSET(0x102976D0)
#define NPCCROWD_AI_NODE_GET_POSITION_OFFSET UNITYSDK_OFFSET(0x10297670)
#define NPCCROWD_AI_NODE_SETASJOINTPOINT_OFFSET UNITYSDK_OFFSET(0x10297680)
#define NPCCROWD_AI_NODE_SETPOSITION_OFFSET UNITYSDK_OFFSET(0x10297610)
#define NPCCROWD_AI_NODE__CTOR_OFFSET UNITYSDK_OFFSET(0x102975F0)

namespace NPCCrowd::AI
{
	inline static constexpr unsigned int Node_TypeDefinitionIndex = 45280;

	class Node : public ::System::Object
	{
	public:
		::UnityEngine::Vector3 position; // 0x10
		::System::UInt16 autoGeneratedID; // 0x1C
		::System::Boolean bIsJointPoint; // 0x1E
		::System::Boolean bIsOpen; // 0x1F

		::System::Void _ctor(::UnityEngine::Vector3 pos)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODE__CTOR_OFFSET))(this, pos);
		}

		::System::Void SetPosition(::UnityEngine::Vector3 pos)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODE_SETPOSITION_OFFSET))(this, pos);
		}

		::UnityEngine::Vector3& get_Position()
		{
			return ((::UnityEngine::Vector3&(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODE_GET_POSITION_OFFSET))(this);
		}

		::System::Void SetAsJointPoint(::System::Boolean bis)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODE_SETASJOINTPOINT_OFFSET))(this, bis);
		}

		::System::Boolean get_IsOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_NODE_GET_ISOPEN_OFFSET))(this);
		}
	};
}
