#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"
#include "unitysdk/UnityEngine/Vector3.h"

namespace NPCCrowd::AI { class WPPathSetting; }

#define NPCCROWD_AI_PATH_CONTAINS_OFFSET UNITYSDK_OFFSET(0xF685020)
#define NPCCROWD_AI_PATH__CTOR_OFFSET UNITYSDK_OFFSET(0xF685010)

namespace NPCCrowd::AI
{
	inline static constexpr unsigned int Path_TypeDefinitionIndex = 40196;

	class Path : public ::System::Object
	{
	public:
		::System::Int32 cost; // 0x10
		::System::UInt16 autoGeneratedID; // 0x14
		::System::UInt16 IDOfA; // 0x16
		::System::UInt16 IDOfB; // 0x18
		::System::Boolean bIsOneWay; // 0x1A
		::System::Single width; // 0x1C
		::UnityEngine::Vector3 dir; // 0x20
		::System::Boolean bIsOverridePathSetting; // 0x2C
		::NPCCrowd::AI::WPPathSetting* graphPathSetting; // 0x30

		::System::Void _ctor(::System::UInt16 a, ::System::UInt16 b)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::UInt16))((::PBYTE)hIl2Cpp + NPCCROWD_AI_PATH__CTOR_OFFSET))(this, a, b);
		}

		::System::Boolean Contains(::System::UInt16 nodeId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt16))((::PBYTE)hIl2Cpp + NPCCROWD_AI_PATH_CONTAINS_OFFSET))(this, nodeId);
		}
	};
}
