#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/NPCCrowd/AI/PopulationLimitMode.h"
#include "unitysdk/System/Object.h"

namespace NPCCrowd::AI { class SpawnPointGroup; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define NPCCROWD_AI_SPAWNPOINTCONFIG__CTOR_OFFSET UNITYSDK_OFFSET(0x8C24510)

namespace NPCCrowd::AI
{
	inline static constexpr unsigned int SpawnPointConfig_TypeDefinitionIndex = 54312;

	class SpawnPointConfig : public ::System::Object
	{
	public:
		// static const ::System::Single DefaultPopulationWeight; // 0x0
		// static const ::System::Single DefaultNodeLoadMaxFactor; // 0x0
		::NPCCrowd::AI::PopulationLimitMode populationLimitMode; // 0x10
		::System::Single startPointGlobalWeight; // 0x14
		::System::Collections::Generic::List_1<::NPCCrowd::AI::SpawnPointGroup*>* autoGeneratedPoints; // 0x18
		::System::Collections::Generic::List_1<::NPCCrowd::AI::SpawnPointGroup*>* manualPoints; // 0x20

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_SPAWNPOINTCONFIG__CTOR_OFFSET))(this);
		}
	};
}
