#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace NPCCrowd::AI { class SpawnPointGroup; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define NPCCROWD_AI_SPAWNPOINTCONFIG__CTOR_OFFSET UNITYSDK_OFFSET(0xF3E4CB0)

namespace NPCCrowd::AI
{
	inline static constexpr unsigned int SpawnPointConfig_TypeDefinitionIndex = 81336;

	class SpawnPointConfig : public ::System::Object
	{
	public:
		::System::Collections::Generic::List_1<::NPCCrowd::AI::SpawnPointGroup*>* autoGeneratedPoints; // 0x10
		::System::Collections::Generic::List_1<::NPCCrowd::AI::SpawnPointGroup*>* manualPoints; // 0x18

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCCROWD_AI_SPAWNPOINTCONFIG__CTOR_OFFSET))(this);
		}
	};
}
