#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace System { class String; }

#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISFUNCUNLOCKED_OFFSET UNITYSDK_OFFSET(0xB175DC0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWCARD_OFFSET UNITYSDK_OFFSET(0xB1760C0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWCHARACTER_OFFSET UNITYSDK_OFFSET(0xB176050)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWDUNGEON_OFFSET UNITYSDK_OFFSET(0xB176130)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWGACHA_OFFSET UNITYSDK_OFFSET(0xB176210)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWTECHTREE_OFFSET UNITYSDK_OFFSET(0xB1761A0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__CTOR_OFFSET UNITYSDK_OFFSET(0xB175AC0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISCHARACTERUNLOCKED_OFFSET UNITYSDK_OFFSET(0xB175F10)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISDUNGEONUNLOCKED_OFFSET UNITYSDK_OFFSET(0xB176000)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISGACHAUNLOCKED_OFFSET UNITYSDK_OFFSET(0xB175D70)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISQUESTTREEUNLOCKED_OFFSET UNITYSDK_OFFSET(0xB175FB0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISTECHTREEUNLOCKED_OFFSET UNITYSDK_OFFSET(0xB175F60)

namespace RPG::Client::ActivityIdleLive
{
	inline static constexpr unsigned int IdleLiveUnlockStatusQueryService_TypeDefinitionIndex = 70207;

	class IdleLiveUnlockStatusQueryService : public ::System::Object
	{
	public:
		// static const ::System::String* UnlockKeyCharacter; // 0x0
		// static const ::System::String* UnlockKeyTechTree; // 0x0
		// static const ::System::String* UnlockKeyQuestTree; // 0x0
		// static const ::System::String* UnlockKeyDungeon; // 0x0
		// static const ::System::String* UnlockKeyGacha; // 0x0
		::System::UInt32 _UnlockIdTechTree; // 0x10
		::System::UInt32 _UnlockIdDungeon; // 0x14
		::System::UInt32 _UnlockIdQuestTree; // 0x18
		::System::UInt32 _UnlockIdGacha; // 0x1C
		::System::UInt32 _UnlockIdCharacter; // 0x20

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__CTOR_OFFSET))(this);
		}

		::System::Boolean _IsGachaUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISGACHAUNLOCKED_OFFSET))(this);
		}

		::System::Boolean _IsCharacterUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISCHARACTERUNLOCKED_OFFSET))(this);
		}

		::System::Boolean _IsTechTreeUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISTECHTREEUNLOCKED_OFFSET))(this);
		}

		::System::Boolean _IsQuestTreeUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISQUESTTREEUNLOCKED_OFFSET))(this);
		}

		::System::Boolean _IsDungeonUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE__ISDUNGEONUNLOCKED_OFFSET))(this);
		}

		::System::Boolean IsShowCharacter()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWCHARACTER_OFFSET))(this);
		}

		::System::Boolean IsShowCard()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWCARD_OFFSET))(this);
		}

		::System::Boolean IsShowDungeon()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWDUNGEON_OFFSET))(this);
		}

		::System::Boolean IsShowTechTree()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWTECHTREE_OFFSET))(this);
		}

		::System::Boolean IsShowGacha()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISSHOWGACHA_OFFSET))(this);
		}

		::System::Boolean IsFuncUnlocked(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEUNLOCKSTATUSQUERYSERVICE_ISFUNCUNLOCKED_OFFSET))(this, a1);
		}
	};
}
