#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/ENPCAvatarGender.h"
#include "unitysdk/ENPCAvatarSize.h"
#include "unitysdk/System/Object.h"

class NPCPrefabPartInfo;
class PartMaterials;
namespace Foundation::Unreal { class SerializableGameplayTagContainer; }
namespace NPCCrowd::Accessories { class NPCSlotAccessoryInfo; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define NPCPREFABINFO__CTOR_1_OFFSET UNITYSDK_OFFSET(0x11372C00)
#define NPCPREFABINFO__CTOR_OFFSET UNITYSDK_OFFSET(0x11372910)

inline static constexpr unsigned int NPCPrefabInfo_TypeDefinitionIndex = 61969;

class NPCPrefabInfo : public ::System::Object
{
public:
	::System::Collections::Generic::List_1<::NPCPrefabPartInfo*>* PartList; // 0x10
	::ENPCAvatarGender Gender; // 0x18
	::ENPCAvatarSize Size; // 0x1C
	::System::Int32 Id; // 0x20
	::System::String* Note; // 0x28
	::System::Collections::Generic::List_1<::System::Int32>* logicTags; // 0x30
	::Foundation::Unreal::SerializableGameplayTagContainer* gameplayTags; // 0x38
	::Foundation::Unreal::SerializableGameplayTagContainer* autoGeneratedGameplayTags; // 0x40
	::System::Collections::Generic::List_1<::PartMaterials*>* overridePartMaterials; // 0x48
	::System::Collections::Generic::List_1<::NPCCrowd::Accessories::NPCSlotAccessoryInfo*>* Accessories; // 0x50
	::System::Int32 shadowProxyMeshIndex; // 0x58

	::System::Void _ctor()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + NPCPREFABINFO__CTOR_OFFSET))(this);
	}

	::System::Void _ctor_1(::System::Int32 id, ::ENPCAvatarGender gender, ::ENPCAvatarSize size)
	{
		return ((::System::Void(*)(::PVOID, ::System::Int32, ::ENPCAvatarGender, ::ENPCAvatarSize))((::PBYTE)hIl2Cpp + NPCPREFABINFO__CTOR_1_OFFSET))(this, id, gender, size);
	}
};
