#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_C4CB11A2FD957208_Struct_2_98E057419FFAAB00.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Enum_3_8E90989A26BC6232.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIAbyssS2RoleChallengeWidgetController_DifficultyType.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_09621F974A776F22;
class Class_1_7F489DAFAFC6BD02;
class Class_1_E081FCEC8F87505A;
class Class_2_0A55B5A82A61DAFA_2;
class Class_2_14E7CE92E8A3183F;
class Class_2_1824EF69C8E376A3;
class Class_2_208CC9941471731A_535;
class Class_2_22F360303C414CB0_1;
class Class_2_47BEEACD66EA947F;
class Class_2_E621E51D351EB960;
class Class_2_E621E51D351EB960_1;
namespace MoleMole { class UIAbyssS2RoleChallengeContext; }
namespace MoleMole { class UIAbyssS2RoleChallengeInfoWidgetController; }
namespace MoleMole { class UIAbyssS2RoleChallengeListWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralBottomRewardInfoWidgetController; }
namespace MoleMole { class UIRoleSelectPageContext; }
namespace System { class EventArgs; }
namespace System { template <typename T1, typename T2> class Func_2; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET UNITYSDK_OFFSET(0x13ED7AE0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GET_ISCHALLENGELISTOPEN_OFFSET UNITYSDK_OFFSET(0x13ED8B50)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x13ED7AF0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GOLINEUPSELECT_OFFSET UNITYSDK_OFFSET(0x13ED8FD0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_INITCONFIG_OFFSET UNITYSDK_OFFSET(0x13ED8400)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONABYSSS2ROLECHALLENGESELECT_OFFSET UNITYSDK_OFFSET(0x13EDA110)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONBACKBTNCLICK_OFFSET UNITYSDK_OFFSET(0x13ED93C0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONBATTLERECORDBTNCLICK_OFFSET UNITYSDK_OFFSET(0x13ED9820)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONBEGINBATTLE_OFFSET UNITYSDK_OFFSET(0x13EDA770)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x13ED89D0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONDIFFICULTYTABCLICK_OFFSET UNITYSDK_OFFSET(0x13ED9C70)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONGETSELECTROLECONTEXT_OFFSET UNITYSDK_OFFSET(0x13EDA240)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x13ED8EA0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x13ED8AE0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONMAINBTNCLICK_OFFSET UNITYSDK_OFFSET(0x13ED9520)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONMONSTERINFOBTNCLICK_OFFSET UNITYSDK_OFFSET(0x13ED9640)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONOKBTNCLICK_OFFSET UNITYSDK_OFFSET(0x13ED8F80)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONREWARDINFOBTNCLICK_OFFSET UNITYSDK_OFFSET(0x13ED9A80)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x13ED8A60)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x13ED7B00)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x13ED82B0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHDIFFICULTYTABVIEW_OFFSET UNITYSDK_OFFSET(0x13EDAF40)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHINFOVIEW_OFFSET UNITYSDK_OFFSET(0x13ED9D50)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHLISTVIEW_OFFSET UNITYSDK_OFFSET(0x13EDAA60)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHREWARDINFOVIEW_OFFSET UNITYSDK_OFFSET(0x13EDACE0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0x13ED86F0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHVISIBLEVIEW_OFFSET UNITYSDK_OFFSET(0x13ED8B80)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_SETTABBTNACTIVE_OFFSET UNITYSDK_OFFSET(0x13EDB590)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_SHOWNEWBIE_OFFSET UNITYSDK_OFFSET(0x13EDB6F0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x13EDB970)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER__REFRESHDIFFICULTYTABVIEW_B__26_0_OFFSET UNITYSDK_OFFSET(0x13EDBAE0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x13EDBB80)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x13EDBC10)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x13EDBC40)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x13EDBCD0)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x13EDBD60)
#define MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x13EDBDF0)

namespace MoleMole
{
	inline static constexpr unsigned int UIAbyssS2RoleChallengeWidgetController_TypeDefinitionIndex = 69435;

	class UIAbyssS2RoleChallengeWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		::Class_2_22F360303C414CB0_1* _view; // 0x2B8
		::System::Func_2<::System::Int32, ::System::Boolean>* SpeciallCheckSlotClick; // 0x2C0
		::System::Int32 _entranceID; // 0x2C8
		::Class_2_E621E51D351EB960* _abyssModel; // 0x2D0
		::Class_2_E621E51D351EB960_1* _abyssS2Model; // 0x2D8
		::Class_2_47BEEACD66EA947F* _yorozuyaModel; // 0x2E0
		::Class_2_208CC9941471731A_535* _entranceConfig; // 0x2E8
		::Class_2_0A55B5A82A61DAFA_2* _currSelectQuestConfig; // 0x2F0
		::Class_2_14E7CE92E8A3183F* _currSelectDungeonConfig; // 0x2F8
		::Class_1_09621F974A776F22* _currDungeonData; // 0x300
		::System::Collections::Generic::List_1<::Class_1_09621F974A776F22*>* _dungeonDatas; // 0x308
		::MoleMole::UIGeneralBottomRewardInfoWidgetController* _rewardInfoWidget; // 0x310
		::MoleMole::UIAbyssS2RoleChallengeInfoWidgetController* _challengeInfoWidget; // 0x318
		::MoleMole::UIAbyssS2RoleChallengeListWidgetController* _challengeListWidget; // 0x320
		::System::Collections::Generic::List_1<::Class_1_7F489DAFAFC6BD02*>* _rewardDataList; // 0x328
		::System::Collections::Generic::List_1<::Class_1_C4CB11A2FD957208_Struct_2_98E057419FFAAB00>* _questRewardList; // 0x330
		::MoleMole::UIAbyssS2RoleChallengeContext* _context; // 0x338
		::System::Boolean _isListInit; // 0x340
		::MoleMole::UIAbyssS2RoleChallengeWidgetController_DifficultyType _currDifficulty; // 0x344

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_8E90989A26BC6232 get_HotSwitchRootLayerState()
		{
			return ((::Enum_3_8E90989A26BC6232(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void InitConfig()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_INITCONFIG_OFFSET))(this);
		}

		::System::Void OnOkBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONOKBTNCLICK_OFFSET))(this);
		}

		::System::Void OnBackBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONBACKBTNCLICK_OFFSET))(this);
		}

		::System::Void OnMainBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONMAINBTNCLICK_OFFSET))(this);
		}

		::System::Void OnMonsterInfoBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONMONSTERINFOBTNCLICK_OFFSET))(this);
		}

		::System::Void OnBattleRecordBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONBATTLERECORDBTNCLICK_OFFSET))(this);
		}

		::System::Void OnRewardInfoBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONREWARDINFOBTNCLICK_OFFSET))(this);
		}

		::System::Void OnDifficultyTabClick(::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONDIFFICULTYTABCLICK_OFFSET))(this, index);
		}

		::System::Void OnAbyssS2RoleChallengeSelect(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONABYSSS2ROLECHALLENGESELECT_OFFSET))(this, args);
		}

		::System::Void GoLineupSelect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GOLINEUPSELECT_OFFSET))(this);
		}

		::MoleMole::UIRoleSelectPageContext* OnGetSelectRoleContext(::System::Int32 selectIndex, ::Il2CppArray<::Class_2_1824EF69C8E376A3*>* currentSelected)
		{
			return ((::MoleMole::UIRoleSelectPageContext*(*)(::PVOID, ::System::Int32, ::Il2CppArray<::Class_2_1824EF69C8E376A3*>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONGETSELECTROLECONTEXT_OFFSET))(this, selectIndex, currentSelected);
		}

		::System::Void OnBeginBattle(::Class_1_E081FCEC8F87505A* data)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_E081FCEC8F87505A*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_ONBEGINBATTLE_OFFSET))(this, data);
		}

		::System::Void RefreshView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHVIEW_OFFSET))(this);
		}

		::System::Void RefreshRewardInfoView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHREWARDINFOVIEW_OFFSET))(this);
		}

		::System::Void RefreshDifficultyTabView(::MoleMole::UIAbyssS2RoleChallengeWidgetController_DifficultyType difficulty)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIAbyssS2RoleChallengeWidgetController_DifficultyType))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHDIFFICULTYTABVIEW_OFFSET))(this, difficulty);
		}

		::System::Void SetTabBtnActive()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_SETTABBTNACTIVE_OFFSET))(this);
		}

		::System::Void RefreshVisibleView(::System::Boolean isListOpen)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHVISIBLEVIEW_OFFSET))(this, isListOpen);
		}

		::System::Void RefreshInfoView(::Class_1_09621F974A776F22* data, ::MoleMole::UIAbyssS2RoleChallengeWidgetController_DifficultyType difficulty)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_09621F974A776F22*, ::MoleMole::UIAbyssS2RoleChallengeWidgetController_DifficultyType))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHINFOVIEW_OFFSET))(this, data, difficulty);
		}

		::System::Void RefreshListView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_REFRESHLISTVIEW_OFFSET))(this);
		}

		::System::Void ShowNewBie()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_SHOWNEWBIE_OFFSET))(this);
		}

		::System::Boolean get_IsChallengeListOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER_GET_ISCHALLENGELISTOPEN_OFFSET))(this);
		}

		::System::Boolean _RefreshDifficultyTabView_b__26_0(::System::Int32 index)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER__REFRESHDIFFICULTYTABVIEW_B__26_0_OFFSET))(this, index);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSS2ROLECHALLENGEWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
