#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_48D56DACBE4271BC;
class Class_1_F0E4E2848B1D52CE;
class Class_2_5F53453ACF8181EA;
class Class_2_CE3D9FA6CFDF456D;
namespace MoleMole { class UIControlReference; }

#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_BINDVIEW_OFFSET UNITYSDK_OFFSET(0x13ECBB80)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_CLEARCOUNTDOWN_OFFSET UNITYSDK_OFFSET(0x13ECC1F0)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x13ECBA70)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONSTAGECHANGE_OFFSET UNITYSDK_OFFSET(0x13ECBF00)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x13ECBB00)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x13ECB940)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_SETFILL_OFFSET UNITYSDK_OFFSET(0x13ECC370)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_STARTCOUNTDOWN_OFFSET UNITYSDK_OFFSET(0x13ECC180)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0x13ECC540)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x13ECC820)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x13ECC880)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x13ECC910)
#define MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x13ECC9A0)

namespace MoleMole
{
	inline static constexpr unsigned int UIABInLevelCountDownWidgetController_TypeDefinitionIndex = 53534;

	class UIABInLevelCountDownWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		::Class_2_5F53453ACF8181EA* _view; // 0x2B8
		::Class_1_48D56DACBE4271BC* _syncHelper; // 0x2C0
		::Class_2_CE3D9FA6CFDF456D* _data; // 0x2C8
		::Class_1_F0E4E2848B1D52CE* _viewModel; // 0x2D0
		::System::Single _countDownTime; // 0x2D8
		::System::Single _totalSec; // 0x2DC

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void BindView(::Class_1_F0E4E2848B1D52CE* viewModel)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_F0E4E2848B1D52CE*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_BINDVIEW_OFFSET))(this, viewModel);
		}

		::System::Void OnStageChange()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_ONSTAGECHANGE_OFFSET))(this);
		}

		::System::Void StartCountDown(::System::Int32 totalSec)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_STARTCOUNTDOWN_OFFSET))(this, totalSec);
		}

		::System::Void ClearCountDown(::System::Boolean needAnim)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_CLEARCOUNTDOWN_OFFSET))(this, needAnim);
		}

		::System::Void SetFill(::System::Single fill, ::System::Int32 colorIdx)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_SETFILL_OFFSET))(this, fill, colorIdx);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABINLEVELCOUNTDOWNWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}
	};
}
