#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIActivitySignInLastDayWidget.h"

class Class_0_16E4307DCC419505_36;
class Class_1_D375C91CCE5D3999;
class Class_2_D1919A47EDB7B54E;
class Class_3_AE02BC8285203464_18;
namespace MoleMole { class UIActivityLambGiftItemWidgetController; }
namespace MoleMole { class UIActivitySignInPopWindowController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }

#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_CANTAKETASKREWARD_OFFSET UNITYSDK_OFFSET(0x19201040)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_GETSEVENDAYREWARD_OFFSET UNITYSDK_OFFSET(0x192010D0)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x19200180)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONPREINPUTACTION_OFFSET UNITYSDK_OFFSET(0x19200D70)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x19200210)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x191FFD20)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x19200020)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_REFRESHLASTDAYINFO_OFFSET UNITYSDK_OFFSET(0x19200370)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_SETDAYDATA_OFFSET UNITYSDK_OFFSET(0x19200300)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_SETPOPCONTROLLER_OFFSET UNITYSDK_OFFSET(0x19200290)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x192014D0)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER__GETSEVENDAYREWARD_B__12_0_OFFSET UNITYSDK_OFFSET(0x19201530)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER__GETSEVENDAYREWARD_B__12_1_OFFSET UNITYSDK_OFFSET(0x19201540)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x19201610)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONPREINPUTACTION_OFFSET UNITYSDK_OFFSET(0x192016A0)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x19201750)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x192017E0)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x19201870)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_REFRESHLASTDAYINFO_OFFSET UNITYSDK_OFFSET(0x19201900)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_SETDAYDATA_OFFSET UNITYSDK_OFFSET(0x19201940)
#define MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_SETPOPCONTROLLER_OFFSET UNITYSDK_OFFSET(0x19201990)

namespace MoleMole
{
	inline static constexpr unsigned int UIActivitySignInSpecialRowV2WidgetController_TypeDefinitionIndex = 89712;

	class UIActivitySignInSpecialRowV2WidgetController : public ::MoleMole::UIActivitySignInLastDayWidget
	{
	public:
		// static const ::System::Int32 maxRewardCount = 0x2; // 0x0
		::Class_2_D1919A47EDB7B54E* _view; // 0x2C0
		::MoleMole::UIActivitySignInPopWindowController* signInPopController; // 0x2C8
		::Il2CppArray<::MoleMole::UIActivityLambGiftItemWidgetController*>* rewardIconArray; // 0x2D0
		::Class_1_D375C91CCE5D3999* activityData; // 0x2D8
		::Class_3_AE02BC8285203464_18* sevenDayTask; // 0x2E0
		::System::Boolean isTakingReward; // 0x2E8
		::System::Boolean useConsoleSettingV2; // 0x2E9

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void SetPopController(::MoleMole::UIActivitySignInPopWindowController* popController)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIActivitySignInPopWindowController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_SETPOPCONTROLLER_OFFSET))(this, popController);
		}

		::System::Void SetDayData(::Class_3_AE02BC8285203464_18* task, ::Class_1_D375C91CCE5D3999* activityBaseData)
		{
			return ((::System::Void(*)(::PVOID, ::Class_3_AE02BC8285203464_18*, ::Class_1_D375C91CCE5D3999*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_SETDAYDATA_OFFSET))(this, task, activityBaseData);
		}

		::System::Boolean OnPreInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_ONPREINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void GetSevenDayReward()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_GETSEVENDAYREWARD_OFFSET))(this);
		}

		::System::Void RefreshLastDayInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_REFRESHLASTDAYINFO_OFFSET))(this);
		}

		::System::Boolean CanTakeTaskReward()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER_CANTAKETASKREWARD_OFFSET))(this);
		}

		::System::Void _GetSevenDayReward_b__12_0(::Class_0_16E4307DCC419505_36* rspMsg)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_36*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER__GETSEVENDAYREWARD_B__12_0_OFFSET))(this, rspMsg);
		}

		::System::Void _GetSevenDayReward_b__12_1(::Class_0_16E4307DCC419505_36* errorMsg)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_36*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER__GETSEVENDAYREWARD_B__12_1_OFFSET))(this, errorMsg);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Boolean __base_OnPreInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONPREINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Void __base_RefreshLastDayInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_REFRESHLASTDAYINFO_OFFSET))(this);
		}

		::System::Void __base_SetDayData(::Class_3_AE02BC8285203464_18* P0, ::Class_1_D375C91CCE5D3999* P1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_3_AE02BC8285203464_18*, ::Class_1_D375C91CCE5D3999*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_SETDAYDATA_OFFSET))(this, P0, P1);
		}

		::System::Void __base_SetPopController(::MoleMole::UIActivitySignInPopWindowController* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIActivitySignInPopWindowController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYSIGNINSPECIALROWV2WIDGETCONTROLLER___BASE_SETPOPCONTROLLER_OFFSET))(this, P0);
		}
	};
}
