#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/ScrollViewItemWidgetController.h"
#include "unitysdk/Struct_2_575273D27F02957E.h"

class Class_2_B7672EEAD6180671;
class Class_2_F2AFAE0447B8569C;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace UnityEngine::UI::Extension { class UITabButton; }

#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_GETTABBUTTON_OFFSET UNITYSDK_OFFSET(0x13EE1DB0)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_GET__VIEWMODEL_OFFSET UNITYSDK_OFFSET(0x13EE1B80)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONCREATEVIEWMODEL_OFFSET UNITYSDK_OFFSET(0x13EE1BF0)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONITEMSELECT_OFFSET UNITYSDK_OFFSET(0x13EE1EB0)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x13EE1E50)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0x13EE1CB0)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x13EE1FB0)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_SETLEVELDATA_OFFSET UNITYSDK_OFFSET(0x13EE1D00)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x13EE2070)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONCREATEVIEWMODEL_OFFSET UNITYSDK_OFFSET(0x13EE2080)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONITEMSELECT_OFFSET UNITYSDK_OFFSET(0x13EE2120)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x13EE21B0)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0x13EE2240)
#define MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x13EE22E0)

namespace MoleMole
{
	inline static constexpr unsigned int UIActivityFight_LevelTabWidgetController_TypeDefinitionIndex = 70536;

	class UIActivityFight_LevelTabWidgetController : public ::MoleMole::ScrollViewItemWidgetController
	{
	public:
		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::Class_2_B7672EEAD6180671* get__viewModel()
		{
			return ((::Class_2_B7672EEAD6180671*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_GET__VIEWMODEL_OFFSET))(this);
		}

		::System::Void OnCreateViewModel(::Struct_2_575273D27F02957E& binderInfo, ::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_575273D27F02957E&, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONCREATEVIEWMODEL_OFFSET))(this, binderInfo, controlReference);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void SetLevelData(::Class_2_F2AFAE0447B8569C* levelData)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_F2AFAE0447B8569C*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_SETLEVELDATA_OFFSET))(this, levelData);
		}

		::UnityEngine::UI::Extension::UITabButton* GetTabButton()
		{
			return ((::UnityEngine::UI::Extension::UITabButton*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_GETTABBUTTON_OFFSET))(this);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void OnItemSelect(::System::Boolean isSelect)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONITEMSELECT_OFFSET))(this, isSelect);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnCreateViewModel(::Struct_2_575273D27F02957E& P0, ::MoleMole::UIControlReference* P1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_575273D27F02957E&, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONCREATEVIEWMODEL_OFFSET))(this, P0, P1);
		}

		::System::Void __base_OnItemSelect(::System::Boolean P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONITEMSELECT_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYFIGHT_LEVELTABWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}
	};
}
