#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIAllroundGeneralTutorialPopWindowController_LogicDelegate_SwitchCurIdReason.h"
#include "unitysdk/System/Nullable_1.h"
#include "unitysdk/System/Object.h"

class Class_1_135463D7458ED59A_Class_1_9E89B2D44593C915;
class Class_1_E9529ED64113E4E9;
class Class_2_79AE422BA06F6D26_126;
namespace MoleMole { class UIAllroundGeneralTutorialDialogContenxt; }
namespace MoleMole { class UIBaseController; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class Action; }
namespace System { class String; }
namespace UnityEngine::UI { class RawImage; }

#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_BIND_OFFSET UNITYSDK_OFFSET(0x192EA890)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_CLOSE_OFFSET UNITYSDK_OFFSET(0x192EB8B0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_DOOKCALLBACK_OFFSET UNITYSDK_OFFSET(0x192EB850)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_GETCURPAGE_OFFSET UNITYSDK_OFFSET(0x192ED420)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_GETTYPETITLETEX_OFFSET UNITYSDK_OFFSET(0x192EBF70)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_GET_ISOPEN_OFFSET UNITYSDK_OFFSET(0x192EA690)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_HASNEXT_OFFSET UNITYSDK_OFFSET(0x192ED360)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_HASPREV_OFFSET UNITYSDK_OFFSET(0x192ED3C0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_INITTITLETEXT_OFFSET UNITYSDK_OFFSET(0x192EBE20)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_MASKCLOSE_OFFSET UNITYSDK_OFFSET(0x192EBC90)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONCLOSEBTNCLICKED_OFFSET UNITYSDK_OFFSET(0x192ED1E0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x192EBAF0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONNEXTPRESSED_OFFSET UNITYSDK_OFFSET(0x192ED160)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONPREPRESSED_OFFSET UNITYSDK_OFFSET(0x192ED0F0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONRENDERSTATESHOW_OFFSET UNITYSDK_OFFSET(0x192EBCF0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONSKILLTIPSBTNCLICKED_OFFSET UNITYSDK_OFFSET(0x192ED640)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONTUTORIALBTNCLICKED_OFFSET UNITYSDK_OFFSET(0x192ED480)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x192EB540)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x192EBA70)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x192EA700)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x192EACC0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_REFRESHPAGE_OFFSET UNITYSDK_OFFSET(0x192EC2D0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_REFRESHREACHEND_OFFSET UNITYSDK_OFFSET(0x192ED020)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETCANCLOSEONLYREACHEND_OFFSET UNITYSDK_OFFSET(0x192EA640)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETCONTROLLER_OFFSET UNITYSDK_OFFSET(0x192EA5A0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETDISABLENEXTBTNWHENREACHEND_OFFSET UNITYSDK_OFFSET(0x192EA5F0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETOKCLICK_OFFSET UNITYSDK_OFFSET(0x192EA6B0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETVIEW_OFFSET UNITYSDK_OFFSET(0x192EA550)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SET_ISOPEN_OFFSET UNITYSDK_OFFSET(0x192EA6A0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_TYPESUBTITLETEX_OFFSET UNITYSDK_OFFSET(0x192EC120)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE__BIND_B__49_0_OFFSET UNITYSDK_OFFSET(0x192ED7A0)
#define MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE__CTOR_OFFSET UNITYSDK_OFFSET(0x192ED790)

namespace MoleMole
{
	inline static constexpr unsigned int UIAllroundGeneralTutorialPopWindowController_LogicDelegate_TypeDefinitionIndex = 52173;

	class UIAllroundGeneralTutorialPopWindowController_LogicDelegate : public ::System::Object
	{
	public:
		// static const ::System::String* closeBtnAnim; // 0x0
		::UnityEngine::UI::RawImage* videoRawImg; // 0x10
		::MoleMole::UIBaseController* _controller; // 0x18
		::MoleMole::UIAllroundGeneralTutorialDialogContenxt* _context; // 0x20
		::System::Action* _onTutorialBtnClickCallback; // 0x28
		::Class_1_135463D7458ED59A_Class_1_9E89B2D44593C915* popupGroupData; // 0x30
		::System::String* lastResPath; // 0x38
		::Class_2_79AE422BA06F6D26_126* _view; // 0x40
		::Class_1_E9529ED64113E4E9* _playerHelper; // 0x48
		::System::Action* okBtnCb; // 0x50
		::System::Boolean _canCloseOnlyReachEnd; // 0x58
		::System::Boolean _disableNextBtnWhenReachEnd; // 0x59
		::System::Boolean _hasNext; // 0x5A
		::System::Boolean _hasPrev; // 0x5B
		::System::Int32 curId; // 0x5C
		::System::Int32 _count; // 0x60
		::System::Int32 trainQuestID; // 0x64
		::System::Boolean _hasReachEnd; // 0x68
		::System::Boolean _canShowBottomTips; // 0x69
		::System::Boolean _hasPauseGame; // 0x6A
		::System::Boolean _isOpen_k__BackingField; // 0x6B

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE__CTOR_OFFSET))(this);
		}

		::System::Void SetView(::Class_2_79AE422BA06F6D26_126* view)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_79AE422BA06F6D26_126*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETVIEW_OFFSET))(this, view);
		}

		::System::Void SetController(::MoleMole::UIBaseController* controller)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIBaseController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETCONTROLLER_OFFSET))(this, controller);
		}

		::System::Void SetDisableNextBtnWhenReachEnd(::System::Boolean state)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETDISABLENEXTBTNWHENREACHEND_OFFSET))(this, state);
		}

		::System::Void SetCanCloseOnlyReachEnd(::System::Boolean state)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETCANCLOSEONLYREACHEND_OFFSET))(this, state);
		}

		::System::Boolean get_isOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_GET_ISOPEN_OFFSET))(this);
		}

		::System::Void set_isOpen(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SET_ISOPEN_OFFSET))(this, value);
		}

		::System::Void SetOkClick(::System::Action* callback)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_SETOKCLICK_OFFSET))(this, callback);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void Close()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_CLOSE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Nullable_1<::System::Boolean> OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Nullable_1<::System::Boolean>(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void MaskClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_MASKCLOSE_OFFSET))(this);
		}

		::System::Void OnRenderStateShow()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONRENDERSTATESHOW_OFFSET))(this);
		}

		::System::Void InitTitleText()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_INITTITLETEXT_OFFSET))(this);
		}

		::System::String* GetTypeTitleTex()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_GETTYPETITLETEX_OFFSET))(this);
		}

		::System::String* TypeSubTitleTex()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_TYPESUBTITLETEX_OFFSET))(this);
		}

		::System::Void RefreshPage(::MoleMole::UIAllroundGeneralTutorialPopWindowController_LogicDelegate_SwitchCurIdReason switchCurIdReason)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIAllroundGeneralTutorialPopWindowController_LogicDelegate_SwitchCurIdReason))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_REFRESHPAGE_OFFSET))(this, switchCurIdReason);
		}

		::System::Void RefreshReachEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_REFRESHREACHEND_OFFSET))(this);
		}

		::System::Void OnPrePressed()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONPREPRESSED_OFFSET))(this);
		}

		::System::Void OnNextPressed()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONNEXTPRESSED_OFFSET))(this);
		}

		::System::Boolean HasNext()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_HASNEXT_OFFSET))(this);
		}

		::System::Boolean HasPrev()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_HASPREV_OFFSET))(this);
		}

		::System::Int32 GetCurPage()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_GETCURPAGE_OFFSET))(this);
		}

		::System::Void OnCloseBtnClicked()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONCLOSEBTNCLICKED_OFFSET))(this);
		}

		::System::Void Bind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_BIND_OFFSET))(this);
		}

		::System::Void DoOkCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_DOOKCALLBACK_OFFSET))(this);
		}

		::System::Void OnTutorialBtnClicked()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONTUTORIALBTNCLICKED_OFFSET))(this);
		}

		::System::Void OnSkillTipsBtnClicked()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE_ONSKILLTIPSBTNCLICKED_OFFSET))(this);
		}

		::System::Void _Bind_b__49_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIALLROUNDGENERALTUTORIALPOPWINDOWCONTROLLER_LOGICDELEGATE__BIND_B__49_0_OFFSET))(this);
		}
	};
}
