#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Foundation/Coroutine/CoroutineHandle.h"
#include "unitysdk/MoleMole/UIInLevelCommonSkillButtonBaseController.h"

class Class_2_60638234271CCDB8;
namespace MoleMole { class EtherEyesSubSystem; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIEtherEyesSkillButtonEffectCircleOneWidgetController; }
namespace MoleMole { class UIEtherEyesSkillButtonEffectCircleThreeWidgetController; }
namespace MoleMole { class UIEtherEyesSkillButtonEffectCircleTwoWidgetController; }
namespace System { class EventArgs; }
namespace UnityEngine { class Material; }

#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_CLEARMATERIALCACHE_OFFSET UNITYSDK_OFFSET(0x15EE3F70)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_CLOSECOMMONBUTTON_OFFSET UNITYSDK_OFFSET(0x15EE56D0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_GET_NEEDCACHEBYBATTLEHUD_OFFSET UNITYSDK_OFFSET(0x15EE3E60)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_INITMATERIALCACHE_OFFSET UNITYSDK_OFFSET(0x15EE4EC0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_INITPLAYBTN_OFFSET UNITYSDK_OFFSET(0x15EE49C0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ISBTNSHOWUI_OFFSET UNITYSDK_OFFSET(0x15EE5BC0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ISBTNWORKABLE_OFFSET UNITYSDK_OFFSET(0x15EE5AE0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONACTIVEETHEREYES_OFFSET UNITYSDK_OFFSET(0x15EE5F90)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONBUTTONCLICK_OFFSET UNITYSDK_OFFSET(0x15EE58A0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15EE3E70)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0x15EE4740)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONINITLISTENINPUTTYPE_OFFSET UNITYSDK_OFFSET(0x15EE5970)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONRECOVERFROMCACHE_OFFSET UNITYSDK_OFFSET(0x15EE5120)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0x15EE46F0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x15EE47A0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x15EE3F00)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x15EE4160)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x15EE45C0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_PLAYCOMMONBUTTONFADEINANIM_OFFSET UNITYSDK_OFFSET(0x15EE5590)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHBUTTONHIGHLIGHT_OFFSET UNITYSDK_OFFSET(0x15EE6840)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHBUTTONICON_OFFSET UNITYSDK_OFFSET(0x15EE4460)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHBUTTONSTATE_OFFSET UNITYSDK_OFFSET(0x15EE5CA0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHHIGHLIGHTEFF_OFFSET UNITYSDK_OFFSET(0x15EE5D20)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHMATERIAL_OFFSET UNITYSDK_OFFSET(0x15EE41C0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0x15EE4880)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_TRYCACHESUBSYSTEM_OFFSET UNITYSDK_OFFSET(0x15EE5090)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0x15EE4830)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x15EE68C0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__ONACTIVEETHEREYES_B__20_0_OFFSET UNITYSDK_OFFSET(0x15EE6940)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__ONACTIVEETHEREYES_B__20_1_OFFSET UNITYSDK_OFFSET(0x15EE6B10)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__ONUIOPEN_B__6_0_OFFSET UNITYSDK_OFFSET(0x15EE6920)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_CLOSECOMMONBUTTON_OFFSET UNITYSDK_OFFSET(0x15EE6CE0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_INITPLAYBTN_OFFSET UNITYSDK_OFFSET(0x15EE6CF0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ISBTNSHOWUI_OFFSET UNITYSDK_OFFSET(0x15EE6D00)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ISBTNWORKABLE_OFFSET UNITYSDK_OFFSET(0x15EE6DB0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONBUTTONCLICK_OFFSET UNITYSDK_OFFSET(0x15EE6E60)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15EE6EF0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0x15EE6F80)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONINITLISTENINPUTTYPE_OFFSET UNITYSDK_OFFSET(0x15EE7010)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONRECOVERFROMCACHE_OFFSET UNITYSDK_OFFSET(0x15EE70A0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0x15EE7130)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x15EE7140)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x15EE7200)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x15EE7210)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x15EE7220)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_PLAYCOMMONBUTTONFADEINANIM_OFFSET UNITYSDK_OFFSET(0x15EE7230)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_REFRESHBUTTONSTATE_OFFSET UNITYSDK_OFFSET(0x15EE72C0)
#define MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___N__0_OFFSET UNITYSDK_OFFSET(0x15EE6930)

namespace MoleMole
{
	inline static constexpr unsigned int UIEtherEyesSkillBtnChildWindowController_TypeDefinitionIndex = 58744;

	class UIEtherEyesSkillBtnChildWindowController : public ::MoleMole::UIInLevelCommonSkillButtonBaseController
	{
	public:
		::Class_2_60638234271CCDB8* _view; // 0x380
		::MoleMole::EtherEyesSubSystem* _etherEyesSubSystem; // 0x388
		::UnityEngine::Material* _noHighlightMaterial; // 0x390
		::System::Boolean _isMatDirty; // 0x398
		::System::Boolean _isButtonHighlight; // 0x399
		::System::Boolean _isEtherEyesActive; // 0x39A
		::Foundation::Coroutine::CoroutineHandle _animCoroutineHandle; // 0x39C
		::MoleMole::UIEtherEyesSkillButtonEffectCircleOneWidgetController* _effCircle01; // 0x3A0
		::MoleMole::UIEtherEyesSkillButtonEffectCircleTwoWidgetController* _effCircle02; // 0x3A8
		::MoleMole::UIEtherEyesSkillButtonEffectCircleThreeWidgetController* _effCircle03; // 0x3B0
		::Foundation::Coroutine::CoroutineHandle _effCoroutineHandle01; // 0x3B8
		::Foundation::Coroutine::CoroutineHandle _effCoroutineHandle02; // 0x3BC

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Boolean get_NeedCacheByBattleHUD()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_GET_NEEDCACHEBYBATTLEHUD_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONUICLOSE_OFFSET))(this);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Void InitPlayBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_INITPLAYBTN_OFFSET))(this);
		}

		::System::Void OnRecoverFromCache()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONRECOVERFROMCACHE_OFFSET))(this);
		}

		::System::Void PlayCommonButtonFadeInAnim()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_PLAYCOMMONBUTTONFADEINANIM_OFFSET))(this);
		}

		::System::Void CloseCommonButton(::System::Boolean checkCache)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_CLOSECOMMONBUTTON_OFFSET))(this, checkCache);
		}

		::System::Void OnButtonClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONBUTTONCLICK_OFFSET))(this);
		}

		::System::Void OnInitListenInputType()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONINITLISTENINPUTTYPE_OFFSET))(this);
		}

		::System::Boolean IsBtnWorkable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ISBTNWORKABLE_OFFSET))(this);
		}

		::System::Boolean IsBtnShowUI()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ISBTNSHOWUI_OFFSET))(this);
		}

		::System::Void RefreshButtonState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHBUTTONSTATE_OFFSET))(this);
		}

		::System::Void OnActiveEtherEyes()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_ONACTIVEETHEREYES_OFFSET))(this);
		}

		::System::Void RefreshView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHVIEW_OFFSET))(this);
		}

		::System::Void TryCacheSubSystem()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_TRYCACHESUBSYSTEM_OFFSET))(this);
		}

		::System::Void RefreshButtonHighlight()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHBUTTONHIGHLIGHT_OFFSET))(this);
		}

		::System::Void RefreshButtonIcon()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHBUTTONICON_OFFSET))(this);
		}

		::System::Void InitMaterialCache()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_INITMATERIALCACHE_OFFSET))(this);
		}

		::System::Void RefreshMaterial()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHMATERIAL_OFFSET))(this);
		}

		::System::Void ClearMaterialCache()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_CLEARMATERIALCACHE_OFFSET))(this);
		}

		::System::Void RefreshHighlightEff()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER_REFRESHHIGHLIGHTEFF_OFFSET))(this);
		}

		::System::Void _OnUIOpen_b__6_0(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__ONUIOPEN_B__6_0_OFFSET))(this, args);
		}

		::System::Void __n__0(::System::Boolean checkCache)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___N__0_OFFSET))(this, checkCache);
		}

		::System::Void _OnActiveEtherEyes_b__20_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__ONACTIVEETHEREYES_B__20_0_OFFSET))(this);
		}

		::System::Void _OnActiveEtherEyes_b__20_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER__ONACTIVEETHEREYES_B__20_1_OFFSET))(this);
		}

		::System::Void __base_CloseCommonButton(::System::Boolean P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_CLOSECOMMONBUTTON_OFFSET))(this, P0);
		}

		::System::Void __base_InitPlayBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_INITPLAYBTN_OFFSET))(this);
		}

		::System::Boolean __base_IsBtnShowUI()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ISBTNSHOWUI_OFFSET))(this);
		}

		::System::Boolean __base_IsBtnWorkable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ISBTNWORKABLE_OFFSET))(this);
		}

		::System::Void __base_OnButtonClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONBUTTONCLICK_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Void __base_OnInitListenInputType()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONINITLISTENINPUTTYPE_OFFSET))(this);
		}

		::System::Void __base_OnRecoverFromCache()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONRECOVERFROMCACHE_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Void __base_PlayCommonButtonFadeInAnim()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_PLAYCOMMONBUTTONFADEINANIM_OFFSET))(this);
		}

		::System::Void __base_RefreshButtonState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIETHEREYESSKILLBTNCHILDWINDOWCONTROLLER___BASE_REFRESHBUTTONSTATE_OFFSET))(this);
		}
	};
}
