#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/MoleMole/UIWindowController.h"

class Class_2_4CF6F758B26B2E9F;
class Class_2_60638234271CCDB8_71;
class Class_2_98B938A2E3D3C17C;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIFishQuickSelectPopWindowContext; }
namespace MoleMole { class UIGeneralFilterGroupRowWidgetController; }
namespace MoleMole { class UIGeneralFilterItemRowWidgetController; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x166C8F60)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTCANSHOW_OFFSET UNITYSDK_OFFSET(0x166CB1B0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTCANTSHOW_OFFSET UNITYSDK_OFFSET(0x166CB210)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTNORMAL_OFFSET UNITYSDK_OFFSET(0x166CB0F0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTSPECIAL_OFFSET UNITYSDK_OFFSET(0x166CB150)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECT_OFFSET UNITYSDK_OFFSET(0x166CB400)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x166C9D70)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONOKBTNCLICK_OFFSET UNITYSDK_OFFSET(0x166CB490)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONRESETBTNCLICK_OFFSET UNITYSDK_OFFSET(0x166CB630)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x166C9E00)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x166C8F70)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x166C9270)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_REFRESHITEMTYPEROW_OFFSET UNITYSDK_OFFSET(0x166C9E70)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_REFRESHNUM_OFFSET UNITYSDK_OFFSET(0x166CAAE0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0x166C9480)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_SETQUICKSELECTDATA_OFFSET UNITYSDK_OFFSET(0x166CAEF0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_SETSELECTSTARLIST_OFFSET UNITYSDK_OFFSET(0x166CB270)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x166CB6F0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_0_OFFSET UNITYSDK_OFFSET(0x166CB780)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_1_OFFSET UNITYSDK_OFFSET(0x166CB7B0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_2_OFFSET UNITYSDK_OFFSET(0x166CB7E0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_3_OFFSET UNITYSDK_OFFSET(0x166CB840)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_4_OFFSET UNITYSDK_OFFSET(0x166CB8A0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_5_OFFSET UNITYSDK_OFFSET(0x166CB900)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_6_OFFSET UNITYSDK_OFFSET(0x166CB960)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_7_OFFSET UNITYSDK_OFFSET(0x166CB990)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x166CB9C0)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x166CBA50)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x166CBA60)
#define MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x166CBA70)

namespace MoleMole
{
	inline static constexpr unsigned int UIFishQuickSelectPopWindowController_TypeDefinitionIndex = 50715;

	class UIFishQuickSelectPopWindowController : public ::MoleMole::UIWindowController
	{
	public:
		::Class_2_60638234271CCDB8_71* _view; // 0x318
		::Class_2_98B938A2E3D3C17C* _model; // 0x320
		::MoleMole::UIFishQuickSelectPopWindowContext* _context; // 0x328
		::MoleMole::UIGeneralFilterGroupRowWidgetController* _itemTypeWidgetColor; // 0x330
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetNormal; // 0x338
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetSpecial; // 0x340
		::MoleMole::UIGeneralFilterGroupRowWidgetController* _itemTypeWidgetStar; // 0x348
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetStar1; // 0x350
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetStar2; // 0x358
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetStar3; // 0x360
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetStar4; // 0x368
		::MoleMole::UIGeneralFilterGroupRowWidgetController* _itemTypeWidgetShowType; // 0x370
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetCanShow; // 0x378
		::MoleMole::UIGeneralFilterItemRowWidgetController* _itemTypeRowWidgetCantShow; // 0x380
		::System::Boolean _isSelectNormal; // 0x388
		::System::Boolean _isSelectSpecial; // 0x389
		::System::Collections::Generic::List_1<::System::Boolean>* _isSelectStarList; // 0x390
		::System::Boolean _isSelectCanShow; // 0x398
		::System::Boolean _isSelectCantShow; // 0x399
		::Class_2_4CF6F758B26B2E9F* _quickSelectData; // 0x3A0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void RefreshView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_REFRESHVIEW_OFFSET))(this);
		}

		::System::Void RefreshItemTypeRow()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_REFRESHITEMTYPEROW_OFFSET))(this);
		}

		::System::Void SetQuickSelectData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_SETQUICKSELECTDATA_OFFSET))(this);
		}

		::System::Void RefreshNum()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_REFRESHNUM_OFFSET))(this);
		}

		::System::Void OnOkBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONOKBTNCLICK_OFFSET))(this);
		}

		::System::Boolean IsSelectNormal()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTNORMAL_OFFSET))(this);
		}

		::System::Boolean IsSelectSpecial()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTSPECIAL_OFFSET))(this);
		}

		::System::Void SetSelectStarList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_SETSELECTSTARLIST_OFFSET))(this);
		}

		::System::Boolean IsSelectCanShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTCANSHOW_OFFSET))(this);
		}

		::System::Boolean IsSelectCantShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECTCANTSHOW_OFFSET))(this);
		}

		::System::Boolean IsSelect()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ISSELECT_OFFSET))(this);
		}

		::System::Void OnResetBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER_ONRESETBTNCLICK_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_0_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_1_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_2_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_3_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_4_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_5()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_5_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_6()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_6_OFFSET))(this);
		}

		::System::Void _RefreshView_b__7_7()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER__REFRESHVIEW_B__7_7_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIFISHQUICKSELECTPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
