#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/DropDownItemWidgetController.h"

class Class_2_061CBD681B3A898B;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralDropdownOptionContext; }
namespace UnityEngine::UI::Extension { class UITabButton; }

#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_GETUITABBUTTON_OFFSET UNITYSDK_OFFSET(0x15A1FED0)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONCLICKDELETE_OFFSET UNITYSDK_OFFSET(0x15A20040)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15A1FF30)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x15A1FFC0)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x15A1F9D0)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x15A1FA30)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_SETACCOUNT_OFFSET UNITYSDK_OFFSET(0x15A1FC70)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_SETICON_OFFSET UNITYSDK_OFFSET(0x15A1FD00)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_SETTIME_OFFSET UNITYSDK_OFFSET(0x15A1FD80)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x15A200E0)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_GETUITABBUTTON_OFFSET UNITYSDK_OFFSET(0x15A20140)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15A201D0)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x15A20260)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x15A202F0)
#define MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x15A20380)

namespace MoleMole
{
	inline static constexpr unsigned int UIGeneralLoginDropDownBoxRowWidgetController_TypeDefinitionIndex = 48258;

	class UIGeneralLoginDropDownBoxRowWidgetController : public ::MoleMole::DropDownItemWidgetController
	{
	public:
		::Class_2_061CBD681B3A898B* _view; // 0x2C8
		::MoleMole::UIGeneralDropdownOptionContext* context; // 0x2D0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::UnityEngine::UI::Extension::UITabButton* GetUITabButton()
		{
			return ((::UnityEngine::UI::Extension::UITabButton*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_GETUITABBUTTON_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void SetIcon()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_SETICON_OFFSET))(this);
		}

		::System::Void SetAccount()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_SETACCOUNT_OFFSET))(this);
		}

		::System::Void SetTime()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_SETTIME_OFFSET))(this);
		}

		::System::Void OnClickDelete()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER_ONCLICKDELETE_OFFSET))(this);
		}

		::UnityEngine::UI::Extension::UITabButton* __base_GetUITabButton()
		{
			return ((::UnityEngine::UI::Extension::UITabButton*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_GETUITABBUTTON_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERALLOGINDROPDOWNBOXROWWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
