#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_2_79F6D62CE30E3F8E_45;
class Class_2_B4378B46E0020E85;
class MonoUITableScrollV2;
namespace MoleMole { class MonoGamepadModule; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIHollowCardOptionsDialogContext; }
namespace System { class Action; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class Transform; }
namespace UnityEngine::UI::Extension { class UILocalizationText; }

#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_CARDREWARDSINGLESELECTMODULE_OFFSET UNITYSDK_OFFSET(0x19FECAE0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_CARDREWARD_OFFSET UNITYSDK_OFFSET(0x19FECA20)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_GIVEUP_OFFSET UNITYSDK_OFFSET(0x19FECA70)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_REWARDCONFRIMTEXT_OFFSET UNITYSDK_OFFSET(0x19FECAC0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_REWARDCONTENT_OFFSET UNITYSDK_OFFSET(0x19FECAA0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_SCROLLVIEW_OFFSET UNITYSDK_OFFSET(0x19FECA00)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_SHOWCOMBINEBTN_OFFSET UNITYSDK_OFFSET(0x19FECA50)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_INITGAMEPAD_OFFSET UNITYSDK_OFFSET(0x19FED3D0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_INITGIVETIPS_OFFSET UNITYSDK_OFFSET(0x19FED020)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONCOMBINEBTNCLICK_OFFSET UNITYSDK_OFFSET(0x19FECDF0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x19FECF10)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONGIVEBTNCLICK_OFFSET UNITYSDK_OFFSET(0x19FECD40)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x19FECFA0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x19FECB00)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x19FECEA0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_REGISTERCOMBINEBTCALLBACK_OFFSET UNITYSDK_OFFSET(0x19FECE50)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_REGISTERGIVEBTNCALLBACK_OFFSET UNITYSDK_OFFSET(0x19FECDA0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x19FEDDB0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x19FEDE10)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x19FEDEA0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x19FEDF30)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x19FEDFC0)

namespace MoleMole
{
	inline static constexpr unsigned int UIHollowCardOptionsRewardPanelWidgetController_TypeDefinitionIndex = 76272;

	class UIHollowCardOptionsRewardPanelWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		::Class_2_79F6D62CE30E3F8E_45* _view; // 0x2C0
		::System::Action* _onGiveUpAction; // 0x2C8
		::System::Action* _onCombineBtnClick; // 0x2D0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::MonoUITableScrollV2* get_ScrollView()
		{
			return ((::MonoUITableScrollV2*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_SCROLLVIEW_OFFSET))(this);
		}

		::UnityEngine::GameObject* get_CardReward()
		{
			return ((::UnityEngine::GameObject*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_CARDREWARD_OFFSET))(this);
		}

		::Class_2_B4378B46E0020E85* get_ShowCombineBtn()
		{
			return ((::Class_2_B4378B46E0020E85*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_SHOWCOMBINEBTN_OFFSET))(this);
		}

		::Class_2_B4378B46E0020E85* get_GiveUp()
		{
			return ((::Class_2_B4378B46E0020E85*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_GIVEUP_OFFSET))(this);
		}

		::UnityEngine::Transform* get_RewardContent()
		{
			return ((::UnityEngine::Transform*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_REWARDCONTENT_OFFSET))(this);
		}

		::UnityEngine::UI::Extension::UILocalizationText* get_RewardConfrimText()
		{
			return ((::UnityEngine::UI::Extension::UILocalizationText*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_REWARDCONFRIMTEXT_OFFSET))(this);
		}

		::MoleMole::MonoGamepadModule* get_CardRewardSingleSelectModule()
		{
			return ((::MoleMole::MonoGamepadModule*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_GET_CARDREWARDSINGLESELECTMODULE_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnGiveBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONGIVEBTNCLICK_OFFSET))(this);
		}

		::System::Void RegisterGiveBtnCallback(::System::Action* action)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_REGISTERGIVEBTNCALLBACK_OFFSET))(this, action);
		}

		::System::Void OnCombineBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONCOMBINEBTNCLICK_OFFSET))(this);
		}

		::System::Void RegisterCombineBtCallback(::System::Action* action)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_REGISTERCOMBINEBTCALLBACK_OFFSET))(this, action);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void InitGiveTips(::MoleMole::UIHollowCardOptionsDialogContext* dialogContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIHollowCardOptionsDialogContext*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_INITGIVETIPS_OFFSET))(this, dialogContext);
		}

		::System::Void InitGamePad(::MoleMole::UIHollowCardOptionsDialogContext* dialogContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIHollowCardOptionsDialogContext*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER_INITGAMEPAD_OFFSET))(this, dialogContext);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSREWARDPANELWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
