#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Cysharp/Threading/Tasks/UniTask.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Enum_3_8E90989A26BC6232.h"
#include "unitysdk/Enum_3_DBF2701137F18AA6.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIHollowCardOptionsBasePopWindowController.h"
#include "unitysdk/System/Collections/Generic/KeyValuePair_2.h"

class Class_1_0E5778BB52E10271;
class Class_1_4F9417780723166C;
class Class_1_661077F66F5DB866;
class Class_2_60638234271CCDB8_11;
namespace MoleMole { class HollowCardCombineConfig; }
namespace MoleMole { class UIAbyssS2InfoBtnWidgetController; }
namespace MoleMole { class UIAbyssTabButtonWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralToggleWidgetControllerWithModel; }
namespace MoleMole { class UIHollowCardOptionsAbyssS2DialogPopWindowController_CombineAnimationHelper; }
namespace MoleMole { class UIHollowCardOptionsDialogContext; }
namespace MoleMole { class UIHollowCardOptionsRelicPanelWidgetController; }
namespace System { class Action; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace System::Threading { class CancellationTokenSource; }

#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_CREATEHOLLOWCARDSELECTEDRESULT_OFFSET UNITYSDK_OFFSET(0x19FE9A00)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_CREATESELECTEDRESULT_OFFSET UNITYSDK_OFFSET(0x19FE9940)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GETSELECTCOUNT_OFFSET UNITYSDK_OFFSET(0x19FE8280)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET UNITYSDK_OFFSET(0x19FE6230)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET_RELICPANEL_OFFSET UNITYSDK_OFFSET(0x19FE6360)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x19FE6220)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET__ALLITEMLIST_OFFSET UNITYSDK_OFFSET(0x19FE6240)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INITBRANCHDATA_OFFSET UNITYSDK_OFFSET(0x19FE4090)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INITREFRESHBUTTON_OFFSET UNITYSDK_OFFSET(0x19FE7A30)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INITSELECTGAMEPAD_OFFSET UNITYSDK_OFFSET(0x19FE5650)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INRELICUPDATE_OFFSET UNITYSDK_OFFSET(0x19FE7470)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_MASKCLOSE_OFFSET UNITYSDK_OFFSET(0x19FE66C0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCLICKCONFIRM_OFFSET UNITYSDK_OFFSET(0x19FE97D0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCLICKITEM_OFFSET UNITYSDK_OFFSET(0x19FE8A60)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCLICKREFRESH_OFFSET UNITYSDK_OFFSET(0x19FE9330)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCONFIRM_OFFSET UNITYSDK_OFFSET(0x19FE99B0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x19FE6370)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x19FE7100)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x19FE62B0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONTABGROUPCLICK_OFFSET UNITYSDK_OFFSET(0x19FE5990)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x19FE7070)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x19FE6840)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x19FE69E0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_PLAYCLOSEANIM_OFFSET UNITYSDK_OFFSET(0x19FE6F70)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_PLAYITEMRELICUPGRADEANIM_OFFSET UNITYSDK_OFFSET(0x19FE9E40)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_PLAYVIEWREFRESH_OFFSET UNITYSDK_OFFSET(0x19FE9730)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHCONFIRM_OFFSET UNITYSDK_OFFSET(0x19FE55E0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHINFOTASK_OFFSET UNITYSDK_OFFSET(0x19FE95F0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHLIST_OFFSET UNITYSDK_OFFSET(0x19FE7690)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHROLETABGROUPBYINDEX_OFFSET UNITYSDK_OFFSET(0x19FE56B0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHROLETABGROUP_OFFSET UNITYSDK_OFFSET(0x19FE4C60)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHROLETAB_OFFSET UNITYSDK_OFFSET(0x19FE5750)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTABGROUPLIST_OFFSET UNITYSDK_OFFSET(0x19FE59E0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTASK_OFFSET UNITYSDK_OFFSET(0x19FE9550)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTIPS_OFFSET UNITYSDK_OFFSET(0x19FE51B0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTOGGLE_OFFSET UNITYSDK_OFFSET(0x19FE4FB0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_RESETCLOSEFORBIDTIMER_OFFSET UNITYSDK_OFFSET(0x19FE74D0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETBRANCHDATACHANGE_OFFSET UNITYSDK_OFFSET(0x19FE5BA0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETDATAWHENTOGGLECHANGE_OFFSET UNITYSDK_OFFSET(0x19FE8560)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETDESTROYCALLBACK_OFFSET UNITYSDK_OFFSET(0x19FE75E0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETNORMALDATACHANGE_OFFSET UNITYSDK_OFFSET(0x19FE85E0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICBRANCHACTIVEVIEW_OFFSET UNITYSDK_OFFSET(0x19FE3D10)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICITEMAFTERUPDATE_OFFSET UNITYSDK_OFFSET(0x19FE7570)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICUPGRADEVIEW_OFFSET UNITYSDK_OFFSET(0x19FE6B90)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICVIEW_OFFSET UNITYSDK_OFFSET(0x19FE6DB0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SWITCHDETAILDESC_OFFSET UNITYSDK_OFFSET(0x19FE8440)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_TRYSKIPRELICUPDATE_OFFSET UNITYSDK_OFFSET(0x19FE6710)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__CCTOR_OFFSET UNITYSDK_OFFSET(0x19FEA200)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x19FEA0A0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__ONCLICKCONFIRM_B__63_0_OFFSET UNITYSDK_OFFSET(0x19FEA220)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__RESETCLOSEFORBIDTIMER_B__43_0_OFFSET UNITYSDK_OFFSET(0x19FEA210)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_MASKCLOSE_OFFSET UNITYSDK_OFFSET(0x19FEA270)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x19FEA300)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x19FEA390)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x19FEA3C0)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x19FEA450)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x19FEA510)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x19FEA520)
#define MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_PLAYCLOSEANIM_OFFSET UNITYSDK_OFFSET(0x19FEA5B0)

namespace MoleMole
{
	inline static constexpr unsigned int UIHollowCardOptionsAbyssS2DialogPopWindowController_TypeDefinitionIndex = 41312;

	class UIHollowCardOptionsAbyssS2DialogPopWindowController : public ::MoleMole::UIHollowCardOptionsBasePopWindowController
	{
	public:
		static ::System::Int32* StaticGet_MAX_AVATAR_NUM()
		{
			return (::System::Int32*)Il2CppClass::FromTypeDefinitionIndex(UIHollowCardOptionsAbyssS2DialogPopWindowController_TypeDefinitionIndex)->GetStaticField(0x12DC0);
		}
		// static const ::System::String* SELECT_MODE_KEY; // 0x0
		// static const ::System::String* GET_MODE_KEY; // 0x0
		// static const ::System::String* UPGRADE_MODE_KEY; // 0x0
		// static const ::System::String* EFFECT_BG_FADE_OUT_ANIM; // 0x0
		// static const ::System::String* CARD_LIST_FADE_OUT; // 0x0
		// static const ::System::Single CLOSE_FORBID_TIME; // 0x0
		::System::Collections::Generic::List_1<::System::Collections::Generic::List_1<::Class_1_0E5778BB52E10271*>*>* _relicBranchdData; // 0x318
		::System::Collections::Generic::List_1<::Class_1_0E5778BB52E10271*>* _relicBranchdDataCacheView; // 0x320
		::Class_2_60638234271CCDB8_11* _view; // 0x328
		::MoleMole::UIHollowCardOptionsDialogContext* _dialogContext; // 0x330
		::System::Action* onDestroy; // 0x338
		::System::Collections::Generic::List_1<::Class_1_0E5778BB52E10271*>* _list; // 0x340
		::MoleMole::UIAbyssS2InfoBtnWidgetController* _abyssS2InfoBtn; // 0x348
		::MoleMole::UIGeneralToggleWidgetControllerWithModel* _toggleDetail; // 0x350
		::MoleMole::UIHollowCardOptionsRelicPanelWidgetController* _relicPanel; // 0x358
		::System::Boolean _forbidClose; // 0x360
		::System::Threading::CancellationTokenSource* _refreshCts; // 0x368
		::MoleMole::HollowCardCombineConfig* _config; // 0x370
		::System::Collections::Generic::List_1<::MoleMole::UIAbyssTabButtonWidgetController*>* _roleTabGroup; // 0x378
		::MoleMole::UIHollowCardOptionsAbyssS2DialogPopWindowController_CombineAnimationHelper* _combineAnimationHelper; // 0x380
		::System::Boolean _ShowRelicItemAfterUpdate; // 0x388
		::System::Boolean _isRefresh; // 0x389

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__CCTOR_OFFSET))();
		}

		::System::Void ShowRelicBranchActiveView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICBRANCHACTIVEVIEW_OFFSET))(this);
		}

		::System::Void InitBranchData(::Il2CppArray<::System::Collections::Generic::KeyValuePair_2<::System::Int32, ::System::Collections::Generic::List_1<::Class_1_4F9417780723166C*>*>>* branchOptions)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::System::Collections::Generic::KeyValuePair_2<::System::Int32, ::System::Collections::Generic::List_1<::Class_1_4F9417780723166C*>*>>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INITBRANCHDATA_OFFSET))(this, branchOptions);
		}

		::System::Void RefreshRoleTabGroup(::Il2CppArray<::System::Collections::Generic::KeyValuePair_2<::System::Int32, ::System::Collections::Generic::List_1<::Class_1_4F9417780723166C*>*>>* keyValuePairs)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::System::Collections::Generic::KeyValuePair_2<::System::Int32, ::System::Collections::Generic::List_1<::Class_1_4F9417780723166C*>*>>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHROLETABGROUP_OFFSET))(this, keyValuePairs);
		}

		static ::System::Void RefreshRoleTab(::System::Boolean empty, ::Il2CppArray<::System::Collections::Generic::KeyValuePair_2<::System::Int32, ::System::Collections::Generic::List_1<::Class_1_4F9417780723166C*>*>>* sortedArray, ::System::Int32 index, ::MoleMole::UIAbyssTabButtonWidgetController* roleTab)
		{
			return ((::System::Void(*)(::System::Boolean, ::Il2CppArray<::System::Collections::Generic::KeyValuePair_2<::System::Int32, ::System::Collections::Generic::List_1<::Class_1_4F9417780723166C*>*>>*, ::System::Int32, ::MoleMole::UIAbyssTabButtonWidgetController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHROLETAB_OFFSET))(empty, sortedArray, index, roleTab);
		}

		::System::Void RefreshRoleTabGroupByIndex(::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHROLETABGROUPBYINDEX_OFFSET))(this, index);
		}

		::System::Void OnTabGroupClick(::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONTABGROUPCLICK_OFFSET))(this, index);
		}

		::System::Void RefreshTabGroupList(::System::Boolean playScrollFadeIn, ::System::Int32 select)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTABGROUPLIST_OFFSET))(this, playScrollFadeIn, select);
		}

		::System::Void SetBranchDataChange(::System::Boolean showDetailDesc)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETBRANCHDATACHANGE_OFFSET))(this, showDetailDesc);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::Enum_3_8E90989A26BC6232 get_HotSwitchRootLayerState()
		{
			return ((::Enum_3_8E90989A26BC6232(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::Class_1_0E5778BB52E10271*>* get__allItemList()
		{
			return ((::System::Collections::Generic::List_1<::Class_1_0E5778BB52E10271*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET__ALLITEMLIST_OFFSET))(this);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::MoleMole::UIHollowCardOptionsRelicPanelWidgetController* get_RelicPanel()
		{
			return ((::MoleMole::UIHollowCardOptionsRelicPanelWidgetController*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GET_RELICPANEL_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void MaskClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_MASKCLOSE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Single PlayCloseAnim(::System::Action* callback, ::Enum_3_DBF2701137F18AA6 nextPage, ::System::String* fadeOutAnim)
		{
			return ((::System::Single(*)(::PVOID, ::System::Action*, ::Enum_3_DBF2701137F18AA6, ::System::String*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_PLAYCLOSEANIM_OFFSET))(this, callback, nextPage, fadeOutAnim);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONUICLOSE_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Boolean InRelicUpdate()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INRELICUPDATE_OFFSET))(this);
		}

		::System::Void ResetCloseForbidTimer()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_RESETCLOSEFORBIDTIMER_OFFSET))(this);
		}

		::System::Void TrySkipRelicUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_TRYSKIPRELICUPDATE_OFFSET))(this);
		}

		::System::Void SetDestroyCallback(::System::Action* callback)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETDESTROYCALLBACK_OFFSET))(this, callback);
		}

		::System::Void ShowRelicView(::System::Boolean playScrollFadeIn)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICVIEW_OFFSET))(this, playScrollFadeIn);
		}

		::System::Void RefreshList(::System::Boolean playScrollFadeIn)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHLIST_OFFSET))(this, playScrollFadeIn);
		}

		::System::Void RefreshTips()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTIPS_OFFSET))(this);
		}

		::System::Void RefreshConfirm()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHCONFIRM_OFFSET))(this);
		}

		::System::Void InitSelectGamepad()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INITSELECTGAMEPAD_OFFSET))(this);
		}

		::System::Void RefreshToggle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTOGGLE_OFFSET))(this);
		}

		::System::Void SwitchDetailDesc(::System::Boolean showDetailDesc)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SWITCHDETAILDESC_OFFSET))(this, showDetailDesc);
		}

		::System::Void SetDataWhenToggleChange(::System::Boolean showDetailDesc)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETDATAWHENTOGGLECHANGE_OFFSET))(this, showDetailDesc);
		}

		::System::Void SetNormalDataChange(::System::Boolean showDetailDesc)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SETNORMALDATACHANGE_OFFSET))(this, showDetailDesc);
		}

		::System::Void OnClickItem(::Class_1_0E5778BB52E10271* data)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_0E5778BB52E10271*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCLICKITEM_OFFSET))(this, data);
		}

		::System::Int32 GetSelectCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_GETSELECTCOUNT_OFFSET))(this);
		}

		::System::Void OnClickRefresh()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCLICKREFRESH_OFFSET))(this);
		}

		::System::Void InitRefreshButton()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_INITREFRESHBUTTON_OFFSET))(this);
		}

		::Cysharp::Threading::Tasks::UniTask RefreshTask()
		{
			return ((::Cysharp::Threading::Tasks::UniTask(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHTASK_OFFSET))(this);
		}

		::Cysharp::Threading::Tasks::UniTask RefreshInfoTask(::MoleMole::UIHollowCardOptionsDialogContext* dialogContext)
		{
			return ((::Cysharp::Threading::Tasks::UniTask(*)(::PVOID, ::MoleMole::UIHollowCardOptionsDialogContext*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_REFRESHINFOTASK_OFFSET))(this, dialogContext);
		}

		::Cysharp::Threading::Tasks::UniTask PlayViewRefresh()
		{
			return ((::Cysharp::Threading::Tasks::UniTask(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_PLAYVIEWREFRESH_OFFSET))(this);
		}

		::System::Void OnClickConfirm()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCLICKCONFIRM_OFFSET))(this);
		}

		::System::Void OnConfirm()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_ONCONFIRM_OFFSET))(this);
		}

		::Class_1_661077F66F5DB866* CreateSelectedResult()
		{
			return ((::Class_1_661077F66F5DB866*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_CREATESELECTEDRESULT_OFFSET))(this);
		}

		::Class_1_661077F66F5DB866* CreateHollowCardSelectedResult()
		{
			return ((::Class_1_661077F66F5DB866*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_CREATEHOLLOWCARDSELECTEDRESULT_OFFSET))(this);
		}

		::System::Void ShowRelicUpgradeView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICUPGRADEVIEW_OFFSET))(this);
		}

		::System::Void ShowRelicItemAfterUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_SHOWRELICITEMAFTERUPDATE_OFFSET))(this);
		}

		::System::Void PlayItemRelicUpgradeAnim()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER_PLAYITEMRELICUPGRADEANIM_OFFSET))(this);
		}

		::System::Void _ResetCloseForbidTimer_b__43_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__RESETCLOSEFORBIDTIMER_B__43_0_OFFSET))(this);
		}

		::System::Void _OnClickConfirm_b__63_0(::System::Int32 result)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER__ONCLICKCONFIRM_B__63_0_OFFSET))(this, result);
		}

		::System::Void __base_MaskClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_MASKCLOSE_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Single __base_PlayCloseAnim(::System::Action* P0, ::Enum_3_DBF2701137F18AA6 P1, ::System::String* P2)
		{
			return ((::System::Single(*)(::PVOID, ::System::Action*, ::Enum_3_DBF2701137F18AA6, ::System::String*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCARDOPTIONSABYSSS2DIALOGPOPWINDOWCONTROLLER___BASE_PLAYCLOSEANIM_OFFSET))(this, P0, P1, P2);
		}
	};
}
