#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_C4CB11A2FD957208_Struct_2_98E057419FFAAB00.h"
#include "unitysdk/MoleMole/ScrollViewItemWidgetController.h"
#include "unitysdk/MoleMole/UIHollowCollectRewardDialogRewardItemWidgetController_ButtonState.h"

class Class_1_1685EC66FBD28897;
class Class_2_208CC9941471731A_142;
class Class_2_42F554BCBCF18CB8;
namespace MoleMole { class UIAbyssSweepPopWindowController; }
namespace MoleMole { class UIControlReference; }
namespace System { class Object; }

#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONCLICKGETREWARD_OFFSET UNITYSDK_OFFSET(0x1525F580)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONCLICKSWEEP_OFFSET UNITYSDK_OFFSET(0x1525F6D0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15260A10)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONSCROLLITEMUPDATE_OFFSET UNITYSDK_OFFSET(0x1525FD00)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x15260AA0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x1525F3D0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_REFRESHBUTTONSTATE_OFFSET UNITYSDK_OFFSET(0x1525FE90)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_REFRESHSCROLLVIEW_OFFSET UNITYSDK_OFFSET(0x152608A0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0x152601F0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_SHOWREWARDDIALOG_OFFSET UNITYSDK_OFFSET(0x1525FB20)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x15260B20)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_0_OFFSET UNITYSDK_OFFSET(0x15260B30)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_1_OFFSET UNITYSDK_OFFSET(0x15260C80)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_2_OFFSET UNITYSDK_OFFSET(0x15260DF0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_3_OFFSET UNITYSDK_OFFSET(0x15260DD0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_4_OFFSET UNITYSDK_OFFSET(0x15260E50)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_6_OFFSET UNITYSDK_OFFSET(0x15261250)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__REFRESHSCROLLVIEW_B__8_0_OFFSET UNITYSDK_OFFSET(0x15261300)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15261450)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONSCROLLITEMUPDATE_OFFSET UNITYSDK_OFFSET(0x152614E0)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x15261580)
#define MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x15261610)

namespace MoleMole
{
	inline static constexpr unsigned int UIHollowCollectRewardDialogRewardItemWidgetController_TypeDefinitionIndex = 64746;

	class UIHollowCollectRewardDialogRewardItemWidgetController : public ::MoleMole::ScrollViewItemWidgetController
	{
	public:
		::Class_2_42F554BCBCF18CB8* _view; // 0x2E8
		::MoleMole::UIAbyssSweepPopWindowController* _sweepPopWindow; // 0x2F0
		::Class_2_208CC9941471731A_142* m_cfg; // 0x2F8
		::MoleMole::UIHollowCollectRewardDialogRewardItemWidgetController_ButtonState m_buttonState; // 0x300

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnClickGetReward()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONCLICKGETREWARD_OFFSET))(this);
		}

		::System::Void OnClickSweep()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONCLICKSWEEP_OFFSET))(this);
		}

		::System::Void ShowRewardDialog()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_SHOWREWARDDIALOG_OFFSET))(this);
		}

		::System::Void OnScrollItemUpdate(::System::Int32 index, ::System::Object* data, ::System::Boolean init)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONSCROLLITEMUPDATE_OFFSET))(this, index, data, init);
		}

		::System::Void RefreshScrollView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_REFRESHSCROLLVIEW_OFFSET))(this);
		}

		::System::Void RefreshButtonState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_REFRESHBUTTONSTATE_OFFSET))(this);
		}

		::System::Void RefreshView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_REFRESHVIEW_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::Class_1_1685EC66FBD28897* _OnClickSweep_b__4_0(::Class_1_C4CB11A2FD957208_Struct_2_98E057419FFAAB00 x)
		{
			return ((::Class_1_1685EC66FBD28897*(*)(::PVOID, ::Class_1_C4CB11A2FD957208_Struct_2_98E057419FFAAB00))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_0_OFFSET))(this, x);
		}

		::System::Void _OnClickSweep_b__4_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_1_OFFSET))(this);
		}

		::System::Void _OnClickSweep_b__4_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_3_OFFSET))(this);
		}

		::System::Void _OnClickSweep_b__4_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_2_OFFSET))(this);
		}

		::System::Void _OnClickSweep_b__4_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_4_OFFSET))(this);
		}

		::System::Void _OnClickSweep_b__4_6()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__ONCLICKSWEEP_B__4_6_OFFSET))(this);
		}

		::Class_1_1685EC66FBD28897* _RefreshScrollView_b__8_0(::Class_1_C4CB11A2FD957208_Struct_2_98E057419FFAAB00 x)
		{
			return ((::Class_1_1685EC66FBD28897*(*)(::PVOID, ::Class_1_C4CB11A2FD957208_Struct_2_98E057419FFAAB00))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER__REFRESHSCROLLVIEW_B__8_0_OFFSET))(this, x);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnScrollItemUpdate(::System::Int32 P0, ::System::Object* P1, ::System::Boolean P2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONSCROLLITEMUPDATE_OFFSET))(this, P0, P1, P2);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHOLLOWCOLLECTREWARDDIALOGREWARDITEMWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}
	};
}
