#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Foundation/Coroutine/CoroutineHandle.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/InputLogicEventType.h"
#include "unitysdk/MoleMole/LogicButtonInputType.h"
#include "unitysdk/MoleMole/UIInLevelGamePlayButtonBaseController.h"

class Class_2_34D83D6328FA369E;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class EventArgs; }

#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_CHANGESTATE_OFFSET UNITYSDK_OFFSET(0x199F9C90)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GETGRAPHICCASTENABLE_OFFSET UNITYSDK_OFFSET(0x199FA820)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GET_ENABLEDRAGINPUTINSKILLBUTTON_OFFSET UNITYSDK_OFFSET(0x199FA1C0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GET_VIRTUALLOGICBUTTONINPUTTYPE_OFFSET UNITYSDK_OFFSET(0x199F9FD0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x199F9850)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_INITPLAYBTN_OFFSET UNITYSDK_OFFSET(0x199FA710)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ISBTNWORKABLE_OFFSET UNITYSDK_OFFSET(0x199F9F40)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ISCOMBINEDINTERACTINPUTEVENTTYPE_OFFSET UNITYSDK_OFFSET(0x199FA3E0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONBUTTONDOWN_OFFSET UNITYSDK_OFFSET(0x199FA5F0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x199F9860)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0x199F9E70)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONINPUTDEVICECHANGE_OFFSET UNITYSDK_OFFSET(0x199FA780)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x199FA7D0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0x199F9BB0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x199F9EE0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x199F98F0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x199F9A20)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONZENKOVCONSOLEINTERACTINPUTMODECHANGED_OFFSET UNITYSDK_OFFSET(0x199F99D0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_SETGRAPHICCASTENABLE_OFFSET UNITYSDK_OFFSET(0x199F9AB0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_SHOULDSKILLBUTTONHANDLEINPUT_OFFSET UNITYSDK_OFFSET(0x199FA1D0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER__CHANGESTATE_B__21_0_OFFSET UNITYSDK_OFFSET(0x199FA980)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x199FA8C0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_GET_VIRTUALLOGICBUTTONINPUTTYPE_OFFSET UNITYSDK_OFFSET(0x199FAA40)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_INITPLAYBTN_OFFSET UNITYSDK_OFFSET(0x199FAA50)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ISBTNWORKABLE_OFFSET UNITYSDK_OFFSET(0x199FAA60)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONBUTTONDOWN_OFFSET UNITYSDK_OFFSET(0x199FAA70)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x199FAB00)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0x199FAB90)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x199FAC20)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0x199FACB0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x199FACC0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x199FACD0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x199FACE0)
#define MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_SHOULDSKILLBUTTONHANDLEINPUT_OFFSET UNITYSDK_OFFSET(0x199FACF0)

namespace MoleMole
{
	inline static constexpr unsigned int UIInLevelSkillButtonQteDoorInteractChildWindowController_TypeDefinitionIndex = 76648;

	class UIInLevelSkillButtonQteDoorInteractChildWindowController : public ::MoleMole::UIInLevelGamePlayButtonBaseController
	{
	public:
		::Class_2_34D83D6328FA369E* _view; // 0x368
		::System::Boolean _isTriggeredByDown; // 0x370
		::Foundation::Coroutine::CoroutineHandle fadeOutHandle; // 0x374
		::System::Single _fadeOutLen; // 0x378

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnZenkovConsoleInteractInputModeChanged(::System::EventArgs* e)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONZENKOVCONSOLEINTERACTINPUTMODECHANGED_OFFSET))(this, e);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Boolean IsBtnWorkable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ISBTNWORKABLE_OFFSET))(this);
		}

		::MoleMole::LogicButtonInputType get_VirtualLogicButtonInputType()
		{
			return ((::MoleMole::LogicButtonInputType(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GET_VIRTUALLOGICBUTTONINPUTTYPE_OFFSET))(this);
		}

		::System::Boolean get_EnableDragInputInSkillButton()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GET_ENABLEDRAGINPUTINSKILLBUTTON_OFFSET))(this);
		}

		::System::Boolean ShouldSkillButtonHandleInput(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_SHOULDSKILLBUTTONHANDLEINPUT_OFFSET))(this, inputAction);
		}

		::System::Void OnButtonDown()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONBUTTONDOWN_OFFSET))(this);
		}

		::System::Void InitPlayBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_INITPLAYBTN_OFFSET))(this);
		}

		::System::Void OnInputDeviceChange(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONINPUTDEVICECHANGE_OFFSET))(this, args);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void ChangeState(::System::Boolean isIn)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_CHANGESTATE_OFFSET))(this, isIn);
		}

		::System::Boolean GetGraphicCastEnable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_GETGRAPHICCASTENABLE_OFFSET))(this);
		}

		::System::Void SetGraphicCastEnable(::System::Boolean enable)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_SETGRAPHICCASTENABLE_OFFSET))(this, enable);
		}

		::System::Boolean IsCombinedInteractInputEventType(::MoleMole::InputLogicEventType input)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputLogicEventType))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER_ISCOMBINEDINTERACTINPUTEVENTTYPE_OFFSET))(this, input);
		}

		::System::Void _ChangeState_b__21_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER__CHANGESTATE_B__21_0_OFFSET))(this);
		}

		::MoleMole::LogicButtonInputType __base_get_VirtualLogicButtonInputType()
		{
			return ((::MoleMole::LogicButtonInputType(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_GET_VIRTUALLOGICBUTTONINPUTTYPE_OFFSET))(this);
		}

		::System::Void __base_InitPlayBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_INITPLAYBTN_OFFSET))(this);
		}

		::System::Boolean __base_IsBtnWorkable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ISBTNWORKABLE_OFFSET))(this);
		}

		::System::Void __base_OnButtonDown()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONBUTTONDOWN_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Boolean __base_ShouldSkillButtonHandleInput(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSKILLBUTTONQTEDOORINTERACTCHILDWINDOWCONTROLLER___BASE_SHOULDSKILLBUTTONHANDLEINPUT_OFFSET))(this, P0);
		}
	};
}
