#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_F4299CC27263318B.h"
#include "unitysdk/System/Nullable_1.h"

template <typename T> class Class_0_16E4307DCC41950C_13;

#define MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER_GET_PLAYHPUPANIM_OFFSET UNITYSDK_OFFSET(0x148209C0)
#define MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER_ONCREATEPROPERTY_OFFSET UNITYSDK_OFFSET(0x148209E0)
#define MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER_SET_PLAYHPUPANIM_OFFSET UNITYSDK_OFFSET(0x148209D0)
#define MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER__CTOR_OFFSET UNITYSDK_OFFSET(0x14820A60)

namespace MoleMole
{
	inline static constexpr unsigned int UIInLevelRoleHudWidgetChildWindowController_HpAnimDataBindView_InnerPropertyContainer_TypeDefinitionIndex = 41490;

	class UIInLevelRoleHudWidgetChildWindowController_HpAnimDataBindView_InnerPropertyContainer : public ::Class_1_F4299CC27263318B
	{
	public:
		::Class_0_16E4307DCC41950C_13<::System::Nullable_1<::System::Boolean>>* _PlayHpUpAnim_k__BackingField; // 0x70

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER__CTOR_OFFSET))(this);
		}

		::Class_0_16E4307DCC41950C_13<::System::Nullable_1<::System::Boolean>>* get_PlayHpUpAnim()
		{
			return ((::Class_0_16E4307DCC41950C_13<::System::Nullable_1<::System::Boolean>>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER_GET_PLAYHPUPANIM_OFFSET))(this);
		}

		::System::Void set_PlayHpUpAnim(::Class_0_16E4307DCC41950C_13<::System::Nullable_1<::System::Boolean>>* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC41950C_13<::System::Nullable_1<::System::Boolean>>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER_SET_PLAYHPUPANIM_OFFSET))(this, value);
		}

		::System::Void OnCreateProperty()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELROLEHUDWIDGETCHILDWINDOWCONTROLLER_HPANIMDATABINDVIEW_INNERPROPERTYCONTAINER_ONCREATEPROPERTY_OFFSET))(this);
		}
	};
}
