#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

class Class_1_5FBB235457C1293C;
namespace MoleMole { class UIPhotoWallSwitchPopWindowController; }
namespace System { class Action; }

#define MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__CTOR_OFFSET UNITYSDK_OFFSET(0x16A720F0)
#define MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__1_OFFSET UNITYSDK_OFFSET(0x16A72100)
#define MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__2_OFFSET UNITYSDK_OFFSET(0x16A724C0)
#define MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__3_OFFSET UNITYSDK_OFFSET(0x16A72620)
#define MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__4_OFFSET UNITYSDK_OFFSET(0x16A72600)
#define MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_G__ONCONFIRM_0_OFFSET UNITYSDK_OFFSET(0x16A72260)

namespace MoleMole
{
	inline static constexpr unsigned int UIPhotoWallSwitchPopWindowController___c__DisplayClass17_0_TypeDefinitionIndex = 67017;

	class UIPhotoWallSwitchPopWindowController___c__DisplayClass17_0 : public ::System::Object
	{
	public:
		::System::Action* __9__4; // 0x10
		::Class_1_5FBB235457C1293C* data; // 0x18
		::MoleMole::UIPhotoWallSwitchPopWindowController* __4__this; // 0x20

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__CTOR_OFFSET))(this);
		}

		::System::Void _OnClickConfirmCallback_b__1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__1_OFFSET))(this);
		}

		::System::Void _OnClickConfirmCallback_g__OnConfirm_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_G__ONCONFIRM_0_OFFSET))(this);
		}

		::System::Void _OnClickConfirmCallback_b__2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__2_OFFSET))(this);
		}

		::System::Void _OnClickConfirmCallback_b__4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__4_OFFSET))(this);
		}

		::System::Void _OnClickConfirmCallback_b__3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIPHOTOWALLSWITCHPOPWINDOWCONTROLLER___C__DISPLAYCLASS17_0__ONCLICKCONFIRMCALLBACK_B__3_OFFSET))(this);
		}
	};
}
