#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Enum_3_CC3BC82D2D2360D0.h"
#include "unitysdk/Enum_3_D3384FC764485EA3.h"
#include "unitysdk/MoleMole/UIWindowController.h"

class Class_1_48D56DACBE4271BC;
class Class_1_B890BA8430A32496_Class_1_D8C08C94211C11A1;
class Class_2_EFEFC07575EC322B;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UISuibianTempleManageRowWidgetController; }
namespace System { class EventArgs; }

#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_BINDPROPERTY_OFFSET UNITYSDK_OFFSET(0x1629A230)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_BINDRESOLVEBTN_OFFSET UNITYSDK_OFFSET(0x1629B070)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_BIND_OFFSET UNITYSDK_OFFSET(0x162996B0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_GET_TYPE_OFFSET UNITYSDK_OFFSET(0x16299360)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x16299350)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_INITAUTODISPOSEDATABIND_OFFSET UNITYSDK_OFFSET(0x16299400)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_INITTOKEN_OFFSET UNITYSDK_OFFSET(0x1629A030)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_INITTOPPANEL_OFFSET UNITYSDK_OFFSET(0x1629A170)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x16299370)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONRESOLVE_OFFSET UNITYSDK_OFFSET(0x1629B790)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x1629AA30)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x162994A0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONUNLOCK_OFFSET UNITYSDK_OFFSET(0x1629B720)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_OPENINFOBTN_OFFSET UNITYSDK_OFFSET(0x1629AFE0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_OPENSIMPAGE_OFFSET UNITYSDK_OFFSET(0x1629AB70)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_REFRESHPROGRESS_OFFSET UNITYSDK_OFFSET(0x1629B240)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_REFRESHTRACK_OFFSET UNITYSDK_OFFSET(0x1629A4E0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_RESET_OFFSET UNITYSDK_OFFSET(0x1629BAF0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_RESTOREPARAS_OFFSET UNITYSDK_OFFSET(0x1629BB40)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__BIND_B__16_1_OFFSET UNITYSDK_OFFSET(0x1629BB90)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__BIND_B__16_2_OFFSET UNITYSDK_OFFSET(0x1629BBA0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__BIND_B__16_3_OFFSET UNITYSDK_OFFSET(0x1629BBB0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x1629BB80)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_INITAUTODISPOSEDATABIND_OFFSET UNITYSDK_OFFSET(0x1629BBC0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x1629BC50)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x1629BCE0)
#define MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x1629BCF0)

namespace MoleMole
{
	inline static constexpr unsigned int UISuibianTempleManagePageController_TypeDefinitionIndex = 74926;

	class UISuibianTempleManagePageController : public ::MoleMole::UIWindowController
	{
	public:
		::Class_2_EFEFC07575EC322B* _view; // 0x318
		::MoleMole::UISuibianTempleManageRowWidgetController* researchBtn; // 0x320
		::MoleMole::UISuibianTempleManageRowWidgetController* saleBtn; // 0x328
		::MoleMole::UISuibianTempleManageRowWidgetController* produceBtn; // 0x330
		::Class_1_48D56DACBE4271BC* syncHelper; // 0x338

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::Enum_3_CC3BC82D2D2360D0 get_Type()
		{
			return ((::Enum_3_CC3BC82D2D2360D0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_GET_TYPE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void InitAutoDisposeDataBind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_INITAUTODISPOSEDATABIND_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void BindProperty()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_BINDPROPERTY_OFFSET))(this);
		}

		::System::Void RefreshTrack(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_REFRESHTRACK_OFFSET))(this, args);
		}

		::System::Void OpenSimPage(::Enum_3_D3384FC764485EA3 panelType)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_D3384FC764485EA3))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_OPENSIMPAGE_OFFSET))(this, panelType);
		}

		::System::Void OpenInfoBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_OPENINFOBTN_OFFSET))(this);
		}

		::System::Void Bind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_BIND_OFFSET))(this);
		}

		::System::Void OnUnlock(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONUNLOCK_OFFSET))(this, args);
		}

		::System::Void BindResolveBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_BINDRESOLVEBTN_OFFSET))(this);
		}

		::System::Void OnResolve()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_ONRESOLVE_OFFSET))(this);
		}

		::System::Void RefreshProgress()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_REFRESHPROGRESS_OFFSET))(this);
		}

		::System::Void InitToken()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_INITTOKEN_OFFSET))(this);
		}

		::System::Void InitTopPanel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_INITTOPPANEL_OFFSET))(this);
		}

		::System::Void Reset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_RESET_OFFSET))(this);
		}

		::Class_1_B890BA8430A32496_Class_1_D8C08C94211C11A1* RestoreParas()
		{
			return ((::Class_1_B890BA8430A32496_Class_1_D8C08C94211C11A1*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER_RESTOREPARAS_OFFSET))(this);
		}

		::System::Void _Bind_b__16_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__BIND_B__16_1_OFFSET))(this);
		}

		::System::Void _Bind_b__16_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__BIND_B__16_2_OFFSET))(this);
		}

		::System::Void _Bind_b__16_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER__BIND_B__16_3_OFFSET))(this);
		}

		::System::Void __base_InitAutoDisposeDataBind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_INITAUTODISPOSEDATABIND_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEMANAGEPAGECONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}
	};
}
