#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Cysharp/Threading/Tasks/UniTask.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIMainCityStorePageController.h"

class Class_1_0D6706375CDAAE8C;
class Class_2_01B22E9930E7BB4D;
class Class_2_60638234271CCDB8_97;
class Class_2_B8262BA14DBAEA9D;
class Class_3_C3F0E3B5AB5977AE;
namespace MoleMole { class MonoGamepadModule; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralToggleWidgetController; }
namespace MoleMole { class UIGeneralTokenRowWidgetController; }
namespace MoleMole { class UISuibianTempleHiveBoxDetailPanelWidgetController; }
namespace MoleMole { class UISuibianTempleHiveBoxListRowWidgetController; }
namespace MoleMole { class UISuibianTempleHiveBoxPageController_ViewModel; }
namespace MoleMole::Battle { class Entity; }
namespace System { class EventArgs; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_BIND_OFFSET UNITYSDK_OFFSET(0x151188A0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_BUDDYPLAYANI_OFFSET UNITYSDK_OFFSET(0x1511D830)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_BUILDVIEWMODELDATABINDING_OFFSET UNITYSDK_OFFSET(0x15119160)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CLEARALLNEWPOINT_OFFSET UNITYSDK_OFFSET(0x1511A480)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CLEARBUDDYENTITY_OFFSET UNITYSDK_OFFSET(0x1511D600)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CLOSEDOOR_OFFSET UNITYSDK_OFFSET(0x1511DEF0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CREATEBUDDYENTITY_OFFSET UNITYSDK_OFFSET(0x1511D550)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_DOORPLAYANI_OFFSET UNITYSDK_OFFSET(0x1511D980)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETCURRENTPERIODPERFORMID_OFFSET UNITYSDK_OFFSET(0x1511B7A0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETLISTROWCONTROLLER_OFFSET UNITYSDK_OFFSET(0x1511CEF0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETTEMPLEBUDDYLIST_OFFSET UNITYSDK_OFFSET(0x1511D480)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETTEMPLEBUDDY_OFFSET UNITYSDK_OFFSET(0x1511D0F0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x15118650)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_INITAUTODISPOSEDATABIND_OFFSET UNITYSDK_OFFSET(0x151186F0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_INITTOKEN_OFFSET UNITYSDK_OFFSET(0x1511ADD0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_INITVIEW_OFFSET UNITYSDK_OFFSET(0x15119060)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKBUYBTN_OFFSET UNITYSDK_OFFSET(0x1511B310)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKINFOBTN_OFFSET UNITYSDK_OFFSET(0x1511B110)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKREFRESHBTN_OFFSET UNITYSDK_OFFSET(0x1511AFB0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKSCROLLVIEWITEM_OFFSET UNITYSDK_OFFSET(0x1511BF10)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15118660)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONGAMEPADMODULELOSTFOCUS_OFFSET UNITYSDK_OFFSET(0x1511ACC0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONHIVEBOXPERFORMNOTIFY_OFFSET UNITYSDK_OFFSET(0x1511E1A0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x1511AA10)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONITEMMULTICLICK_OFFSET UNITYSDK_OFFSET(0x1511C850)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x1511A960)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONMULTITOGGLECHANGE_OFFSET UNITYSDK_OFFSET(0x1511B930)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONOPENMANAGE_OFFSET UNITYSDK_OFFSET(0x1511AF20)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x1511A410)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x151187E0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x151199C0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_OPENDOOR_OFFSET UNITYSDK_OFFSET(0x1511DC40)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_REFRESHALLPROPERTIES_OFFSET UNITYSDK_OFFSET(0x15119A20)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_REGISTEREVENTS_OFFSET UNITYSDK_OFFSET(0x15118F90)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_SETUIWINDOWSETTING_OFFSET UNITYSDK_OFFSET(0x1511A8C0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_0_OFFSET UNITYSDK_OFFSET(0x1511E8C0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_10_OFFSET UNITYSDK_OFFSET(0x151201B0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_11_OFFSET UNITYSDK_OFFSET(0x1511F280)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_1_OFFSET UNITYSDK_OFFSET(0x1511EA30)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_2_OFFSET UNITYSDK_OFFSET(0x1511ECA0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_3_OFFSET UNITYSDK_OFFSET(0x1511EDD0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_4_OFFSET UNITYSDK_OFFSET(0x1511F3B0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_5_OFFSET UNITYSDK_OFFSET(0x1511F620)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_6_OFFSET UNITYSDK_OFFSET(0x1511F910)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_7_OFFSET UNITYSDK_OFFSET(0x1511FB80)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_8_OFFSET UNITYSDK_OFFSET(0x1511FFA0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_9_OFFSET UNITYSDK_OFFSET(0x151200C0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__CREATEBUDDYENTITY_B__36_0_OFFSET UNITYSDK_OFFSET(0x1511E490)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__CREATEBUDDYENTITY_B__36_1_OFFSET UNITYSDK_OFFSET(0x1511E4E0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x1511E370)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__GETTEMPLEBUDDYLIST_B__35_0_OFFSET UNITYSDK_OFFSET(0x1511E470)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__REGISTEREVENTS_B__43_0_OFFSET UNITYSDK_OFFSET(0x1511E630)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__REGISTEREVENTS_B__43_1_OFFSET UNITYSDK_OFFSET(0x1511E7D0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_INITAUTODISPOSEDATABIND_OFFSET UNITYSDK_OFFSET(0x151203F0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x15120480)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONGAMEPADMODULELOSTFOCUS_OFFSET UNITYSDK_OFFSET(0x15120510)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x151205A0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x151205D0)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x15120660)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x15120670)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x15120680)
#define MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_SETUIWINDOWSETTING_OFFSET UNITYSDK_OFFSET(0x15120690)

namespace MoleMole
{
	inline static constexpr unsigned int UISuibianTempleHiveBoxPageController_TypeDefinitionIndex = 60451;

	class UISuibianTempleHiveBoxPageController : public ::MoleMole::UIMainCityStorePageController
	{
	public:
		::Class_2_60638234271CCDB8_97* _view; // 0x328
		::MoleMole::UIGeneralToggleWidgetController* _toggleWidget; // 0x330
		::MoleMole::UIGeneralTokenRowWidgetController* _tokenWidget; // 0x338
		::MoleMole::UISuibianTempleHiveBoxDetailPanelWidgetController* _detailPanelWidget; // 0x340
		::System::Boolean _isScrollViewInited; // 0x348
		::System::Boolean _isMultiSelect; // 0x349
		::System::Int32 _curSelectIndex; // 0x34C
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::Class_2_01B22E9930E7BB4D*>* _templeBuddies; // 0x350
		::MoleMole::Battle::Entity* _buddyEntity; // 0x358
		::System::Collections::Generic::List_1<::Class_1_0D6706375CDAAE8C*>* _selectToBuyItems; // 0x360
		::Class_2_B8262BA14DBAEA9D* _propertySyncHelper; // 0x368
		::MoleMole::UISuibianTempleHiveBoxPageController_ViewModel* _viewModel; // 0x370

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void InitAutoDisposeDataBind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_INITAUTODISPOSEDATABIND_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void SetUIWindowSetting()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_SETUIWINDOWSETTING_OFFSET))(this);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void OnGamepadModuleLostFocus(::MoleMole::MonoGamepadModule* gamepadModule)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONGAMEPADMODULELOSTFOCUS_OFFSET))(this, gamepadModule);
		}

		::System::Void Bind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_BIND_OFFSET))(this);
		}

		::System::Void InitView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_INITVIEW_OFFSET))(this);
		}

		::System::Void InitToken()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_INITTOKEN_OFFSET))(this);
		}

		::System::Void OnOpenManage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONOPENMANAGE_OFFSET))(this);
		}

		::System::Void OnClickRefreshBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKREFRESHBTN_OFFSET))(this);
		}

		::System::Void OnClickInfoBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKINFOBTN_OFFSET))(this);
		}

		::System::Void ClearAllNewPoint()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CLEARALLNEWPOINT_OFFSET))(this);
		}

		::System::Void OnClickBuyBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKBUYBTN_OFFSET))(this);
		}

		::System::Int32 GetCurrentPeriodPerformId()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETCURRENTPERIODPERFORMID_OFFSET))(this);
		}

		::System::Void OnMultiToggleChange()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONMULTITOGGLECHANGE_OFFSET))(this);
		}

		::System::Void OnClickScrollViewItem(::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONCLICKSCROLLVIEWITEM_OFFSET))(this, index);
		}

		::System::Void OnItemMultiClick(::System::EventArgs* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONITEMMULTICLICK_OFFSET))(this, arg);
		}

		::MoleMole::UISuibianTempleHiveBoxListRowWidgetController* GetListRowController(::System::Int32 index)
		{
			return ((::MoleMole::UISuibianTempleHiveBoxListRowWidgetController*(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETLISTROWCONTROLLER_OFFSET))(this, index);
		}

		::Class_2_01B22E9930E7BB4D* GetTempleBuddy(::System::UInt32 buddyId)
		{
			return ((::Class_2_01B22E9930E7BB4D*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETTEMPLEBUDDY_OFFSET))(this, buddyId);
		}

		::System::Collections::Generic::List_1<::Class_2_01B22E9930E7BB4D*>* GetTempleBuddyList()
		{
			return ((::System::Collections::Generic::List_1<::Class_2_01B22E9930E7BB4D*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_GETTEMPLEBUDDYLIST_OFFSET))(this);
		}

		::Cysharp::Threading::Tasks::UniTask CreateBuddyEntity(::System::Int32 buddyID)
		{
			return ((::Cysharp::Threading::Tasks::UniTask(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CREATEBUDDYENTITY_OFFSET))(this, buddyID);
		}

		::System::Void ClearBuddyEntity()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CLEARBUDDYENTITY_OFFSET))(this);
		}

		::System::Void BuddyPlayAni(::System::Int32 triggerID)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_BUDDYPLAYANI_OFFSET))(this, triggerID);
		}

		::System::Void DoorPlayAni(::System::Int32 triggerID)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_DOORPLAYANI_OFFSET))(this, triggerID);
		}

		::System::Void OpenDoor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_OPENDOOR_OFFSET))(this);
		}

		::System::Void CloseDoor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_CLOSEDOOR_OFFSET))(this);
		}

		::System::Void OnHiveBoxPerformNotify(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_ONHIVEBOXPERFORMNOTIFY_OFFSET))(this, args);
		}

		::System::Void RegisterEvents()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_REGISTEREVENTS_OFFSET))(this);
		}

		::System::Void BuildViewModelDataBinding()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_BUILDVIEWMODELDATABINDING_OFFSET))(this);
		}

		::System::Void RefreshAllProperties()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER_REFRESHALLPROPERTIES_OFFSET))(this);
		}

		::Class_2_01B22E9930E7BB4D* _GetTempleBuddyList_b__35_0(::Class_3_C3F0E3B5AB5977AE* templeBuddyGood)
		{
			return ((::Class_2_01B22E9930E7BB4D*(*)(::PVOID, ::Class_3_C3F0E3B5AB5977AE*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__GETTEMPLEBUDDYLIST_B__35_0_OFFSET))(this, templeBuddyGood);
		}

		::System::Boolean _CreateBuddyEntity_b__36_0()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__CREATEBUDDYENTITY_B__36_0_OFFSET))(this);
		}

		::System::Void _CreateBuddyEntity_b__36_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__CREATEBUDDYENTITY_B__36_1_OFFSET))(this);
		}

		::System::Void _RegisterEvents_b__43_0(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__REGISTEREVENTS_B__43_0_OFFSET))(this, args);
		}

		::System::Void _RegisterEvents_b__43_1(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__REGISTEREVENTS_B__43_1_OFFSET))(this, args);
		}

		::System::Void _BuildViewModelDataBinding_b__44_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_0_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_1_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_2_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_3_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_11()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_11_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_4_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_5()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_5_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_6()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_6_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_7()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_7_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_8()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_8_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_9()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_9_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__44_10()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER__BUILDVIEWMODELDATABINDING_B__44_10_OFFSET))(this);
		}

		::System::Void __base_InitAutoDisposeDataBind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_INITAUTODISPOSEDATABIND_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnGamepadModuleLostFocus(::MoleMole::MonoGamepadModule* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONGAMEPADMODULELOSTFOCUS_OFFSET))(this, P0);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Void __base_SetUIWindowSetting()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEHIVEBOXPAGECONTROLLER___BASE_SETUIWINDOWSETTING_OFFSET))(this);
		}
	};
}
