#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIUrbanMapPointWidgetContext.h"
#include "unitysdk/Struct_2_032E3093F309FC91.h"

class Class_1_2C37E1F4F32A068C_1;
namespace MoleMole { class UIUrbanMapPointGroupWidgetContext; }
namespace System { class Object; }
namespace System { class String; }

#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_EQUALS_1_OFFSET UNITYSDK_OFFSET(0x160FFD30)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_EQUALS_OFFSET UNITYSDK_OFFSET(0x160FFC90)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_FORCECLICKPOPINWORLDSTATE_OFFSET UNITYSDK_OFFSET(0x160FFE40)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETBANNER_OFFSET UNITYSDK_OFFSET(0x160FF920)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETICONWIDGETNAME_OFFSET UNITYSDK_OFFSET(0x160FEDA0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETKEY_OFFSET UNITYSDK_OFFSET(0x160FFBE0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETTITLEKEY_OFFSET UNITYSDK_OFFSET(0x160FF750)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETTITLETEXT_OFFSET UNITYSDK_OFFSET(0x160FF570)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETWORLDPOSITION_OFFSET UNITYSDK_OFFSET(0x160FFB50)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GET_GETAREAMAPPANELCONFIGID_INTERNAL_OFFSET UNITYSDK_OFFSET(0x160FF210)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_ISINWORLDSTATELOCK_OFFSET UNITYSDK_OFFSET(0x160FEE10)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_ISUNLOCK_OFFSET UNITYSDK_OFFSET(0x160FEEA0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_ONSHOWPANEL_OFFSET UNITYSDK_OFFSET(0x160FF080)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT__CTOR_OFFSET UNITYSDK_OFFSET(0x160FFE80)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_EQUALS_OFFSET UNITYSDK_OFFSET(0x160FFED0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_FORCECLICKPOPINWORLDSTATE_OFFSET UNITYSDK_OFFSET(0x160FFEE0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETBANNER_OFFSET UNITYSDK_OFFSET(0x160FFF80)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETICONWIDGETNAME_OFFSET UNITYSDK_OFFSET(0x160FFF90)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETKEY_OFFSET UNITYSDK_OFFSET(0x16100020)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETTITLEKEY_OFFSET UNITYSDK_OFFSET(0x161000C0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETTITLETEXT_OFFSET UNITYSDK_OFFSET(0x161000D0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETWORLDPOSITION_OFFSET UNITYSDK_OFFSET(0x161000E0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GET_GETAREAMAPPANELCONFIGID_INTERNAL_OFFSET UNITYSDK_OFFSET(0x160FFF70)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_ISINWORLDSTATELOCK_OFFSET UNITYSDK_OFFSET(0x161001C0)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_ISUNLOCK_OFFSET UNITYSDK_OFFSET(0x16100250)
#define MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_ONSHOWPANEL_OFFSET UNITYSDK_OFFSET(0x161002E0)

namespace MoleMole
{
	inline static constexpr unsigned int UIThreeDMapElement_PortalContext_TypeDefinitionIndex = 54116;

	class UIThreeDMapElement_PortalContext : public ::MoleMole::UIUrbanMapPointWidgetContext
	{
	public:
		::Class_1_2C37E1F4F32A068C_1* CfgID; // 0x58

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT__CTOR_OFFSET))(this);
		}

		::System::String* GetIconWidgetName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETICONWIDGETNAME_OFFSET))(this);
		}

		::System::Boolean IsInWorldStateLock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_ISINWORLDSTATELOCK_OFFSET))(this);
		}

		::System::Boolean IsUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_ISUNLOCK_OFFSET))(this);
		}

		::System::Void OnShowPanel(::MoleMole::UIUrbanMapPointGroupWidgetContext* fromGroupContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIUrbanMapPointGroupWidgetContext*))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_ONSHOWPANEL_OFFSET))(this, fromGroupContext);
		}

		::System::Int32 get_GetAreaMapPanelConfigId_Internal()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GET_GETAREAMAPPANELCONFIGID_INTERNAL_OFFSET))(this);
		}

		::System::String* GetTitleText()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETTITLETEXT_OFFSET))(this);
		}

		::System::String* GetTitleKey()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETTITLEKEY_OFFSET))(this);
		}

		::System::String* GetBanner()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETBANNER_OFFSET))(this);
		}

		::Struct_2_032E3093F309FC91 GetWorldPosition()
		{
			return ((::Struct_2_032E3093F309FC91(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETWORLDPOSITION_OFFSET))(this);
		}

		::System::UInt64 GetKey()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_GETKEY_OFFSET))(this);
		}

		::System::Boolean Equals(::MoleMole::UIThreeDMapElement_PortalContext* other)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::UIThreeDMapElement_PortalContext*))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_EQUALS_OFFSET))(this, other);
		}

		::System::Boolean Equals_1(::System::Object* obj)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_EQUALS_1_OFFSET))(this, obj);
		}

		::System::Boolean ForceClickPopInWorldState()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT_FORCECLICKPOPINWORLDSTATE_OFFSET))(this);
		}

		::System::Boolean __base_Equals(::System::Object* P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_EQUALS_OFFSET))(this, P0);
		}

		::System::Boolean __base_ForceClickPopInWorldState()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_FORCECLICKPOPINWORLDSTATE_OFFSET))(this);
		}

		::System::Int32 __base_get_GetAreaMapPanelConfigId_Internal()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GET_GETAREAMAPPANELCONFIGID_INTERNAL_OFFSET))(this);
		}

		::System::String* __base_GetBanner()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETBANNER_OFFSET))(this);
		}

		::System::String* __base_GetIconWidgetName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETICONWIDGETNAME_OFFSET))(this);
		}

		::System::UInt64 __base_GetKey()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETKEY_OFFSET))(this);
		}

		::System::String* __base_GetTitleKey()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETTITLEKEY_OFFSET))(this);
		}

		::System::String* __base_GetTitleText()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETTITLETEXT_OFFSET))(this);
		}

		::Struct_2_032E3093F309FC91 __base_GetWorldPosition()
		{
			return ((::Struct_2_032E3093F309FC91(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_GETWORLDPOSITION_OFFSET))(this);
		}

		::System::Boolean __base_IsInWorldStateLock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_ISINWORLDSTATELOCK_OFFSET))(this);
		}

		::System::Boolean __base_IsUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_ISUNLOCK_OFFSET))(this);
		}

		::System::Void __base_OnShowPanel(::MoleMole::UIUrbanMapPointGroupWidgetContext* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIUrbanMapPointGroupWidgetContext*))((::PBYTE)hIl2Cpp + MOLEMOLE_UITHREEDMAPELEMENT_PORTALCONTEXT___BASE_ONSHOWPANEL_OFFSET))(this, P0);
		}
	};
}
