#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/MoleMole/UIWindowController.h"
#include "unitysdk/UnityEngine/Vector2.h"

class Class_1_1662E12EB5FB0120;
class Class_2_B4378B46E0020E85;
namespace MoleMole { class UIControllerContextBase; }

#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_DOWNBTN_OFFSET UNITYSDK_OFFSET(0x162C7130)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_ISTICKLOOP_OFFSET UNITYSDK_OFFSET(0x162C7100)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_LEFTBTN_OFFSET UNITYSDK_OFFSET(0x162C7140)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_RIGHTBTN_OFFSET UNITYSDK_OFFSET(0x162C7150)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_UPBTN_OFFSET UNITYSDK_OFFSET(0x162C7120)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x162C70F0)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0x162C7780)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONPREUPDATE_OFFSET UNITYSDK_OFFSET(0x162C78F0)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0x162C7840)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x162C7370)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x162C7160)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x162C7580)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_SET_ISTICKLOOP_OFFSET UNITYSDK_OFFSET(0x162C7110)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x162C7BC0)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0x162C7CF0)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0x162C7D80)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x162C7C40)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x162C7C50)
#define MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x162C7C60)

namespace MoleMole
{
	inline static constexpr unsigned int UIVirtualGamepadDpadBaseController_TypeDefinitionIndex = 90074;

	class UIVirtualGamepadDpadBaseController : public ::MoleMole::UIWindowController
	{
	public:
		::System::Boolean _IsTickLoop_k__BackingField; // 0x318
		::Class_2_B4378B46E0020E85* _UpBtn_k__BackingField; // 0x320
		::Class_2_B4378B46E0020E85* _DownBtn_k__BackingField; // 0x328
		::Class_2_B4378B46E0020E85* _LeftBtn_k__BackingField; // 0x330
		::Class_2_B4378B46E0020E85* _RightBtn_k__BackingField; // 0x338
		::Class_1_1662E12EB5FB0120* _holdUp; // 0x340
		::Class_1_1662E12EB5FB0120* _holdDown; // 0x348
		::Class_1_1662E12EB5FB0120* _holdLeft; // 0x350
		::Class_1_1662E12EB5FB0120* _holdRight; // 0x358
		::UnityEngine::Vector2 _holdInput; // 0x360

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Boolean get_IsTickLoop()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_ISTICKLOOP_OFFSET))(this);
		}

		::System::Void set_IsTickLoop(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_SET_ISTICKLOOP_OFFSET))(this, value);
		}

		::Class_2_B4378B46E0020E85* get_UpBtn()
		{
			return ((::Class_2_B4378B46E0020E85*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_UPBTN_OFFSET))(this);
		}

		::Class_2_B4378B46E0020E85* get_DownBtn()
		{
			return ((::Class_2_B4378B46E0020E85*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_DOWNBTN_OFFSET))(this);
		}

		::Class_2_B4378B46E0020E85* get_LeftBtn()
		{
			return ((::Class_2_B4378B46E0020E85*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_LEFTBTN_OFFSET))(this);
		}

		::Class_2_B4378B46E0020E85* get_RightBtn()
		{
			return ((::Class_2_B4378B46E0020E85*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_GET_RIGHTBTN_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnPreUpdate(::System::Single deltaTime)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER_ONPREUPDATE_OFFSET))(this, deltaTime);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIVIRTUALGAMEPADDPADBASECONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}
	};
}
