#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_A047EA5169B6B30F;
class Class_2_0946524052D5EA18;
class Class_2_0A55B5A82A61DAFA;
class Class_2_14E7CE92E8A3183F;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIYorozuyaAbyssWidgetController; }

#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETABYSSQUESTISUNLOCK_OFFSET UNITYSDK_OFFSET(0x10421170)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETHOLLOWQUESTCFG_OFFSET UNITYSDK_OFFSET(0x10421EC0)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETISUNLOCK_OFFSET UNITYSDK_OFFSET(0x10421CD0)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETQUESTID_OFFSET UNITYSDK_OFFSET(0x10421E60)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GET_ISSELECTED_OFFSET UNITYSDK_OFFSET(0x10420940)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ISNEW_OFFSET UNITYSDK_OFFSET(0x10421550)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONCLICLITEM_OFFSET UNITYSDK_OFFSET(0x104216A0)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x1041FE80)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONLAYOUTCHANGEREFRESH_OFFSET UNITYSDK_OFFSET(0x1041FA90)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x1041FA20)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONREMOVESELECT_OFFSET UNITYSDK_OFFSET(0x10420FA0)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONSELECT_OFFSET UNITYSDK_OFFSET(0x10420AF0)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x1041FF10)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x1041FD10)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_REFRESHSKIN_OFFSET UNITYSDK_OFFSET(0x10420040)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_SETDATA_OFFSET UNITYSDK_OFFSET(0x1041FFA0)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_SETEMPTYSTATE_OFFSET UNITYSDK_OFFSET(0x10420180)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_SETPARENTWIDGET_OFFSET UNITYSDK_OFFSET(0x10421120)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_UPDATEUI_OFFSET UNITYSDK_OFFSET(0x10420290)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x10421F10)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x10421F70)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x10422000)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x10422090)
#define MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x10422120)

namespace MoleMole
{
	inline static constexpr unsigned int UIYorozuyaAbyssRowChildWindowController_TypeDefinitionIndex = 66414;

	class UIYorozuyaAbyssRowChildWindowController : public ::MoleMole::UIWidgetController
	{
	public:
		::Class_2_0946524052D5EA18* _view; // 0x2C0
		::MoleMole::UIYorozuyaAbyssWidgetController* parentWidget; // 0x2C8
		::Class_2_14E7CE92E8A3183F* _mData; // 0x2D0
		::Class_2_0A55B5A82A61DAFA* _hollowQuestCfg; // 0x2D8
		::Class_1_A047EA5169B6B30F* questInfo; // 0x2E0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void SetData(::Class_2_14E7CE92E8A3183F* data)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_14E7CE92E8A3183F*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_SETDATA_OFFSET))(this, data);
		}

		::System::Void SetEmptyState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_SETEMPTYSTATE_OFFSET))(this);
		}

		::System::Void RefreshSkin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_REFRESHSKIN_OFFSET))(this);
		}

		::System::Void OnLayoutChangeRefresh()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONLAYOUTCHANGEREFRESH_OFFSET))(this);
		}

		::System::Boolean get_IsSelected()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GET_ISSELECTED_OFFSET))(this);
		}

		::System::Void SetParentWidget(::MoleMole::UIYorozuyaAbyssWidgetController* parent)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIYorozuyaAbyssWidgetController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_SETPARENTWIDGET_OFFSET))(this, parent);
		}

		::System::Void UpdateUI()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_UPDATEUI_OFFSET))(this);
		}

		::System::Boolean GetAbyssQuestIsUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETABYSSQUESTISUNLOCK_OFFSET))(this);
		}

		::System::Boolean IsNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ISNEW_OFFSET))(this);
		}

		::System::Void OnCliclItem()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONCLICLITEM_OFFSET))(this);
		}

		::System::Void OnSelect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONSELECT_OFFSET))(this);
		}

		::System::Void OnRemoveSelect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_ONREMOVESELECT_OFFSET))(this);
		}

		::System::Boolean GetIsUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETISUNLOCK_OFFSET))(this);
		}

		::System::Int32 GetQuestID()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETQUESTID_OFFSET))(this);
		}

		::Class_2_0A55B5A82A61DAFA* GetHollowQuestCfg()
		{
			return ((::Class_2_0A55B5A82A61DAFA*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER_GETHOLLOWQUESTCFG_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAABYSSROWCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}
	};
}
