#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_7A4252233BCEB3A9.h"
#include "unitysdk/Enum_3_8E90989A26BC6232.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_5DA2E7556103D5A3_292;
class Class_2_0A55B5A82A61DAFA;
class Class_2_14E7CE92E8A3183F;
class Class_2_208CC9941471731A_576;
class Class_2_79AE422BA06F6D26_207;
class Class_2_E621E51D351EB960;
class Class_2_F69D29AB796376C2;
namespace MoleMole { class ScrollViewItemWidgetController; }
namespace MoleMole { class UIAbyssBuffRowWidgetController; }
namespace MoleMole { class UIAbyssS2HeatRowWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIYorozuyaAbyssS2WidgetController; }
namespace MoleMole { class UIYorozuyaS2DifficultyInfoWidgetController_AbyssHeatData; }
namespace System { class Action; }
namespace System { class EventArgs; }
namespace System { template <typename T> class Func_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_CANCELBUFFSELECT_OFFSET UNITYSDK_OFFSET(0x14915E30)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_CREATEHEATITEMWIDGET_OFFSET UNITYSDK_OFFSET(0x14913B40)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GETABYSSPOINT_OFFSET UNITYSDK_OFFSET(0x149171D0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GETBUFFCTRL_OFFSET UNITYSDK_OFFSET(0x14915C30)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GETWRAPPEDITEMDATALIST_OFFSET UNITYSDK_OFFSET(0x14916910)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET UNITYSDK_OFFSET(0x14918540)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_ISHOBAPREFAC_OFFSET UNITYSDK_OFFSET(0x14913F50)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_ISPERIOD_OFFSET UNITYSDK_OFFSET(0x14913D80)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_QUESTID_OFFSET UNITYSDK_OFFSET(0x149146B0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET__CURRSELECTEQUIPMENTID_OFFSET UNITYSDK_OFFSET(0x14918550)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_HASHEAT_OFFSET UNITYSDK_OFFSET(0x14916130)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_INITHEATCONFIG_OFFSET UNITYSDK_OFFSET(0x14916460)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISDUNGEONFIRSTPASS_OFFSET UNITYSDK_OFFSET(0x14917500)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISHEATLISTOPEN_OFFSET UNITYSDK_OFFSET(0x14917160)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISNEW_OFFSET UNITYSDK_OFFSET(0x149183F0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISPERIODFIRSTPASS_OFFSET UNITYSDK_OFFSET(0x14917630)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONABYSSSERVERDATANOTIFY_OFFSET UNITYSDK_OFFSET(0x14913C30)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONBUFFSELECT_OFFSET UNITYSDK_OFFSET(0x14915F40)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x14913A30)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONEQUIPMENTSELECT_OFFSET UNITYSDK_OFFSET(0x14915EE0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONHEATBTNCLICK_OFFSET UNITYSDK_OFFSET(0x14916BF0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONHEATSELECT_OFFSET UNITYSDK_OFFSET(0x14918280)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONINFOBTNCLICK_OFFSET UNITYSDK_OFFSET(0x149176C0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x149179B0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x14917790)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONSELECTEQUIPMENTBTNCLICK_OFFSET UNITYSDK_OFFSET(0x14914060)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x14913960)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x14913AC0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x149131D0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x149138F0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHAVATARVIEW_OFFSET UNITYSDK_OFFSET(0x14915570)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHBUFFVIEW_OFFSET UNITYSDK_OFFSET(0x14913DE0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHEQUIPMENTVIEW_OFFSET UNITYSDK_OFFSET(0x149146D0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHHEATVIEW_1_OFFSET UNITYSDK_OFFSET(0x149165E0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHHEATVIEW_OFFSET UNITYSDK_OFFSET(0x14914990)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHHOBAPREFACVIEW_OFFSET UNITYSDK_OFFSET(0x14913FB0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHPERIODVIEW_OFFSET UNITYSDK_OFFSET(0x14914610)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHREWARDVIEW_OFFSET UNITYSDK_OFFSET(0x149158B0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHTEXTVIEW_OFFSET UNITYSDK_OFFSET(0x14914C20)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHVIEWINNER_OFFSET UNITYSDK_OFFSET(0x14914590)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0x149180F0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHVISIBLEVIEW_OFFSET UNITYSDK_OFFSET(0x14914460)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_SETARROWSTATE_OFFSET UNITYSDK_OFFSET(0x149161A0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_SHOWHEATNEWBIE_OFFSET UNITYSDK_OFFSET(0x149162D0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0x149180B0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x149185A0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER__ONHEATBTNCLICK_B__27_0_OFFSET UNITYSDK_OFFSET(0x14918730)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER__ONUIINIT_B__1_0_OFFSET UNITYSDK_OFFSET(0x14918720)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x14918850)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x149188E0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0x14918910)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x149189A0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x149189B0)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x14918A40)
#define MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x14918AD0)

namespace MoleMole
{
	inline static constexpr unsigned int UIYorozuyaS2DifficultyInfoWidgetController_TypeDefinitionIndex = 77097;

	class UIYorozuyaS2DifficultyInfoWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		::Class_2_79AE422BA06F6D26_207* _view; // 0x2C0
		::System::Collections::Generic::List_1<::System::Int32>* _buffs; // 0x2C8
		::System::Int32 _currSelectBuffID; // 0x2D0
		::Class_2_208CC9941471731A_576* _currSelectBuffConfig; // 0x2D8
		::Class_1_5DA2E7556103D5A3_292* _currSelectEquipmentConfig; // 0x2E0
		::System::Collections::Generic::List_1<::Class_2_208CC9941471731A_576*>* _heatConfigs; // 0x2E8
		::System::Collections::Generic::List_1<::MoleMole::UIAbyssS2HeatRowWidgetController*>* _heatWidgets; // 0x2F0
		::Class_2_E621E51D351EB960* _abyssModel; // 0x2F8
		::Class_2_14E7CE92E8A3183F* _dungeonConfig; // 0x300
		::Class_2_0A55B5A82A61DAFA* _questConfig; // 0x308
		::Class_2_F69D29AB796376C2* _questTemplate; // 0x310
		::MoleMole::UIYorozuyaAbyssS2WidgetController* _parentCtrl; // 0x318

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUICLOSE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::MoleMole::ScrollViewItemWidgetController* CreateHeatItemWidget(::Enum_3_7A4252233BCEB3A9 arg1, ::System::Func_1<::MoleMole::UIControlReference*>* arg2)
		{
			return ((::MoleMole::ScrollViewItemWidgetController*(*)(::PVOID, ::Enum_3_7A4252233BCEB3A9, ::System::Func_1<::MoleMole::UIControlReference*>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_CREATEHEATITEMWIDGET_OFFSET))(this, arg1, arg2);
		}

		::System::Void OnAbyssServerDataNotify(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONABYSSSERVERDATANOTIFY_OFFSET))(this, args);
		}

		::System::Void OnSelectEquipmentBtnClick(::System::Action* lineupSelectAction)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONSELECTEQUIPMENTBTNCLICK_OFFSET))(this, lineupSelectAction);
		}

		::System::Void RefreshVisibleView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHVISIBLEVIEW_OFFSET))(this);
		}

		::System::Void RefreshViewInner()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHVIEWINNER_OFFSET))(this);
		}

		::System::Void RefreshPeriodView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHPERIODVIEW_OFFSET))(this);
		}

		::System::Void RefreshHobaPrefacView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHHOBAPREFACVIEW_OFFSET))(this);
		}

		::System::Void RefreshAvatarView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHAVATARVIEW_OFFSET))(this);
		}

		::System::Void RefreshRewardView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHREWARDVIEW_OFFSET))(this);
		}

		::System::Void RefreshBuffView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHBUFFVIEW_OFFSET))(this);
		}

		::MoleMole::UIAbyssBuffRowWidgetController* GetBuffCtrl(::System::Int32 index)
		{
			return ((::MoleMole::UIAbyssBuffRowWidgetController*(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GETBUFFCTRL_OFFSET))(this, index);
		}

		::System::Void OnEquipmentSelect(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONEQUIPMENTSELECT_OFFSET))(this, args);
		}

		::System::Void RefreshEquipmentView(::System::Int32 equipmentID)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHEQUIPMENTVIEW_OFFSET))(this, equipmentID);
		}

		::System::Void OnBuffSelect(::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONBUFFSELECT_OFFSET))(this, index);
		}

		::System::Void CancelBuffSelect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_CANCELBUFFSELECT_OFFSET))(this);
		}

		::System::Void RefreshHeatView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHHEATVIEW_OFFSET))(this);
		}

		::System::Void ShowHeatNewbie(::System::Int32 newbieID)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_SHOWHEATNEWBIE_OFFSET))(this, newbieID);
		}

		::System::Void InitHeatConfig()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_INITHEATCONFIG_OFFSET))(this);
		}

		::System::Void RefreshHeatView_1(::System::Int32 heatCount)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHHEATVIEW_1_OFFSET))(this, heatCount);
		}

		::System::Collections::Generic::List_1<::MoleMole::UIYorozuyaS2DifficultyInfoWidgetController_AbyssHeatData*>* GetWrappedItemDataList(::System::Collections::Generic::List_1<::Class_2_208CC9941471731A_576*>* raw)
		{
			return ((::System::Collections::Generic::List_1<::MoleMole::UIYorozuyaS2DifficultyInfoWidgetController_AbyssHeatData*>*(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_208CC9941471731A_576*>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GETWRAPPEDITEMDATALIST_OFFSET))(this, raw);
		}

		::System::Void OnHeatBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONHEATBTNCLICK_OFFSET))(this);
		}

		::System::Void SetArrowState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_SETARROWSTATE_OFFSET))(this);
		}

		::System::Boolean IsHeatListOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISHEATLISTOPEN_OFFSET))(this);
		}

		::System::Void RefreshTextView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHTEXTVIEW_OFFSET))(this);
		}

		::System::Int32 GetAbyssPoint()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GETABYSSPOINT_OFFSET))(this);
		}

		::System::Boolean HasHeat()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_HASHEAT_OFFSET))(this);
		}

		::System::Boolean IsPeriodFirstPass(::System::Int32 questID)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISPERIODFIRSTPASS_OFFSET))(this, questID);
		}

		::System::Boolean IsDungeonFirstPass(::System::Int32 questID)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISDUNGEONFIRSTPASS_OFFSET))(this, questID);
		}

		::System::Void OnInfoBtnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONINFOBTNCLICK_OFFSET))(this);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Void RefreshView(::Class_2_14E7CE92E8A3183F* dungeonConfig)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_14E7CE92E8A3183F*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_REFRESHVIEW_OFFSET))(this, dungeonConfig);
		}

		::System::Void OnHeatSelect(::System::Int32 index, ::System::Boolean isSelect, ::System::Int32 id)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Boolean, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ONHEATSELECT_OFFSET))(this, index, isSelect, id);
		}

		::System::Boolean IsNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_ISNEW_OFFSET))(this);
		}

		::System::Int32 get_QuestID()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_QUESTID_OFFSET))(this);
		}

		::System::Boolean get_isPeriod()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_ISPERIOD_OFFSET))(this);
		}

		::System::Boolean get_isHobaPrefac()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_ISHOBAPREFAC_OFFSET))(this);
		}

		::Enum_3_8E90989A26BC6232 get_HotSwitchRootLayerState()
		{
			return ((::Enum_3_8E90989A26BC6232(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET))(this);
		}

		::System::Int32 get__currSelectEquipmentID()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER_GET__CURRSELECTEQUIPMENTID_OFFSET))(this);
		}

		::System::Void _OnUIInit_b__1_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER__ONUIINIT_B__1_0_OFFSET))(this);
		}

		::System::Void _OnHeatBtnClick_b__27_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER__ONHEATBTNCLICK_B__27_0_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYAS2DIFFICULTYINFOWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
