#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIWidgetController.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_1_16C7607DC7EE71E8;
class Class_1_28C0FDDF1076A6D9;
class Class_1_E9529ED64113E4E9;
class Class_2_F9471F3BB5949932_14;
namespace MoleMole { class UIControlReference; }
namespace System { class String; }
namespace UnityEngine::UI { class RawImage; }

#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x1514CC70)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0x1514E780)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONPRESSUREBTNCLICKHANDLE_OFFSET UNITYSDK_OFFSET(0x1514CD00)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x1514E910)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x1514C850)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_PLAYMAPLOGO_OFFSET UNITYSDK_OFFSET(0x1514E650)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETLEVELINFO_OFFSET UNITYSDK_OFFSET(0x1514D240)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETLOGOINFO_OFFSET UNITYSDK_OFFSET(0x1514D4D0)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETNOISE_OFFSET UNITYSDK_OFFSET(0x1514E2B0)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETPROGRESS_OFFSET UNITYSDK_OFFSET(0x1514D670)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETTIMECOST_OFFSET UNITYSDK_OFFSET(0x1514E160)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETVIDEINFO_OFFSET UNITYSDK_OFFSET(0x1514D000)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_UPDATERALLYQUESTVIEW_OFFSET UNITYSDK_OFFSET(0x1514D1C0)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER__CCTOR_OFFSET UNITYSDK_OFFSET(0x1514EA90)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x1514E9F0)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER__SETVIDEINFO_B__4_0_OFFSET UNITYSDK_OFFSET(0x1514EAB0)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x1514EAF0)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0x1514EB80)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x1514EC10)
#define MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x1514ECA0)

namespace MoleMole
{
	inline static constexpr unsigned int UIYorozuyaRallyVideoInfoWidgetController_TypeDefinitionIndex = 62972;

	class UIYorozuyaRallyVideoInfoWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		static ::UnityEngine::Vector3* StaticGet_DEFAULT_NEEDLE_ANGLE()
		{
			return (::UnityEngine::Vector3*)Il2CppClass::FromTypeDefinitionIndex(UIYorozuyaRallyVideoInfoWidgetController_TypeDefinitionIndex)->GetStaticField(0x108A0);
		}
		::Class_2_F9471F3BB5949932_14* _view; // 0x2C0
		::UnityEngine::UI::RawImage* _videoRawImg; // 0x2C8
		::Class_1_E9529ED64113E4E9* _playerHelper; // 0x2D0
		::Class_1_28C0FDDF1076A6D9* _rallyQuest; // 0x2D8
		::System::Boolean _isOpenVideoPanel; // 0x2E0
		::System::String* _lastNeedleType; // 0x2E8
		::Class_1_16C7607DC7EE71E8* _rallyData; // 0x2F0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER__CCTOR_OFFSET))();
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnPressureBtnClickHandle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONPRESSUREBTNCLICKHANDLE_OFFSET))(this);
		}

		::System::Void SetVideInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETVIDEINFO_OFFSET))(this);
		}

		::System::Void UpdateRallyQuestView(::Class_1_28C0FDDF1076A6D9* rallyQuest)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_28C0FDDF1076A6D9*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_UPDATERALLYQUESTVIEW_OFFSET))(this, rallyQuest);
		}

		::System::Void SetProgress()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETPROGRESS_OFFSET))(this);
		}

		::System::Void SetTimeCost(::System::Int32 c)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETTIMECOST_OFFSET))(this, c);
		}

		::System::Void SetLogoInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETLOGOINFO_OFFSET))(this);
		}

		::System::Void SetLevelInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETLEVELINFO_OFFSET))(this);
		}

		::System::Void SetNoise()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_SETNOISE_OFFSET))(this);
		}

		::System::Void PlayMapLogo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_PLAYMAPLOGO_OFFSET))(this);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void _SetVideInfo_b__4_0(::Class_1_E9529ED64113E4E9* vp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_E9529ED64113E4E9*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER__SETVIDEINFO_B__4_0_OFFSET))(this, vp);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYARALLYVIDEOINFOWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}
	};
}
